schema_version = 1
parent = "CA"

[[region]]
id = "CA-AB"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Alberta"
"fr" = "Alberta"

[region.slugs]
"ca" = "alberta"
"da" = "alberta"
"de" = "alberta"
"et" = "alberta"
"en" = "alberta"
"es" = "alberta"
"fr" = "alberta"
"oc" = "alberta"
"lb" = "alberta"
"ga" = "alberta"
"hr" = "alberta"
"it" = "alberta"
"lt" = "alberta"
"lv" = "alberta"
"nl" = "alberta"
"hu" = "alberta"
"no" = "alberta"
"pl" = "alberta"
"pt-PT" = "alberta"
"ro" = "alberta"
"sk" = "alberta"
"sl" = "alberta"
"sr" = "alberta"
"fi" = "alberta"
"sv" = "alberta"
"ru" = "alberta"
"uk" = "alberta"
"el" = "alberta"
"zh-CN" = "alberta"
"zh-TW" = "alberta"
"ja" = "alberta"
"ko" = "alberta"
"bg" = "alberta"
"cs" = "alberta"
"mt" = "alberta"

[region.codes]
iso_3166_2 = "CA-AB"

[[region]]
id = "CA-BC"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "British Columbia"
"fr" = "Colombie-Britannique"

[region.slugs]
"ca" = "british-columbia"
"da" = "british-columbia"
"de" = "british-columbia"
"et" = "british-columbia"
"en" = "british-columbia"
"es" = "british-columbia"
"fr" = "colombie-britannique"
"oc" = "british-columbia"
"lb" = "british-columbia"
"ga" = "british-columbia"
"hr" = "british-columbia"
"it" = "british-columbia"
"lt" = "british-columbia"
"lv" = "british-columbia"
"nl" = "british-columbia"
"hu" = "british-columbia"
"no" = "british-columbia"
"pl" = "british-columbia"
"pt-PT" = "british-columbia"
"ro" = "british-columbia"
"sk" = "british-columbia"
"sl" = "british-columbia"
"sr" = "british-columbia"
"fi" = "british-columbia"
"sv" = "british-columbia"
"ru" = "british-columbia"
"uk" = "british-columbia"
"el" = "british-columbia"
"zh-CN" = "british-columbia"
"zh-TW" = "british-columbia"
"ja" = "british-columbia"
"ko" = "british-columbia"
"bg" = "british-columbia"
"cs" = "british-columbia"
"mt" = "british-columbia"

[region.codes]
iso_3166_2 = "CA-BC"

[[region]]
id = "CA-MB"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Manitoba"
"fr" = "Manitoba"

[region.slugs]
"ca" = "manitoba"
"da" = "manitoba"
"de" = "manitoba"
"et" = "manitoba"
"en" = "manitoba"
"es" = "manitoba"
"fr" = "manitoba"
"oc" = "manitoba"
"lb" = "manitoba"
"ga" = "manitoba"
"hr" = "manitoba"
"it" = "manitoba"
"lt" = "manitoba"
"lv" = "manitoba"
"nl" = "manitoba"
"hu" = "manitoba"
"no" = "manitoba"
"pl" = "manitoba"
"pt-PT" = "manitoba"
"ro" = "manitoba"
"sk" = "manitoba"
"sl" = "manitoba"
"sr" = "manitoba"
"fi" = "manitoba"
"sv" = "manitoba"
"ru" = "manitoba"
"uk" = "manitoba"
"el" = "manitoba"
"zh-CN" = "manitoba"
"zh-TW" = "manitoba"
"ja" = "manitoba"
"ko" = "manitoba"
"bg" = "manitoba"
"cs" = "manitoba"
"mt" = "manitoba"

[region.codes]
iso_3166_2 = "CA-MB"

[[region]]
id = "CA-NB"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "New Brunswick"
"fr" = "Nouveau-Brunswick"

[region.slugs]
"ca" = "new-brunswick"
"da" = "new-brunswick"
"de" = "new-brunswick"
"et" = "new-brunswick"
"en" = "new-brunswick"
"es" = "new-brunswick"
"fr" = "nouveau-brunswick"
"oc" = "new-brunswick"
"lb" = "new-brunswick"
"ga" = "new-brunswick"
"hr" = "new-brunswick"
"it" = "new-brunswick"
"lt" = "new-brunswick"
"lv" = "new-brunswick"
"nl" = "new-brunswick"
"hu" = "new-brunswick"
"no" = "new-brunswick"
"pl" = "new-brunswick"
"pt-PT" = "new-brunswick"
"ro" = "new-brunswick"
"sk" = "new-brunswick"
"sl" = "new-brunswick"
"sr" = "new-brunswick"
"fi" = "new-brunswick"
"sv" = "new-brunswick"
"ru" = "new-brunswick"
"uk" = "new-brunswick"
"el" = "new-brunswick"
"zh-CN" = "new-brunswick"
"zh-TW" = "new-brunswick"
"ja" = "new-brunswick"
"ko" = "new-brunswick"
"bg" = "new-brunswick"
"cs" = "new-brunswick"
"mt" = "new-brunswick"

[region.codes]
iso_3166_2 = "CA-NB"

[[region]]
id = "CA-NL"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Newfoundland and Labrador"
"fr" = "Terre-Neuve-et-Labrador"

[region.slugs]
"ca" = "newfoundland-and-labrador"
"da" = "newfoundland-and-labrador"
"de" = "newfoundland-and-labrador"
"et" = "newfoundland-and-labrador"
"en" = "newfoundland-and-labrador"
"es" = "newfoundland-and-labrador"
"fr" = "terre-neuve-et-labrador"
"oc" = "newfoundland-and-labrador"
"lb" = "newfoundland-and-labrador"
"ga" = "newfoundland-and-labrador"
"hr" = "newfoundland-and-labrador"
"it" = "newfoundland-and-labrador"
"lt" = "newfoundland-and-labrador"
"lv" = "newfoundland-and-labrador"
"nl" = "newfoundland-and-labrador"
"hu" = "newfoundland-and-labrador"
"no" = "newfoundland-and-labrador"
"pl" = "newfoundland-and-labrador"
"pt-PT" = "newfoundland-and-labrador"
"ro" = "newfoundland-and-labrador"
"sk" = "newfoundland-and-labrador"
"sl" = "newfoundland-and-labrador"
"sr" = "newfoundland-and-labrador"
"fi" = "newfoundland-and-labrador"
"sv" = "newfoundland-and-labrador"
"ru" = "newfoundland-and-labrador"
"uk" = "newfoundland-and-labrador"
"el" = "newfoundland-and-labrador"
"zh-CN" = "newfoundland-and-labrador"
"zh-TW" = "newfoundland-and-labrador"
"ja" = "newfoundland-and-labrador"
"ko" = "newfoundland-and-labrador"
"bg" = "newfoundland-and-labrador"
"cs" = "newfoundland-and-labrador"
"mt" = "newfoundland-and-labrador"

[region.codes]
iso_3166_2 = "CA-NL"

[[region]]
id = "CA-NS"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Nova Scotia"
"fr" = "Nouvelle-Écosse"

[region.slugs]
"ca" = "nova-scotia"
"da" = "nova-scotia"
"de" = "nova-scotia"
"et" = "nova-scotia"
"en" = "nova-scotia"
"es" = "nova-scotia"
"fr" = "nouvelle-écosse"
"oc" = "nova-scotia"
"lb" = "nova-scotia"
"ga" = "nova-scotia"
"hr" = "nova-scotia"
"it" = "nova-scotia"
"lt" = "nova-scotia"
"lv" = "nova-scotia"
"nl" = "nova-scotia"
"hu" = "nova-scotia"
"no" = "nova-scotia"
"pl" = "nova-scotia"
"pt-PT" = "nova-scotia"
"ro" = "nova-scotia"
"sk" = "nova-scotia"
"sl" = "nova-scotia"
"sr" = "nova-scotia"
"fi" = "nova-scotia"
"sv" = "nova-scotia"
"ru" = "nova-scotia"
"uk" = "nova-scotia"
"el" = "nova-scotia"
"zh-CN" = "nova-scotia"
"zh-TW" = "nova-scotia"
"ja" = "nova-scotia"
"ko" = "nova-scotia"
"bg" = "nova-scotia"
"cs" = "nova-scotia"
"mt" = "nova-scotia"

[region.codes]
iso_3166_2 = "CA-NS"

[[region]]
id = "CA-ON"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Ontario"
"fr" = "Ontario"

[region.slugs]
"ca" = "ontario"
"da" = "ontario"
"de" = "ontario"
"et" = "ontario"
"en" = "ontario"
"es" = "ontario"
"fr" = "ontario"
"oc" = "ontario"
"lb" = "ontario"
"ga" = "ontario"
"hr" = "ontario"
"it" = "ontario"
"lt" = "ontario"
"lv" = "ontario"
"nl" = "ontario"
"hu" = "ontario"
"no" = "ontario"
"pl" = "ontario"
"pt-PT" = "ontario"
"ro" = "ontario"
"sk" = "ontario"
"sl" = "ontario"
"sr" = "ontario"
"fi" = "ontario"
"sv" = "ontario"
"ru" = "ontario"
"uk" = "ontario"
"el" = "ontario"
"zh-CN" = "ontario"
"zh-TW" = "ontario"
"ja" = "ontario"
"ko" = "ontario"
"bg" = "ontario"
"cs" = "ontario"
"mt" = "ontario"

[region.codes]
iso_3166_2 = "CA-ON"

[[region]]
id = "CA-PE"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Prince Edward Island"
"fr" = "Île-du-Prince-Édouard"

[region.slugs]
"ca" = "prince-edward-island"
"da" = "prince-edward-island"
"de" = "prince-edward-island"
"et" = "prince-edward-island"
"en" = "prince-edward-island"
"es" = "prince-edward-island"
"fr" = "île-du-prince-édouard"
"oc" = "prince-edward-island"
"lb" = "prince-edward-island"
"ga" = "prince-edward-island"
"hr" = "prince-edward-island"
"it" = "prince-edward-island"
"lt" = "prince-edward-island"
"lv" = "prince-edward-island"
"nl" = "prince-edward-island"
"hu" = "prince-edward-island"
"no" = "prince-edward-island"
"pl" = "prince-edward-island"
"pt-PT" = "prince-edward-island"
"ro" = "prince-edward-island"
"sk" = "prince-edward-island"
"sl" = "prince-edward-island"
"sr" = "prince-edward-island"
"fi" = "prince-edward-island"
"sv" = "prince-edward-island"
"ru" = "prince-edward-island"
"uk" = "prince-edward-island"
"el" = "prince-edward-island"
"zh-CN" = "prince-edward-island"
"zh-TW" = "prince-edward-island"
"ja" = "prince-edward-island"
"ko" = "prince-edward-island"
"bg" = "prince-edward-island"
"cs" = "prince-edward-island"
"mt" = "prince-edward-island"

[region.codes]
iso_3166_2 = "CA-PE"

[[region]]
id = "CA-QC"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Quebec"
"fr" = "Québec"

[region.slugs]
"ca" = "quebec"
"da" = "quebec"
"de" = "quebec"
"et" = "quebec"
"en" = "quebec"
"es" = "quebec"
"fr" = "québec"
"oc" = "quebec"
"lb" = "quebec"
"ga" = "quebec"
"hr" = "quebec"
"it" = "quebec"
"lt" = "quebec"
"lv" = "quebec"
"nl" = "quebec"
"hu" = "quebec"
"no" = "quebec"
"pl" = "quebec"
"pt-PT" = "quebec"
"ro" = "quebec"
"sk" = "quebec"
"sl" = "quebec"
"sr" = "quebec"
"fi" = "quebec"
"sv" = "quebec"
"ru" = "quebec"
"uk" = "quebec"
"el" = "quebec"
"zh-CN" = "quebec"
"zh-TW" = "quebec"
"ja" = "quebec"
"ko" = "quebec"
"bg" = "quebec"
"cs" = "quebec"
"mt" = "quebec"

[region.codes]
iso_3166_2 = "CA-QC"

[[region]]
id = "CA-SK"
kind = "province"
official_languages = ["en", "fr"]

[region.names]
"en" = "Saskatchewan"
"fr" = "Saskatchewan"

[region.slugs]
"ca" = "saskatchewan"
"da" = "saskatchewan"
"de" = "saskatchewan"
"et" = "saskatchewan"
"en" = "saskatchewan"
"es" = "saskatchewan"
"fr" = "saskatchewan"
"oc" = "saskatchewan"
"lb" = "saskatchewan"
"ga" = "saskatchewan"
"hr" = "saskatchewan"
"it" = "saskatchewan"
"lt" = "saskatchewan"
"lv" = "saskatchewan"
"nl" = "saskatchewan"
"hu" = "saskatchewan"
"no" = "saskatchewan"
"pl" = "saskatchewan"
"pt-PT" = "saskatchewan"
"ro" = "saskatchewan"
"sk" = "saskatchewan"
"sl" = "saskatchewan"
"sr" = "saskatchewan"
"fi" = "saskatchewan"
"sv" = "saskatchewan"
"ru" = "saskatchewan"
"uk" = "saskatchewan"
"el" = "saskatchewan"
"zh-CN" = "saskatchewan"
"zh-TW" = "saskatchewan"
"ja" = "saskatchewan"
"ko" = "saskatchewan"
"bg" = "saskatchewan"
"cs" = "saskatchewan"
"mt" = "saskatchewan"

[region.codes]
iso_3166_2 = "CA-SK"

[[region]]
id = "CA-NT"
kind = "territory"
official_languages = ["en", "fr"]

[region.names]
"en" = "Northwest Territories"
"fr" = "Territoires du Nord-Ouest"

[region.slugs]
"ca" = "northwest-territories"
"da" = "northwest-territories"
"de" = "northwest-territories"
"et" = "northwest-territories"
"en" = "northwest-territories"
"es" = "northwest-territories"
"fr" = "territoires-du-nord-ouest"
"oc" = "northwest-territories"
"lb" = "northwest-territories"
"ga" = "northwest-territories"
"hr" = "northwest-territories"
"it" = "northwest-territories"
"lt" = "northwest-territories"
"lv" = "northwest-territories"
"nl" = "northwest-territories"
"hu" = "northwest-territories"
"no" = "northwest-territories"
"pl" = "northwest-territories"
"pt-PT" = "northwest-territories"
"ro" = "northwest-territories"
"sk" = "northwest-territories"
"sl" = "northwest-territories"
"sr" = "northwest-territories"
"fi" = "northwest-territories"
"sv" = "northwest-territories"
"ru" = "northwest-territories"
"uk" = "northwest-territories"
"el" = "northwest-territories"
"zh-CN" = "northwest-territories"
"zh-TW" = "northwest-territories"
"ja" = "northwest-territories"
"ko" = "northwest-territories"
"bg" = "northwest-territories"
"cs" = "northwest-territories"
"mt" = "northwest-territories"

[region.codes]
iso_3166_2 = "CA-NT"

[[region]]
id = "CA-NU"
kind = "territory"
official_languages = ["en", "fr"]

[region.names]
"en" = "Nunavut"
"fr" = "Nunavut"

[region.slugs]
"ca" = "nunavut"
"da" = "nunavut"
"de" = "nunavut"
"et" = "nunavut"
"en" = "nunavut"
"es" = "nunavut"
"fr" = "nunavut"
"oc" = "nunavut"
"lb" = "nunavut"
"ga" = "nunavut"
"hr" = "nunavut"
"it" = "nunavut"
"lt" = "nunavut"
"lv" = "nunavut"
"nl" = "nunavut"
"hu" = "nunavut"
"no" = "nunavut"
"pl" = "nunavut"
"pt-PT" = "nunavut"
"ro" = "nunavut"
"sk" = "nunavut"
"sl" = "nunavut"
"sr" = "nunavut"
"fi" = "nunavut"
"sv" = "nunavut"
"ru" = "nunavut"
"uk" = "nunavut"
"el" = "nunavut"
"zh-CN" = "nunavut"
"zh-TW" = "nunavut"
"ja" = "nunavut"
"ko" = "nunavut"
"bg" = "nunavut"
"cs" = "nunavut"
"mt" = "nunavut"

[region.codes]
iso_3166_2 = "CA-NU"

[[region]]
id = "CA-YT"
kind = "territory"
official_languages = ["en", "fr"]

[region.names]
"en" = "Yukon"
"fr" = "Yukon"

[region.slugs]
"ca" = "yukon"
"da" = "yukon"
"de" = "yukon"
"et" = "yukon"
"en" = "yukon"
"es" = "yukon"
"fr" = "yukon"
"oc" = "yukon"
"lb" = "yukon"
"ga" = "yukon"
"hr" = "yukon"
"it" = "yukon"
"lt" = "yukon"
"lv" = "yukon"
"nl" = "yukon"
"hu" = "yukon"
"no" = "yukon"
"pl" = "yukon"
"pt-PT" = "yukon"
"ro" = "yukon"
"sk" = "yukon"
"sl" = "yukon"
"sr" = "yukon"
"fi" = "yukon"
"sv" = "yukon"
"ru" = "yukon"
"uk" = "yukon"
"el" = "yukon"
"zh-CN" = "yukon"
"zh-TW" = "yukon"
"ja" = "yukon"
"ko" = "yukon"
"bg" = "yukon"
"cs" = "yukon"
"mt" = "yukon"

[region.codes]
iso_3166_2 = "CA-YT"
