schema_version = 1
parent = "DE"

[[region]]
id = "DE-BW"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Baden-Württemberg"
"en" = "Baden-Württemberg"
"es" = "Baden-Wurtemberg"
"fr" = "Bade-Wurtemberg"

[region.slugs]
"ca" = "baden-württemberg"
"da" = "baden-württemberg"
"de" = "baden-württemberg"
"et" = "baden-württemberg"
"en" = "baden-württemberg"
"es" = "baden-wurtemberg"
"fr" = "bade-wurtemberg"
"oc" = "baden-württemberg"
"lb" = "baden-württemberg"
"ga" = "baden-württemberg"
"hr" = "baden-württemberg"
"it" = "baden-württemberg"
"lt" = "baden-württemberg"
"lv" = "baden-württemberg"
"nl" = "baden-württemberg"
"hu" = "baden-württemberg"
"no" = "baden-württemberg"
"pl" = "baden-württemberg"
"pt-PT" = "baden-württemberg"
"ro" = "baden-württemberg"
"sk" = "baden-württemberg"
"sl" = "baden-württemberg"
"sr" = "baden-württemberg"
"fi" = "baden-württemberg"
"sv" = "baden-württemberg"
"ru" = "baden-württemberg"
"uk" = "baden-württemberg"
"el" = "baden-württemberg"
"zh-CN" = "baden-württemberg"
"zh-TW" = "baden-württemberg"
"ja" = "baden-württemberg"
"ko" = "baden-württemberg"
"bg" = "baden-württemberg"
"cs" = "baden-württemberg"
"mt" = "baden-württemberg"

[region.codes]
iso_3166_2 = "DE-BW"

[[region]]
id = "DE-BY"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Bayern"
"en" = "Bavaria"
"es" = "Baviera"
"fr" = "Bavière"

[region.slugs]
"ca" = "bavaria"
"da" = "bavaria"
"de" = "bayern"
"et" = "bavaria"
"en" = "bavaria"
"es" = "baviera"
"fr" = "bavière"
"oc" = "bavaria"
"lb" = "bavaria"
"ga" = "bavaria"
"hr" = "bavaria"
"it" = "bavaria"
"lt" = "bavaria"
"lv" = "bavaria"
"nl" = "bavaria"
"hu" = "bavaria"
"no" = "bavaria"
"pl" = "bavaria"
"pt-PT" = "bavaria"
"ro" = "bavaria"
"sk" = "bavaria"
"sl" = "bavaria"
"sr" = "bavaria"
"fi" = "bavaria"
"sv" = "bavaria"
"ru" = "bavaria"
"uk" = "bavaria"
"el" = "bavaria"
"zh-CN" = "bavaria"
"zh-TW" = "bavaria"
"ja" = "bavaria"
"ko" = "bavaria"
"bg" = "bavaria"
"cs" = "bavaria"
"mt" = "bavaria"

[region.codes]
iso_3166_2 = "DE-BY"

[[region]]
id = "DE-BE"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Berlin"
"en" = "Berlin"
"es" = "Berlín"
"fr" = "Berlin"

[region.slugs]
"ca" = "berlin"
"da" = "berlin"
"de" = "berlin"
"et" = "berlin"
"en" = "berlin"
"es" = "berlín"
"fr" = "berlin"
"oc" = "berlin"
"lb" = "berlin"
"ga" = "berlin"
"hr" = "berlin"
"it" = "berlin"
"lt" = "berlin"
"lv" = "berlin"
"nl" = "berlin"
"hu" = "berlin"
"no" = "berlin"
"pl" = "berlin"
"pt-PT" = "berlin"
"ro" = "berlin"
"sk" = "berlin"
"sl" = "berlin"
"sr" = "berlin"
"fi" = "berlin"
"sv" = "berlin"
"ru" = "berlin"
"uk" = "berlin"
"el" = "berlin"
"zh-CN" = "berlin"
"zh-TW" = "berlin"
"ja" = "berlin"
"ko" = "berlin"
"bg" = "berlin"
"cs" = "berlin"
"mt" = "berlin"

[region.codes]
iso_3166_2 = "DE-BE"

[[region]]
id = "DE-BB"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Brandenburg"
"en" = "Brandenburg"
"es" = "Brandeburgo"
"fr" = "Brandebourg"

[region.slugs]
"ca" = "brandenburg"
"da" = "brandenburg"
"de" = "brandenburg"
"et" = "brandenburg"
"en" = "brandenburg"
"es" = "brandeburgo"
"fr" = "brandebourg"
"oc" = "brandenburg"
"lb" = "brandenburg"
"ga" = "brandenburg"
"hr" = "brandenburg"
"it" = "brandenburg"
"lt" = "brandenburg"
"lv" = "brandenburg"
"nl" = "brandenburg"
"hu" = "brandenburg"
"no" = "brandenburg"
"pl" = "brandenburg"
"pt-PT" = "brandenburg"
"ro" = "brandenburg"
"sk" = "brandenburg"
"sl" = "brandenburg"
"sr" = "brandenburg"
"fi" = "brandenburg"
"sv" = "brandenburg"
"ru" = "brandenburg"
"uk" = "brandenburg"
"el" = "brandenburg"
"zh-CN" = "brandenburg"
"zh-TW" = "brandenburg"
"ja" = "brandenburg"
"ko" = "brandenburg"
"bg" = "brandenburg"
"cs" = "brandenburg"
"mt" = "brandenburg"

[region.codes]
iso_3166_2 = "DE-BB"

[[region]]
id = "DE-HB"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Bremen"
"en" = "Bremen"
"es" = "Bremen"
"fr" = "Brême"

[region.slugs]
"ca" = "bremen"
"da" = "bremen"
"de" = "bremen"
"et" = "bremen"
"en" = "bremen"
"es" = "bremen"
"fr" = "brême"
"oc" = "bremen"
"lb" = "bremen"
"ga" = "bremen"
"hr" = "bremen"
"it" = "bremen"
"lt" = "bremen"
"lv" = "bremen"
"nl" = "bremen"
"hu" = "bremen"
"no" = "bremen"
"pl" = "bremen"
"pt-PT" = "bremen"
"ro" = "bremen"
"sk" = "bremen"
"sl" = "bremen"
"sr" = "bremen"
"fi" = "bremen"
"sv" = "bremen"
"ru" = "bremen"
"uk" = "bremen"
"el" = "bremen"
"zh-CN" = "bremen"
"zh-TW" = "bremen"
"ja" = "bremen"
"ko" = "bremen"
"bg" = "bremen"
"cs" = "bremen"
"mt" = "bremen"

[region.codes]
iso_3166_2 = "DE-HB"

[[region]]
id = "DE-HH"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Hamburg"
"en" = "Hamburg"
"es" = "Hamburgo"
"fr" = "Hambourg"

[region.slugs]
"ca" = "hamburg"
"da" = "hamburg"
"de" = "hamburg"
"et" = "hamburg"
"en" = "hamburg"
"es" = "hamburgo"
"fr" = "hambourg"
"oc" = "hamburg"
"lb" = "hamburg"
"ga" = "hamburg"
"hr" = "hamburg"
"it" = "hamburg"
"lt" = "hamburg"
"lv" = "hamburg"
"nl" = "hamburg"
"hu" = "hamburg"
"no" = "hamburg"
"pl" = "hamburg"
"pt-PT" = "hamburg"
"ro" = "hamburg"
"sk" = "hamburg"
"sl" = "hamburg"
"sr" = "hamburg"
"fi" = "hamburg"
"sv" = "hamburg"
"ru" = "hamburg"
"uk" = "hamburg"
"el" = "hamburg"
"zh-CN" = "hamburg"
"zh-TW" = "hamburg"
"ja" = "hamburg"
"ko" = "hamburg"
"bg" = "hamburg"
"cs" = "hamburg"
"mt" = "hamburg"

[region.codes]
iso_3166_2 = "DE-HH"

[[region]]
id = "DE-HE"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Hessen"
"en" = "Hesse"
"es" = "Hesse"
"fr" = "Hesse"

[region.slugs]
"ca" = "hesse"
"da" = "hesse"
"de" = "hessen"
"et" = "hesse"
"en" = "hesse"
"es" = "hesse"
"fr" = "hesse"
"oc" = "hesse"
"lb" = "hesse"
"ga" = "hesse"
"hr" = "hesse"
"it" = "hesse"
"lt" = "hesse"
"lv" = "hesse"
"nl" = "hesse"
"hu" = "hesse"
"no" = "hesse"
"pl" = "hesse"
"pt-PT" = "hesse"
"ro" = "hesse"
"sk" = "hesse"
"sl" = "hesse"
"sr" = "hesse"
"fi" = "hesse"
"sv" = "hesse"
"ru" = "hesse"
"uk" = "hesse"
"el" = "hesse"
"zh-CN" = "hesse"
"zh-TW" = "hesse"
"ja" = "hesse"
"ko" = "hesse"
"bg" = "hesse"
"cs" = "hesse"
"mt" = "hesse"

[region.codes]
iso_3166_2 = "DE-HE"

[[region]]
id = "DE-MV"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Mecklenburg-Vorpommern"
"en" = "Mecklenburg-Western Pomerania"
"es" = "Mecklemburgo-Pomerania Occidental"
"fr" = "Mecklembourg-Poméranie-Occidentale"

[region.slugs]
"ca" = "mecklenburg-western-pomerania"
"da" = "mecklenburg-western-pomerania"
"de" = "mecklenburg-vorpommern"
"et" = "mecklenburg-western-pomerania"
"en" = "mecklenburg-western-pomerania"
"es" = "mecklemburgo-pomerania-occidental"
"fr" = "mecklembourg-poméranie-occidentale"
"oc" = "mecklenburg-western-pomerania"
"lb" = "mecklenburg-western-pomerania"
"ga" = "mecklenburg-western-pomerania"
"hr" = "mecklenburg-western-pomerania"
"it" = "mecklenburg-western-pomerania"
"lt" = "mecklenburg-western-pomerania"
"lv" = "mecklenburg-western-pomerania"
"nl" = "mecklenburg-western-pomerania"
"hu" = "mecklenburg-western-pomerania"
"no" = "mecklenburg-western-pomerania"
"pl" = "mecklenburg-western-pomerania"
"pt-PT" = "mecklenburg-western-pomerania"
"ro" = "mecklenburg-western-pomerania"
"sk" = "mecklenburg-western-pomerania"
"sl" = "mecklenburg-western-pomerania"
"sr" = "mecklenburg-western-pomerania"
"fi" = "mecklenburg-western-pomerania"
"sv" = "mecklenburg-western-pomerania"
"ru" = "mecklenburg-western-pomerania"
"uk" = "mecklenburg-western-pomerania"
"el" = "mecklenburg-western-pomerania"
"zh-CN" = "mecklenburg-western-pomerania"
"zh-TW" = "mecklenburg-western-pomerania"
"ja" = "mecklenburg-western-pomerania"
"ko" = "mecklenburg-western-pomerania"
"bg" = "mecklenburg-western-pomerania"
"cs" = "mecklenburg-western-pomerania"
"mt" = "mecklenburg-western-pomerania"

[region.codes]
iso_3166_2 = "DE-MV"

[[region]]
id = "DE-NI"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Niedersachsen"
"en" = "Lower Saxony"
"es" = "Baja Sajonia"
"fr" = "Basse-Saxe"

[region.slugs]
"ca" = "lower-saxony"
"da" = "lower-saxony"
"de" = "niedersachsen"
"et" = "lower-saxony"
"en" = "lower-saxony"
"es" = "baja-sajonia"
"fr" = "basse-saxe"
"oc" = "lower-saxony"
"lb" = "lower-saxony"
"ga" = "lower-saxony"
"hr" = "lower-saxony"
"it" = "lower-saxony"
"lt" = "lower-saxony"
"lv" = "lower-saxony"
"nl" = "lower-saxony"
"hu" = "lower-saxony"
"no" = "lower-saxony"
"pl" = "lower-saxony"
"pt-PT" = "lower-saxony"
"ro" = "lower-saxony"
"sk" = "lower-saxony"
"sl" = "lower-saxony"
"sr" = "lower-saxony"
"fi" = "lower-saxony"
"sv" = "lower-saxony"
"ru" = "lower-saxony"
"uk" = "lower-saxony"
"el" = "lower-saxony"
"zh-CN" = "lower-saxony"
"zh-TW" = "lower-saxony"
"ja" = "lower-saxony"
"ko" = "lower-saxony"
"bg" = "lower-saxony"
"cs" = "lower-saxony"
"mt" = "lower-saxony"

[region.codes]
iso_3166_2 = "DE-NI"

[[region]]
id = "DE-NW"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Nordrhein-Westfalen"
"en" = "North Rhine-Westphalia"
"es" = "Renania del Norte-Westfalia"
"fr" = "Rhénanie-du-Nord-Westphalie"

[region.slugs]
"ca" = "north-rhine-westphalia"
"da" = "north-rhine-westphalia"
"de" = "nordrhein-westfalen"
"et" = "north-rhine-westphalia"
"en" = "north-rhine-westphalia"
"es" = "renania-del-norte-westfalia"
"fr" = "rhénanie-du-nord-westphalie"
"oc" = "north-rhine-westphalia"
"lb" = "north-rhine-westphalia"
"ga" = "north-rhine-westphalia"
"hr" = "north-rhine-westphalia"
"it" = "north-rhine-westphalia"
"lt" = "north-rhine-westphalia"
"lv" = "north-rhine-westphalia"
"nl" = "north-rhine-westphalia"
"hu" = "north-rhine-westphalia"
"no" = "north-rhine-westphalia"
"pl" = "north-rhine-westphalia"
"pt-PT" = "north-rhine-westphalia"
"ro" = "north-rhine-westphalia"
"sk" = "north-rhine-westphalia"
"sl" = "north-rhine-westphalia"
"sr" = "north-rhine-westphalia"
"fi" = "north-rhine-westphalia"
"sv" = "north-rhine-westphalia"
"ru" = "north-rhine-westphalia"
"uk" = "north-rhine-westphalia"
"el" = "north-rhine-westphalia"
"zh-CN" = "north-rhine-westphalia"
"zh-TW" = "north-rhine-westphalia"
"ja" = "north-rhine-westphalia"
"ko" = "north-rhine-westphalia"
"bg" = "north-rhine-westphalia"
"cs" = "north-rhine-westphalia"
"mt" = "north-rhine-westphalia"

[region.codes]
iso_3166_2 = "DE-NW"

[[region]]
id = "DE-RP"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Rheinland-Pfalz"
"en" = "Rhineland-Palatinate"
"es" = "Renania-Palatinado"
"fr" = "Rhénanie-Palatinat"

[region.slugs]
"ca" = "rhineland-palatinate"
"da" = "rhineland-palatinate"
"de" = "rheinland-pfalz"
"et" = "rhineland-palatinate"
"en" = "rhineland-palatinate"
"es" = "renania-palatinado"
"fr" = "rhénanie-palatinat"
"oc" = "rhineland-palatinate"
"lb" = "rhineland-palatinate"
"ga" = "rhineland-palatinate"
"hr" = "rhineland-palatinate"
"it" = "rhineland-palatinate"
"lt" = "rhineland-palatinate"
"lv" = "rhineland-palatinate"
"nl" = "rhineland-palatinate"
"hu" = "rhineland-palatinate"
"no" = "rhineland-palatinate"
"pl" = "rhineland-palatinate"
"pt-PT" = "rhineland-palatinate"
"ro" = "rhineland-palatinate"
"sk" = "rhineland-palatinate"
"sl" = "rhineland-palatinate"
"sr" = "rhineland-palatinate"
"fi" = "rhineland-palatinate"
"sv" = "rhineland-palatinate"
"ru" = "rhineland-palatinate"
"uk" = "rhineland-palatinate"
"el" = "rhineland-palatinate"
"zh-CN" = "rhineland-palatinate"
"zh-TW" = "rhineland-palatinate"
"ja" = "rhineland-palatinate"
"ko" = "rhineland-palatinate"
"bg" = "rhineland-palatinate"
"cs" = "rhineland-palatinate"
"mt" = "rhineland-palatinate"

[region.codes]
iso_3166_2 = "DE-RP"

[[region]]
id = "DE-SL"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Saarland"
"en" = "Saarland"
"es" = "Sarre"
"fr" = "Sarre"

[region.slugs]
"ca" = "saarland"
"da" = "saarland"
"de" = "saarland"
"et" = "saarland"
"en" = "saarland"
"es" = "sarre"
"fr" = "sarre"
"oc" = "saarland"
"lb" = "saarland"
"ga" = "saarland"
"hr" = "saarland"
"it" = "saarland"
"lt" = "saarland"
"lv" = "saarland"
"nl" = "saarland"
"hu" = "saarland"
"no" = "saarland"
"pl" = "saarland"
"pt-PT" = "saarland"
"ro" = "saarland"
"sk" = "saarland"
"sl" = "saarland"
"sr" = "saarland"
"fi" = "saarland"
"sv" = "saarland"
"ru" = "saarland"
"uk" = "saarland"
"el" = "saarland"
"zh-CN" = "saarland"
"zh-TW" = "saarland"
"ja" = "saarland"
"ko" = "saarland"
"bg" = "saarland"
"cs" = "saarland"
"mt" = "saarland"

[region.codes]
iso_3166_2 = "DE-SL"

[[region]]
id = "DE-SN"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Sachsen"
"en" = "Saxony"
"es" = "Sajonia"
"fr" = "Saxe"

[region.slugs]
"ca" = "saxony"
"da" = "saxony"
"de" = "sachsen"
"et" = "saxony"
"en" = "saxony"
"es" = "sajonia"
"fr" = "saxe"
"oc" = "saxony"
"lb" = "saxony"
"ga" = "saxony"
"hr" = "saxony"
"it" = "saxony"
"lt" = "saxony"
"lv" = "saxony"
"nl" = "saxony"
"hu" = "saxony"
"no" = "saxony"
"pl" = "saxony"
"pt-PT" = "saxony"
"ro" = "saxony"
"sk" = "saxony"
"sl" = "saxony"
"sr" = "saxony"
"fi" = "saxony"
"sv" = "saxony"
"ru" = "saxony"
"uk" = "saxony"
"el" = "saxony"
"zh-CN" = "saxony"
"zh-TW" = "saxony"
"ja" = "saxony"
"ko" = "saxony"
"bg" = "saxony"
"cs" = "saxony"
"mt" = "saxony"

[region.codes]
iso_3166_2 = "DE-SN"

[[region]]
id = "DE-ST"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Sachsen-Anhalt"
"en" = "Saxony-Anhalt"
"es" = "Sajonia-Anhalt"
"fr" = "Saxe-Anhalt"

[region.slugs]
"ca" = "saxony-anhalt"
"da" = "saxony-anhalt"
"de" = "sachsen-anhalt"
"et" = "saxony-anhalt"
"en" = "saxony-anhalt"
"es" = "sajonia-anhalt"
"fr" = "saxe-anhalt"
"oc" = "saxony-anhalt"
"lb" = "saxony-anhalt"
"ga" = "saxony-anhalt"
"hr" = "saxony-anhalt"
"it" = "saxony-anhalt"
"lt" = "saxony-anhalt"
"lv" = "saxony-anhalt"
"nl" = "saxony-anhalt"
"hu" = "saxony-anhalt"
"no" = "saxony-anhalt"
"pl" = "saxony-anhalt"
"pt-PT" = "saxony-anhalt"
"ro" = "saxony-anhalt"
"sk" = "saxony-anhalt"
"sl" = "saxony-anhalt"
"sr" = "saxony-anhalt"
"fi" = "saxony-anhalt"
"sv" = "saxony-anhalt"
"ru" = "saxony-anhalt"
"uk" = "saxony-anhalt"
"el" = "saxony-anhalt"
"zh-CN" = "saxony-anhalt"
"zh-TW" = "saxony-anhalt"
"ja" = "saxony-anhalt"
"ko" = "saxony-anhalt"
"bg" = "saxony-anhalt"
"cs" = "saxony-anhalt"
"mt" = "saxony-anhalt"

[region.codes]
iso_3166_2 = "DE-ST"

[[region]]
id = "DE-SH"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Schleswig-Holstein"
"en" = "Schleswig-Holstein"
"es" = "Schleswig-Holstein"
"fr" = "Schleswig-Holstein"

[region.slugs]
"ca" = "schleswig-holstein"
"da" = "schleswig-holstein"
"de" = "schleswig-holstein"
"et" = "schleswig-holstein"
"en" = "schleswig-holstein"
"es" = "schleswig-holstein"
"fr" = "schleswig-holstein"
"oc" = "schleswig-holstein"
"lb" = "schleswig-holstein"
"ga" = "schleswig-holstein"
"hr" = "schleswig-holstein"
"it" = "schleswig-holstein"
"lt" = "schleswig-holstein"
"lv" = "schleswig-holstein"
"nl" = "schleswig-holstein"
"hu" = "schleswig-holstein"
"no" = "schleswig-holstein"
"pl" = "schleswig-holstein"
"pt-PT" = "schleswig-holstein"
"ro" = "schleswig-holstein"
"sk" = "schleswig-holstein"
"sl" = "schleswig-holstein"
"sr" = "schleswig-holstein"
"fi" = "schleswig-holstein"
"sv" = "schleswig-holstein"
"ru" = "schleswig-holstein"
"uk" = "schleswig-holstein"
"el" = "schleswig-holstein"
"zh-CN" = "schleswig-holstein"
"zh-TW" = "schleswig-holstein"
"ja" = "schleswig-holstein"
"ko" = "schleswig-holstein"
"bg" = "schleswig-holstein"
"cs" = "schleswig-holstein"
"mt" = "schleswig-holstein"

[region.codes]
iso_3166_2 = "DE-SH"

[[region]]
id = "DE-TH"
kind = "state"
official_languages = ["de"]

[region.names]
"de" = "Thüringen"
"en" = "Thuringia"
"es" = "Turingia"
"fr" = "Thuringe"

[region.slugs]
"ca" = "thuringia"
"da" = "thuringia"
"de" = "thüringen"
"et" = "thuringia"
"en" = "thuringia"
"es" = "turingia"
"fr" = "thuringe"
"oc" = "thuringia"
"lb" = "thuringia"
"ga" = "thuringia"
"hr" = "thuringia"
"it" = "thuringia"
"lt" = "thuringia"
"lv" = "thuringia"
"nl" = "thuringia"
"hu" = "thuringia"
"no" = "thuringia"
"pl" = "thuringia"
"pt-PT" = "thuringia"
"ro" = "thuringia"
"sk" = "thuringia"
"sl" = "thuringia"
"sr" = "thuringia"
"fi" = "thuringia"
"sv" = "thuringia"
"ru" = "thuringia"
"uk" = "thuringia"
"el" = "thuringia"
"zh-CN" = "thuringia"
"zh-TW" = "thuringia"
"ja" = "thuringia"
"ko" = "thuringia"
"bg" = "thuringia"
"cs" = "thuringia"
"mt" = "thuringia"

[region.codes]
iso_3166_2 = "DE-TH"
