schema_version = 1
parent = "FR"

[[region]]
id = "FR-ARA"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Auvergne-Rhône-Alpes"
"es" = "Auvergne-Rhône-Alpes"
"fr" = "Auvergne-Rhône-Alpes"

[region.slugs]
"ca" = "auvergne-rhône-alpes"
"da" = "auvergne-rhône-alpes"
"de" = "auvergne-rhône-alpes"
"et" = "auvergne-rhône-alpes"
"en" = "auvergne-rhône-alpes"
"es" = "auvergne-rhône-alpes"
"fr" = "auvergne-rhône-alpes"
"oc" = "auvergne-rhône-alpes"
"lb" = "auvergne-rhône-alpes"
"ga" = "auvergne-rhône-alpes"
"hr" = "auvergne-rhône-alpes"
"it" = "auvergne-rhône-alpes"
"lt" = "auvergne-rhône-alpes"
"lv" = "auvergne-rhône-alpes"
"nl" = "auvergne-rhône-alpes"
"hu" = "auvergne-rhône-alpes"
"no" = "auvergne-rhône-alpes"
"pl" = "auvergne-rhône-alpes"
"pt-PT" = "auvergne-rhône-alpes"
"ro" = "auvergne-rhône-alpes"
"sk" = "auvergne-rhône-alpes"
"sl" = "auvergne-rhône-alpes"
"sr" = "auvergne-rhône-alpes"
"fi" = "auvergne-rhône-alpes"
"sv" = "auvergne-rhône-alpes"
"ru" = "auvergne-rhône-alpes"
"uk" = "auvergne-rhône-alpes"
"el" = "auvergne-rhône-alpes"
"zh-CN" = "auvergne-rhône-alpes"
"zh-TW" = "auvergne-rhône-alpes"
"ja" = "auvergne-rhône-alpes"
"ko" = "auvergne-rhône-alpes"
"bg" = "auvergne-rhône-alpes"
"cs" = "auvergne-rhône-alpes"
"mt" = "auvergne-rhône-alpes"

[region.codes]
iso_3166_2 = "FR-ARA"

[[region]]
id = "FR-BFC"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Bourgogne-Franche-Comté"
"es" = "Bourgogne-Franche-Comté"
"fr" = "Bourgogne-Franche-Comté"

[region.slugs]
"ca" = "bourgogne-franche-comté"
"da" = "bourgogne-franche-comté"
"de" = "bourgogne-franche-comté"
"et" = "bourgogne-franche-comté"
"en" = "bourgogne-franche-comté"
"es" = "bourgogne-franche-comté"
"fr" = "bourgogne-franche-comté"
"oc" = "bourgogne-franche-comté"
"lb" = "bourgogne-franche-comté"
"ga" = "bourgogne-franche-comté"
"hr" = "bourgogne-franche-comté"
"it" = "bourgogne-franche-comté"
"lt" = "bourgogne-franche-comté"
"lv" = "bourgogne-franche-comté"
"nl" = "bourgogne-franche-comté"
"hu" = "bourgogne-franche-comté"
"no" = "bourgogne-franche-comté"
"pl" = "bourgogne-franche-comté"
"pt-PT" = "bourgogne-franche-comté"
"ro" = "bourgogne-franche-comté"
"sk" = "bourgogne-franche-comté"
"sl" = "bourgogne-franche-comté"
"sr" = "bourgogne-franche-comté"
"fi" = "bourgogne-franche-comté"
"sv" = "bourgogne-franche-comté"
"ru" = "bourgogne-franche-comté"
"uk" = "bourgogne-franche-comté"
"el" = "bourgogne-franche-comté"
"zh-CN" = "bourgogne-franche-comté"
"zh-TW" = "bourgogne-franche-comté"
"ja" = "bourgogne-franche-comté"
"ko" = "bourgogne-franche-comté"
"bg" = "bourgogne-franche-comté"
"cs" = "bourgogne-franche-comté"
"mt" = "bourgogne-franche-comté"

[region.codes]
iso_3166_2 = "FR-BFC"

[[region]]
id = "FR-BRE"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Bretagne"
"en" = "Brittany"
"es" = "Bretaña"
"fr" = "Bretagne"

[region.slugs]
"ca" = "brittany"
"da" = "brittany"
"de" = "bretagne"
"et" = "brittany"
"en" = "brittany"
"es" = "bretaña"
"fr" = "bretagne"
"oc" = "brittany"
"lb" = "brittany"
"ga" = "brittany"
"hr" = "brittany"
"it" = "brittany"
"lt" = "brittany"
"lv" = "brittany"
"nl" = "brittany"
"hu" = "brittany"
"no" = "brittany"
"pl" = "brittany"
"pt-PT" = "brittany"
"ro" = "brittany"
"sk" = "brittany"
"sl" = "brittany"
"sr" = "brittany"
"fi" = "brittany"
"sv" = "brittany"
"ru" = "brittany"
"uk" = "brittany"
"el" = "brittany"
"zh-CN" = "brittany"
"zh-TW" = "brittany"
"ja" = "brittany"
"ko" = "brittany"
"bg" = "brittany"
"cs" = "brittany"
"mt" = "brittany"

[region.codes]
iso_3166_2 = "FR-BRE"

[[region]]
id = "FR-CVL"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Centre-Val de Loire"
"es" = "Centro-Valle del Loira"
"fr" = "Centre-Val de Loire"

[region.slugs]
"ca" = "centre-val-de-loire"
"da" = "centre-val-de-loire"
"de" = "centre-val-de-loire"
"et" = "centre-val-de-loire"
"en" = "centre-val-de-loire"
"es" = "centro-valle-del-loira"
"fr" = "centre-val-de-loire"
"oc" = "centre-val-de-loire"
"lb" = "centre-val-de-loire"
"ga" = "centre-val-de-loire"
"hr" = "centre-val-de-loire"
"it" = "centre-val-de-loire"
"lt" = "centre-val-de-loire"
"lv" = "centre-val-de-loire"
"nl" = "centre-val-de-loire"
"hu" = "centre-val-de-loire"
"no" = "centre-val-de-loire"
"pl" = "centre-val-de-loire"
"pt-PT" = "centre-val-de-loire"
"ro" = "centre-val-de-loire"
"sk" = "centre-val-de-loire"
"sl" = "centre-val-de-loire"
"sr" = "centre-val-de-loire"
"fi" = "centre-val-de-loire"
"sv" = "centre-val-de-loire"
"ru" = "centre-val-de-loire"
"uk" = "centre-val-de-loire"
"el" = "centre-val-de-loire"
"zh-CN" = "centre-val-de-loire"
"zh-TW" = "centre-val-de-loire"
"ja" = "centre-val-de-loire"
"ko" = "centre-val-de-loire"
"bg" = "centre-val-de-loire"
"cs" = "centre-val-de-loire"
"mt" = "centre-val-de-loire"

[region.codes]
iso_3166_2 = "FR-CVL"

[[region]]
id = "FR-20R"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Korsika"
"en" = "Corsica"
"es" = "Córcega"
"fr" = "Corse"

[region.slugs]
"ca" = "corsica"
"da" = "corsica"
"de" = "korsika"
"et" = "corsica"
"en" = "corsica"
"es" = "córcega"
"fr" = "corse"
"oc" = "corsica"
"lb" = "corsica"
"ga" = "corsica"
"hr" = "corsica"
"it" = "corsica"
"lt" = "corsica"
"lv" = "corsica"
"nl" = "corsica"
"hu" = "corsica"
"no" = "corsica"
"pl" = "corsica"
"pt-PT" = "corsica"
"ro" = "corsica"
"sk" = "corsica"
"sl" = "corsica"
"sr" = "corsica"
"fi" = "corsica"
"sv" = "corsica"
"ru" = "corsica"
"uk" = "corsica"
"el" = "corsica"
"zh-CN" = "corsica"
"zh-TW" = "corsica"
"ja" = "corsica"
"ko" = "corsica"
"bg" = "corsica"
"cs" = "corsica"
"mt" = "corsica"

[region.codes]
iso_3166_2 = "FR-20R"

[[region]]
id = "FR-GES"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Grand Est"
"es" = "Gran Este"
"fr" = "Grand Est"

[region.slugs]
"ca" = "grand-est"
"da" = "grand-est"
"de" = "grand-est"
"et" = "grand-est"
"en" = "grand-est"
"es" = "gran-este"
"fr" = "grand-est"
"oc" = "grand-est"
"lb" = "grand-est"
"ga" = "grand-est"
"hr" = "grand-est"
"it" = "grand-est"
"lt" = "grand-est"
"lv" = "grand-est"
"nl" = "grand-est"
"hu" = "grand-est"
"no" = "grand-est"
"pl" = "grand-est"
"pt-PT" = "grand-est"
"ro" = "grand-est"
"sk" = "grand-est"
"sl" = "grand-est"
"sr" = "grand-est"
"fi" = "grand-est"
"sv" = "grand-est"
"ru" = "grand-est"
"uk" = "grand-est"
"el" = "grand-est"
"zh-CN" = "grand-est"
"zh-TW" = "grand-est"
"ja" = "grand-est"
"ko" = "grand-est"
"bg" = "grand-est"
"cs" = "grand-est"
"mt" = "grand-est"

[region.codes]
iso_3166_2 = "FR-GES"

[[region]]
id = "FR-HDF"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Hauts-de-France"
"es" = "Alta Francia"
"fr" = "Hauts-de-France"

[region.slugs]
"ca" = "hauts-de-france"
"da" = "hauts-de-france"
"de" = "hauts-de-france"
"et" = "hauts-de-france"
"en" = "hauts-de-france"
"es" = "alta-francia"
"fr" = "hauts-de-france"
"oc" = "hauts-de-france"
"lb" = "hauts-de-france"
"ga" = "hauts-de-france"
"hr" = "hauts-de-france"
"it" = "hauts-de-france"
"lt" = "hauts-de-france"
"lv" = "hauts-de-france"
"nl" = "hauts-de-france"
"hu" = "hauts-de-france"
"no" = "hauts-de-france"
"pl" = "hauts-de-france"
"pt-PT" = "hauts-de-france"
"ro" = "hauts-de-france"
"sk" = "hauts-de-france"
"sl" = "hauts-de-france"
"sr" = "hauts-de-france"
"fi" = "hauts-de-france"
"sv" = "hauts-de-france"
"ru" = "hauts-de-france"
"uk" = "hauts-de-france"
"el" = "hauts-de-france"
"zh-CN" = "hauts-de-france"
"zh-TW" = "hauts-de-france"
"ja" = "hauts-de-france"
"ko" = "hauts-de-france"
"bg" = "hauts-de-france"
"cs" = "hauts-de-france"
"mt" = "hauts-de-france"

[region.codes]
iso_3166_2 = "FR-HDF"

[[region]]
id = "FR-IDF"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Île-de-France"
"es" = "Isla de Francia"
"fr" = "Île-de-France"

[region.slugs]
"ca" = "île-de-france"
"da" = "île-de-france"
"de" = "île-de-france"
"et" = "île-de-france"
"en" = "île-de-france"
"es" = "isla-de-francia"
"fr" = "île-de-france"
"oc" = "île-de-france"
"lb" = "île-de-france"
"ga" = "île-de-france"
"hr" = "île-de-france"
"it" = "île-de-france"
"lt" = "île-de-france"
"lv" = "île-de-france"
"nl" = "île-de-france"
"hu" = "île-de-france"
"no" = "île-de-france"
"pl" = "île-de-france"
"pt-PT" = "île-de-france"
"ro" = "île-de-france"
"sk" = "île-de-france"
"sl" = "île-de-france"
"sr" = "île-de-france"
"fi" = "île-de-france"
"sv" = "île-de-france"
"ru" = "île-de-france"
"uk" = "île-de-france"
"el" = "île-de-france"
"zh-CN" = "île-de-france"
"zh-TW" = "île-de-france"
"ja" = "île-de-france"
"ko" = "île-de-france"
"bg" = "île-de-france"
"cs" = "île-de-france"
"mt" = "île-de-france"

[region.codes]
iso_3166_2 = "FR-IDF"

[[region]]
id = "FR-NOR"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Normandie"
"en" = "Normandy"
"es" = "Normandía"
"fr" = "Normandie"

[region.slugs]
"ca" = "normandy"
"da" = "normandy"
"de" = "normandie"
"et" = "normandy"
"en" = "normandy"
"es" = "normandía"
"fr" = "normandie"
"oc" = "normandy"
"lb" = "normandy"
"ga" = "normandy"
"hr" = "normandy"
"it" = "normandy"
"lt" = "normandy"
"lv" = "normandy"
"nl" = "normandy"
"hu" = "normandy"
"no" = "normandy"
"pl" = "normandy"
"pt-PT" = "normandy"
"ro" = "normandy"
"sk" = "normandy"
"sl" = "normandy"
"sr" = "normandy"
"fi" = "normandy"
"sv" = "normandy"
"ru" = "normandy"
"uk" = "normandy"
"el" = "normandy"
"zh-CN" = "normandy"
"zh-TW" = "normandy"
"ja" = "normandy"
"ko" = "normandy"
"bg" = "normandy"
"cs" = "normandy"
"mt" = "normandy"

[region.codes]
iso_3166_2 = "FR-NOR"

[[region]]
id = "FR-NAQ"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Neu-Aquitanien"
"en" = "New Aquitaine"
"es" = "Nueva Aquitania"
"fr" = "Nouvelle-Aquitaine"

[region.slugs]
"ca" = "new-aquitaine"
"da" = "new-aquitaine"
"de" = "neu-aquitanien"
"et" = "new-aquitaine"
"en" = "new-aquitaine"
"es" = "nueva-aquitania"
"fr" = "nouvelle-aquitaine"
"oc" = "new-aquitaine"
"lb" = "new-aquitaine"
"ga" = "new-aquitaine"
"hr" = "new-aquitaine"
"it" = "new-aquitaine"
"lt" = "new-aquitaine"
"lv" = "new-aquitaine"
"nl" = "new-aquitaine"
"hu" = "new-aquitaine"
"no" = "new-aquitaine"
"pl" = "new-aquitaine"
"pt-PT" = "new-aquitaine"
"ro" = "new-aquitaine"
"sk" = "new-aquitaine"
"sl" = "new-aquitaine"
"sr" = "new-aquitaine"
"fi" = "new-aquitaine"
"sv" = "new-aquitaine"
"ru" = "new-aquitaine"
"uk" = "new-aquitaine"
"el" = "new-aquitaine"
"zh-CN" = "new-aquitaine"
"zh-TW" = "new-aquitaine"
"ja" = "new-aquitaine"
"ko" = "new-aquitaine"
"bg" = "new-aquitaine"
"cs" = "new-aquitaine"
"mt" = "new-aquitaine"

[region.codes]
iso_3166_2 = "FR-NAQ"

[[region]]
id = "FR-OCC"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Okzitanien"
"en" = "Occitania"
"es" = "Occitania"
"fr" = "Occitanie"

[region.slugs]
"ca" = "occitania"
"da" = "occitania"
"de" = "okzitanien"
"et" = "occitania"
"en" = "occitania"
"es" = "occitania"
"fr" = "occitanie"
"oc" = "occitania"
"lb" = "occitania"
"ga" = "occitania"
"hr" = "occitania"
"it" = "occitania"
"lt" = "occitania"
"lv" = "occitania"
"nl" = "occitania"
"hu" = "occitania"
"no" = "occitania"
"pl" = "occitania"
"pt-PT" = "occitania"
"ro" = "occitania"
"sk" = "occitania"
"sl" = "occitania"
"sr" = "occitania"
"fi" = "occitania"
"sv" = "occitania"
"ru" = "occitania"
"uk" = "occitania"
"el" = "occitania"
"zh-CN" = "occitania"
"zh-TW" = "occitania"
"ja" = "occitania"
"ko" = "occitania"
"bg" = "occitania"
"cs" = "occitania"
"mt" = "occitania"

[region.codes]
iso_3166_2 = "FR-OCC"

[[region]]
id = "FR-PDL"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Pays de la Loire"
"es" = "Países del Loira"
"fr" = "Pays de la Loire"

[region.slugs]
"ca" = "pays-de-la-loire"
"da" = "pays-de-la-loire"
"de" = "pays-de-la-loire"
"et" = "pays-de-la-loire"
"en" = "pays-de-la-loire"
"es" = "países-del-loira"
"fr" = "pays-de-la-loire"
"oc" = "pays-de-la-loire"
"lb" = "pays-de-la-loire"
"ga" = "pays-de-la-loire"
"hr" = "pays-de-la-loire"
"it" = "pays-de-la-loire"
"lt" = "pays-de-la-loire"
"lv" = "pays-de-la-loire"
"nl" = "pays-de-la-loire"
"hu" = "pays-de-la-loire"
"no" = "pays-de-la-loire"
"pl" = "pays-de-la-loire"
"pt-PT" = "pays-de-la-loire"
"ro" = "pays-de-la-loire"
"sk" = "pays-de-la-loire"
"sl" = "pays-de-la-loire"
"sr" = "pays-de-la-loire"
"fi" = "pays-de-la-loire"
"sv" = "pays-de-la-loire"
"ru" = "pays-de-la-loire"
"uk" = "pays-de-la-loire"
"el" = "pays-de-la-loire"
"zh-CN" = "pays-de-la-loire"
"zh-TW" = "pays-de-la-loire"
"ja" = "pays-de-la-loire"
"ko" = "pays-de-la-loire"
"bg" = "pays-de-la-loire"
"cs" = "pays-de-la-loire"
"mt" = "pays-de-la-loire"

[region.codes]
iso_3166_2 = "FR-PDL"

[[region]]
id = "FR-PAC"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Provence-Alpes-Côte d’Azur"
"es" = "Provenza-Alpes-Costa Azul"
"fr" = "Provence-Alpes-Côte d’Azur"

[region.slugs]
"ca" = "provence-alpes-côte-d-azur"
"da" = "provence-alpes-côte-d-azur"
"de" = "provence-alpes-côte-d-azur"
"et" = "provence-alpes-côte-d-azur"
"en" = "provence-alpes-côte-d-azur"
"es" = "provenza-alpes-costa-azul"
"fr" = "provence-alpes-côte-d-azur"
"oc" = "provence-alpes-côte-d-azur"
"lb" = "provence-alpes-côte-d-azur"
"ga" = "provence-alpes-côte-d-azur"
"hr" = "provence-alpes-côte-d-azur"
"it" = "provence-alpes-côte-d-azur"
"lt" = "provence-alpes-côte-d-azur"
"lv" = "provence-alpes-côte-d-azur"
"nl" = "provence-alpes-côte-d-azur"
"hu" = "provence-alpes-côte-d-azur"
"no" = "provence-alpes-côte-d-azur"
"pl" = "provence-alpes-côte-d-azur"
"pt-PT" = "provence-alpes-côte-d-azur"
"ro" = "provence-alpes-côte-d-azur"
"sk" = "provence-alpes-côte-d-azur"
"sl" = "provence-alpes-côte-d-azur"
"sr" = "provence-alpes-côte-d-azur"
"fi" = "provence-alpes-côte-d-azur"
"sv" = "provence-alpes-côte-d-azur"
"ru" = "provence-alpes-côte-d-azur"
"uk" = "provence-alpes-côte-d-azur"
"el" = "provence-alpes-côte-d-azur"
"zh-CN" = "provence-alpes-côte-d-azur"
"zh-TW" = "provence-alpes-côte-d-azur"
"ja" = "provence-alpes-côte-d-azur"
"ko" = "provence-alpes-côte-d-azur"
"bg" = "provence-alpes-côte-d-azur"
"cs" = "provence-alpes-côte-d-azur"
"mt" = "provence-alpes-côte-d-azur"

[region.codes]
iso_3166_2 = "FR-PAC"

[[region]]
id = "FR-GP"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Guadeloupe"
"es" = "Guadalupe"
"fr" = "Guadeloupe"

[region.slugs]
"ca" = "guadeloupe"
"da" = "guadeloupe"
"de" = "guadeloupe"
"et" = "guadeloupe"
"en" = "guadeloupe"
"es" = "guadalupe"
"fr" = "guadeloupe"
"oc" = "guadeloupe"
"lb" = "guadeloupe"
"ga" = "guadeloupe"
"hr" = "guadeloupe"
"it" = "guadeloupe"
"lt" = "guadeloupe"
"lv" = "guadeloupe"
"nl" = "guadeloupe"
"hu" = "guadeloupe"
"no" = "guadeloupe"
"pl" = "guadeloupe"
"pt-PT" = "guadeloupe"
"ro" = "guadeloupe"
"sk" = "guadeloupe"
"sl" = "guadeloupe"
"sr" = "guadeloupe"
"fi" = "guadeloupe"
"sv" = "guadeloupe"
"ru" = "guadeloupe"
"uk" = "guadeloupe"
"el" = "guadeloupe"
"zh-CN" = "guadeloupe"
"zh-TW" = "guadeloupe"
"ja" = "guadeloupe"
"ko" = "guadeloupe"
"bg" = "guadeloupe"
"cs" = "guadeloupe"
"mt" = "guadeloupe"

[region.codes]
iso_3166_2 = "FR-GP"

[[region]]
id = "FR-GF"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Französisch-Guayana"
"en" = "French Guiana"
"es" = "Guayana Francesa"
"fr" = "Guyane"

[region.slugs]
"ca" = "french-guiana"
"da" = "french-guiana"
"de" = "französisch-guayana"
"et" = "french-guiana"
"en" = "french-guiana"
"es" = "guayana-francesa"
"fr" = "guyane"
"oc" = "french-guiana"
"lb" = "french-guiana"
"ga" = "french-guiana"
"hr" = "french-guiana"
"it" = "french-guiana"
"lt" = "french-guiana"
"lv" = "french-guiana"
"nl" = "french-guiana"
"hu" = "french-guiana"
"no" = "french-guiana"
"pl" = "french-guiana"
"pt-PT" = "french-guiana"
"ro" = "french-guiana"
"sk" = "french-guiana"
"sl" = "french-guiana"
"sr" = "french-guiana"
"fi" = "french-guiana"
"sv" = "french-guiana"
"ru" = "french-guiana"
"uk" = "french-guiana"
"el" = "french-guiana"
"zh-CN" = "french-guiana"
"zh-TW" = "french-guiana"
"ja" = "french-guiana"
"ko" = "french-guiana"
"bg" = "french-guiana"
"cs" = "french-guiana"
"mt" = "french-guiana"

[region.codes]
iso_3166_2 = "FR-GF"

[[region]]
id = "FR-MQ"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Martinique"
"es" = "Martinica"
"fr" = "Martinique"

[region.slugs]
"ca" = "martinique"
"da" = "martinique"
"de" = "martinique"
"et" = "martinique"
"en" = "martinique"
"es" = "martinica"
"fr" = "martinique"
"oc" = "martinique"
"lb" = "martinique"
"ga" = "martinique"
"hr" = "martinique"
"it" = "martinique"
"lt" = "martinique"
"lv" = "martinique"
"nl" = "martinique"
"hu" = "martinique"
"no" = "martinique"
"pl" = "martinique"
"pt-PT" = "martinique"
"ro" = "martinique"
"sk" = "martinique"
"sl" = "martinique"
"sr" = "martinique"
"fi" = "martinique"
"sv" = "martinique"
"ru" = "martinique"
"uk" = "martinique"
"el" = "martinique"
"zh-CN" = "martinique"
"zh-TW" = "martinique"
"ja" = "martinique"
"ko" = "martinique"
"bg" = "martinique"
"cs" = "martinique"
"mt" = "martinique"

[region.codes]
iso_3166_2 = "FR-MQ"

[[region]]
id = "FR-RE"
kind = "region"
official_languages = ["fr"]

[region.names]
"de" = "Réunion"
"en" = "Réunion"
"es" = "Reunión"
"fr" = "La Réunion"

[region.slugs]
"ca" = "réunion"
"da" = "réunion"
"de" = "réunion"
"et" = "réunion"
"en" = "réunion"
"es" = "reunión"
"fr" = "la-réunion"
"oc" = "réunion"
"lb" = "réunion"
"ga" = "réunion"
"hr" = "réunion"
"it" = "réunion"
"lt" = "réunion"
"lv" = "réunion"
"nl" = "réunion"
"hu" = "réunion"
"no" = "réunion"
"pl" = "réunion"
"pt-PT" = "réunion"
"ro" = "réunion"
"sk" = "réunion"
"sl" = "réunion"
"sr" = "réunion"
"fi" = "réunion"
"sv" = "réunion"
"ru" = "réunion"
"uk" = "réunion"
"el" = "réunion"
"zh-CN" = "réunion"
"zh-TW" = "réunion"
"ja" = "réunion"
"ko" = "réunion"
"bg" = "réunion"
"cs" = "réunion"
"mt" = "réunion"

[region.codes]
iso_3166_2 = "FR-RE"

[[region]]
id = "FR-YT"
kind = "region"
official_languages = ["fr"]

[region.names]
"en" = "Mayotte"
"es" = "Mayotte"
"fr" = "Mayotte"

[region.slugs]
"ca" = "mayotte"
"da" = "mayotte"
"de" = "mayotte"
"et" = "mayotte"
"en" = "mayotte"
"es" = "mayotte"
"fr" = "mayotte"
"oc" = "mayotte"
"lb" = "mayotte"
"ga" = "mayotte"
"hr" = "mayotte"
"it" = "mayotte"
"lt" = "mayotte"
"lv" = "mayotte"
"nl" = "mayotte"
"hu" = "mayotte"
"no" = "mayotte"
"pl" = "mayotte"
"pt-PT" = "mayotte"
"ro" = "mayotte"
"sk" = "mayotte"
"sl" = "mayotte"
"sr" = "mayotte"
"fi" = "mayotte"
"sv" = "mayotte"
"ru" = "mayotte"
"uk" = "mayotte"
"el" = "mayotte"
"zh-CN" = "mayotte"
"zh-TW" = "mayotte"
"ja" = "mayotte"
"ko" = "mayotte"
"bg" = "mayotte"
"cs" = "mayotte"
"mt" = "mayotte"

[region.codes]
iso_3166_2 = "FR-YT"
