[maple]
transitland = "/home/catenary/transitland-atlas/"
use_girolle = true
no_elastic = false
delete_before_ingest = false
only_feed_ids = []
gtfs_zip_temp = "/mnt/sdb1/temp-compressed-maple/"
gtfs_uncompressed_temp = "/mnt/sdb1/temp-uncompressed/"
threads_gtfs = 12
force_ingest_all = false
bypass_temp_delete = false
discord_log = "https://canary.discord.com/api/webhooks/1412343522031439872/YZSsSat_l8I4B15VWvNaSz3S-Kb3LmTXseL3PvRmao4ER9ev3BdQZgK4EYiR0ZJ-soid"

[maple.transitland_download]
download_threads = 64
croatia_npt_username = "kyler@catenarymaps.org"
croatia_npt_password = "Eey8uudUeEmSjkR"
grand_lyon_username = "kyler@catenarymaps.org"
grand_lyon_password = "l3bxZRuOupu2Ns"
de_username = ""
de_password = ""

[aspen]
etcd_urls = ["localhost:2379"]
channels = 4
alpenrose_thread_count = 4
port = 40427
etcd_username = ""
etcd_password = ""

[aspenleader]
etcd_urls = ["localhost:2379"]
etcd_username = ""
etcd_password = ""

[alpenrose]
request_limit = 40
etcd_urls = ["localhost:2379"]
etcd_username = ""
etcd_password = ""

[birch]
worker_amount = 4
etcd_urls = ["localhost:2379"]
etcd_username = ""
etcd_password = ""

[elasticsearch]
elasticsearch_url = "http://localhost:9200"

[postgres]
database_url = "postgresql://postgres:n84qmh7BOr@localhost/postgres"
max_connections = 128