# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
schema = "gtfs"
custom_type_derives = ["diesel::query_builder::QueryId"]
import_types = ["postgis_diesel::sql_types::*","diesel::sql_types::*","crate::custom_pg_types::*"]
generate_missing_sql_type_definitions = false

[migrations_directory]
dir = "migrations"