# For local development

version: '3'
services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: catenary
      POSTGRES_PASSWORD: catenary
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql@16/data

volumes:
  db-data:
