schema_version = 1

[[country]]
id = "AD"
kind = "country"
official_languages = ["ca"]

[country.names]
"ca" = "Andorra"
"da" = "Andorra"
"de" = "Andorra"
"et" = "Andorra"
"en" = "Andorra"
"es" = "Andorra"
"fr" = "Andorre"
"oc" = "Andòrra"
"lb" = "Andorra"
"ga" = "Andóra"
"hr" = "Andora"
"it" = "Andorra"
"lt" = "Andora"
"lv" = "Andora"
"nl" = "Andorra"
"hu" = "Andorra"
"no" = "Andorra"
"pl" = "Andora"
"pt-PT" = "Andorra"
"ro" = "Andorra"
"sk" = "Andorra"
"sl" = "Andora"
"sr" = "Андора"
"fi" = "Andorra"
"sv" = "Andorra"
"ru" = "Андорра"
"uk" = "Андорра"
"el" = "Ανδόρα"
"zh-CN" = "安道尔"
"zh-TW" = "安道爾"
"ja" = "アンドラ"
"ko" = "안도라"
"bg" = "Андора"
"cs" = "Andorra"
"mt" = "Andorra"

[country.slugs]
"ca" = "andorra"
"da" = "andorra"
"de" = "andorra"
"et" = "andorra"
"en" = "andorra"
"es" = "andorra"
"fr" = "andorre"
"oc" = "andòrra"
"lb" = "andorra"
"ga" = "andóra"
"hr" = "andora"
"it" = "andorra"
"lt" = "andora"
"lv" = "andora"
"nl" = "andorra"
"hu" = "andorra"
"no" = "andorra"
"pl" = "andora"
"pt-PT" = "andorra"
"ro" = "andorra"
"sk" = "andorra"
"sl" = "andora"
"sr" = "андора"
"fi" = "andorra"
"sv" = "andorra"
"ru" = "андорра"
"uk" = "андорра"
"el" = "ανδόρα"
"zh-CN" = "安道尔"
"zh-TW" = "安道爾"
"ja" = "アンドラ"
"ko" = "안도라"
"bg" = "андора"
"cs" = "andorra"
"mt" = "andorra"

[country.codes]
gisco_cntr_id = "AD"
iso_3166_1_alpha2 = "AD"
iso_3166_1_alpha3 = "AND"
