schema_version = 1

[[country]]
id = "AE"
kind = "country"
official_languages = ["ar"]

[country.names]
"ca" = "Emirats Àrabs Units"
"da" = "De Forenede Arabiske Emirater"
"de" = "Vereinigte Arabische Emirate"
"et" = "Araabia Ühendemiraadid"
"en" = "United Arab Emirates"
"es" = "Emiratos Árabes Unidos"
"fr" = "Émirats arabes unis"
"oc" = "Emirats Arabs Units"
"lb" = "Vereenegt Arabesch Emirater"
"ga" = "Aontas na nÉimíríochtaí Arabacha"
"hr" = "Ujedinjeni Arapski Emirati"
"it" = "Emirati Arabi Uniti"
"lt" = "Jungtiniai Arabų Emyratai"
"lv" = "Apvienotie Arābu Emirāti"
"nl" = "Verenigde Arabische Emiraten"
"hu" = "Egyesült Arab Emírségek"
"no" = "De forente arabiske emirater"
"pl" = "Zjednoczone Emiraty Arabskie"
"pt-PT" = "Emirados Árabes Unidos"
"ro" = "Emiratele Arabe Unite"
"sk" = "Spojené arabské emiráty"
"sl" = "Združeni arabski emirati"
"sr" = "Уједињени Арапски Емирати"
"fi" = "Arabiemiirikunnat"
"sv" = "Förenade Arabemiraten"
"ru" = "ОАЭ"
"uk" = "Обʼєднані Арабські Емірати"
"el" = "Ηνωμένα Αραβικά Εμιράτα"
"zh-CN" = "阿拉伯联合酋长国"
"zh-TW" = "阿拉伯聯合大公國"
"ja" = "アラブ首長国連邦"
"ko" = "아랍에미리트"
"bg" = "Обединени арабски емирства"
"cs" = "Spojené arabské emiráty"
"mt" = "l-Emirati Għarab Magħquda"
"ar" = "الإمارات العربية المتحدة"

[country.slugs]
"ca" = "emirats-àrabs-units"
"da" = "de-forenede-arabiske-emirater"
"de" = "vereinigte-arabische-emirate"
"et" = "araabia-ühendemiraadid"
"en" = "united-arab-emirates"
"es" = "emiratos-árabes-unidos"
"fr" = "émirats-arabes-unis"
"oc" = "emirats-arabs-units"
"lb" = "vereenegt-arabesch-emirater"
"ga" = "aontas-na-néimíríochtaí-arabacha"
"hr" = "ujedinjeni-arapski-emirati"
"it" = "emirati-arabi-uniti"
"lt" = "jungtiniai-arabų-emyratai"
"lv" = "apvienotie-arābu-emirāti"
"nl" = "verenigde-arabische-emiraten"
"hu" = "egyesült-arab-emírségek"
"no" = "de-forente-arabiske-emirater"
"pl" = "zjednoczone-emiraty-arabskie"
"pt-PT" = "emirados-árabes-unidos"
"ro" = "emiratele-arabe-unite"
"sk" = "spojené-arabské-emiráty"
"sl" = "združeni-arabski-emirati"
"sr" = "уједињени-арапски-емирати"
"fi" = "arabiemiirikunnat"
"sv" = "förenade-arabemiraten"
"ru" = "оаэ"
"uk" = "обʼєднані-арабські-емірати"
"el" = "ηνωμένα-αραβικά-εμιράτα"
"zh-CN" = "阿拉伯联合酋长国"
"zh-TW" = "阿拉伯聯合大公國"
"ja" = "アラブ首長国連邦"
"ko" = "아랍에미리트"
"bg" = "обединени-арабски-емирства"
"cs" = "spojené-arabské-emiráty"
"mt" = "l-emirati-għarab-magħquda"

[country.codes]
gisco_cntr_id = "AE"
iso_3166_1_alpha2 = "AE"
iso_3166_1_alpha3 = "ARE"
