schema_version = 1

[[country]]
id = "AR"
kind = "country"
official_languages = ["es"]

[country.names]
"ca" = "Argentina"
"da" = "Argentina"
"de" = "Argentinien"
"et" = "Argentina"
"en" = "Argentina"
"es" = "Argentina"
"fr" = "Argentine"
"oc" = "Argentina"
"lb" = "Argentinien"
"ga" = "an Airgintín"
"hr" = "Argentina"
"it" = "Argentina"
"lt" = "Argentina"
"lv" = "Argentīna"
"nl" = "Argentinië"
"hu" = "Argentína"
"no" = "Argentina"
"pl" = "Argentyna"
"pt-PT" = "Argentina"
"ro" = "Argentina"
"sk" = "Argentína"
"sl" = "Argentina"
"sr" = "Аргентина"
"fi" = "Argentiina"
"sv" = "Argentina"
"ru" = "Аргентина"
"uk" = "Аргентина"
"el" = "Αργεντινή"
"zh-CN" = "阿根廷"
"zh-TW" = "阿根廷"
"ja" = "アルゼンチン"
"ko" = "아르헨티나"
"bg" = "Аржентина"
"cs" = "Argentina"
"mt" = "l-Arġentina"

[country.slugs]
"ca" = "argentina"
"da" = "argentina"
"de" = "argentinien"
"et" = "argentina"
"en" = "argentina"
"es" = "argentina"
"fr" = "argentine"
"oc" = "argentina"
"lb" = "argentinien"
"ga" = "an-airgintín"
"hr" = "argentina"
"it" = "argentina"
"lt" = "argentina"
"lv" = "argentīna"
"nl" = "argentinië"
"hu" = "argentína"
"no" = "argentina"
"pl" = "argentyna"
"pt-PT" = "argentina"
"ro" = "argentina"
"sk" = "argentína"
"sl" = "argentina"
"sr" = "аргентина"
"fi" = "argentiina"
"sv" = "argentina"
"ru" = "аргентина"
"uk" = "аргентина"
"el" = "αργεντινή"
"zh-CN" = "阿根廷"
"zh-TW" = "阿根廷"
"ja" = "アルゼンチン"
"ko" = "아르헨티나"
"bg" = "аржентина"
"cs" = "argentina"
"mt" = "l-arġentina"

[country.codes]
gisco_cntr_id = "AR"
iso_3166_1_alpha2 = "AR"
iso_3166_1_alpha3 = "ARG"
