schema_version = 1

[[country]]
id = "AT"
kind = "country"
official_languages = ["de"]

[country.names]
"ca" = "Àustria"
"da" = "Østrig"
"de" = "Österreich"
"et" = "Austria"
"en" = "Austria"
"es" = "Austria"
"fr" = "Autriche"
"oc" = "Àustria"
"lb" = "Éisträich"
"ga" = "an Ostair"
"hr" = "Austrija"
"it" = "Austria"
"lt" = "Austrija"
"lv" = "Austrija"
"nl" = "Oostenrijk"
"hu" = "Ausztria"
"no" = "Østerrike"
"pl" = "Austria"
"pt-PT" = "Áustria"
"ro" = "Austria"
"sk" = "Rakúsko"
"sl" = "Avstrija"
"sr" = "Аустрија"
"fi" = "Itävalta"
"sv" = "Österrike"
"ru" = "Австрия"
"uk" = "Австрія"
"el" = "Αυστρία"
"zh-CN" = "奥地利"
"zh-TW" = "奧地利"
"ja" = "オーストリア"
"ko" = "오스트리아"
"bg" = "Австрия"
"cs" = "Rakousko"
"mt" = "l-Awstrija"

[country.slugs]
"ca" = "àustria"
"da" = "østrig"
"de" = "österreich"
"et" = "austria"
"en" = "austria"
"es" = "austria"
"fr" = "autriche"
"oc" = "àustria"
"lb" = "éisträich"
"ga" = "an-ostair"
"hr" = "austrija"
"it" = "austria"
"lt" = "austrija"
"lv" = "austrija"
"nl" = "oostenrijk"
"hu" = "ausztria"
"no" = "østerrike"
"pl" = "austria"
"pt-PT" = "áustria"
"ro" = "austria"
"sk" = "rakúsko"
"sl" = "avstrija"
"sr" = "аустрија"
"fi" = "itävalta"
"sv" = "österrike"
"ru" = "австрия"
"uk" = "австрія"
"el" = "αυστρία"
"zh-CN" = "奥地利"
"zh-TW" = "奧地利"
"ja" = "オーストリア"
"ko" = "오스트리아"
"bg" = "австрия"
"cs" = "rakousko"
"mt" = "l-awstrija"

[country.codes]
gisco_cntr_id = "AT"
iso_3166_1_alpha2 = "AT"
iso_3166_1_alpha3 = "AUT"
