schema_version = 1

[[country]]
id = "AU"
kind = "country"
official_languages = ["en"]

[country.names]
"ca" = "Austràlia"
"da" = "Australien"
"de" = "Australien"
"et" = "Austraalia"
"en" = "Australia"
"es" = "Australia"
"fr" = "Australie"
"oc" = "Austràlia"
"lb" = "Australien"
"ga" = "an Astráil"
"hr" = "Australija"
"it" = "Australia"
"lt" = "Australija"
"lv" = "Austrālija"
"nl" = "Australië"
"hu" = "Ausztrália"
"no" = "Australia"
"pl" = "Australia"
"pt-PT" = "Austrália"
"ro" = "Australia"
"sk" = "Austrália"
"sl" = "Avstralija"
"sr" = "Аустралија"
"fi" = "Australia"
"sv" = "Australien"
"ru" = "Австралия"
"uk" = "Австралія"
"el" = "Αυστραλία"
"zh-CN" = "澳大利亚"
"zh-TW" = "澳洲"
"ja" = "オーストラリア"
"ko" = "오스트레일리아"
"bg" = "Австралия"
"cs" = "Austrálie"
"mt" = "l-Awstralja"

[country.slugs]
"ca" = "austràlia"
"da" = "australien"
"de" = "australien"
"et" = "austraalia"
"en" = "australia"
"es" = "australia"
"fr" = "australie"
"oc" = "austràlia"
"lb" = "australien"
"ga" = "an-astráil"
"hr" = "australija"
"it" = "australia"
"lt" = "australija"
"lv" = "austrālija"
"nl" = "australië"
"hu" = "ausztrália"
"no" = "australia"
"pl" = "australia"
"pt-PT" = "austrália"
"ro" = "australia"
"sk" = "austrália"
"sl" = "avstralija"
"sr" = "аустралија"
"fi" = "australia"
"sv" = "australien"
"ru" = "австралия"
"uk" = "австралія"
"el" = "αυστραλία"
"zh-CN" = "澳大利亚"
"zh-TW" = "澳洲"
"ja" = "オーストラリア"
"ko" = "오스트레일리아"
"bg" = "австралия"
"cs" = "austrálie"
"mt" = "l-awstralja"

[country.codes]
gisco_cntr_id = "AU"
iso_3166_1_alpha2 = "AU"
iso_3166_1_alpha3 = "AUS"
