schema_version = 1

[[country]]
id = "BA"
kind = "country"
official_languages = ["bs", "hr", "sr"]

[country.names]
"ca" = "Bòsnia i Hercegovina"
"da" = "Bosnien-Hercegovina"
"de" = "Bosnien und Herzegowina"
"et" = "Bosnia ja Hertsegoviina"
"en" = "Bosnia & Herzegovina"
"es" = "Bosnia y Herzegovina"
"fr" = "Bosnie-Herzégovine"
"oc" = "Bòsnia e Ercegovina"
"lb" = "Bosnien an Herzegowina"
"ga" = "an Bhoisnia agus an Heirseagaivéin"
"hr" = "Bosna i Hercegovina"
"it" = "Bosnia ed Erzegovina"
"lt" = "Bosnija ir Hercegovina"
"lv" = "Bosnija un Hercegovina"
"nl" = "Bosnië en Herzegovina"
"hu" = "Bosznia-Hercegovina"
"no" = "Bosnia-Hercegovina"
"pl" = "Bośnia i Hercegowina"
"pt-PT" = "Bósnia e Herzegovina"
"ro" = "Bosnia și Herțegovina"
"sk" = "Bosna a Hercegovina"
"sl" = "Bosna in Hercegovina"
"sr" = "Босна и Херцеговина"
"fi" = "Bosnia ja Hertsegovina"
"sv" = "Bosnien och Hercegovina"
"ru" = "Босния и Герцеговина"
"uk" = "Боснія і Герцеговина"
"el" = "Βοσνία - Ερζεγοβίνη"
"zh-CN" = "波斯尼亚和黑塞哥维那"
"zh-TW" = "波士尼亞與赫塞哥維納"
"ja" = "ボスニア・ヘルツェゴビナ"
"ko" = "보스니아 헤르체고비나"
"bg" = "Босна и Херцеговина"
"cs" = "Bosna a Hercegovina"
"mt" = "il-Bożnija-Ħerzegovina"
"bs" = "Bosna i Hercegovina"

[country.slugs]
"ca" = "bòsnia-i-hercegovina"
"da" = "bosnien-hercegovina"
"de" = "bosnien-und-herzegowina"
"et" = "bosnia-ja-hertsegoviina"
"en" = "bosnia-herzegovina"
"es" = "bosnia-y-herzegovina"
"fr" = "bosnie-herzégovine"
"oc" = "bòsnia-e-ercegovina"
"lb" = "bosnien-an-herzegowina"
"ga" = "an-bhoisnia-agus-an-heirseagaivéin"
"hr" = "bosna-i-hercegovina"
"it" = "bosnia-ed-erzegovina"
"lt" = "bosnija-ir-hercegovina"
"lv" = "bosnija-un-hercegovina"
"nl" = "bosnië-en-herzegovina"
"hu" = "bosznia-hercegovina"
"no" = "bosnia-hercegovina"
"pl" = "bośnia-i-hercegowina"
"pt-PT" = "bósnia-e-herzegovina"
"ro" = "bosnia-și-herțegovina"
"sk" = "bosna-a-hercegovina"
"sl" = "bosna-in-hercegovina"
"sr" = "босна-и-херцеговина"
"fi" = "bosnia-ja-hertsegovina"
"sv" = "bosnien-och-hercegovina"
"ru" = "босния-и-герцеговина"
"uk" = "боснія-і-герцеговина"
"el" = "βοσνία-ερζεγοβίνη"
"zh-CN" = "波斯尼亚和黑塞哥维那"
"zh-TW" = "波士尼亞與赫塞哥維納"
"ja" = "ボスニア-ヘルツェゴビナ"
"ko" = "보스니아-헤르체고비나"
"bg" = "босна-и-херцеговина"
"cs" = "bosna-a-hercegovina"
"mt" = "il-bożnija-ħerzegovina"

[country.codes]
gisco_cntr_id = "BA"
iso_3166_1_alpha2 = "BA"
iso_3166_1_alpha3 = "BIH"
