schema_version = 1

[[country]]
id = "BE"
kind = "country"
official_languages = ["nl", "fr", "de"]

[country.names]
"ca" = "Bèlgica"
"da" = "Belgien"
"de" = "Belgien"
"et" = "Belgia"
"en" = "Belgium"
"es" = "Bélgica"
"fr" = "Belgique"
"oc" = "Belgica"
"lb" = "Belsch"
"ga" = "an Bheilg"
"hr" = "Belgija"
"it" = "Belgio"
"lt" = "Belgija"
"lv" = "Beļģija"
"nl" = "België"
"hu" = "Belgium"
"no" = "Belgia"
"pl" = "Belgia"
"pt-PT" = "Bélgica"
"ro" = "Belgia"
"sk" = "Belgicko"
"sl" = "Belgija"
"sr" = "Белгија"
"fi" = "Belgia"
"sv" = "Belgien"
"ru" = "Бельгия"
"uk" = "Бельгія"
"el" = "Βέλγιο"
"zh-CN" = "比利时"
"zh-TW" = "比利時"
"ja" = "ベルギー"
"ko" = "벨기에"
"bg" = "Белгия"
"cs" = "Belgie"
"mt" = "il-Belġju"

[country.slugs]
"ca" = "bèlgica"
"da" = "belgien"
"de" = "belgien"
"et" = "belgia"
"en" = "belgium"
"es" = "bélgica"
"fr" = "belgique"
"oc" = "belgica"
"lb" = "belsch"
"ga" = "an-bheilg"
"hr" = "belgija"
"it" = "belgio"
"lt" = "belgija"
"lv" = "beļģija"
"nl" = "belgië"
"hu" = "belgium"
"no" = "belgia"
"pl" = "belgia"
"pt-PT" = "bélgica"
"ro" = "belgia"
"sk" = "belgicko"
"sl" = "belgija"
"sr" = "белгија"
"fi" = "belgia"
"sv" = "belgien"
"ru" = "бельгия"
"uk" = "бельгія"
"el" = "βέλγιο"
"zh-CN" = "比利时"
"zh-TW" = "比利時"
"ja" = "ベルギー"
"ko" = "벨기에"
"bg" = "белгия"
"cs" = "belgie"
"mt" = "il-belġju"

[country.codes]
gisco_cntr_id = "BE"
iso_3166_1_alpha2 = "BE"
iso_3166_1_alpha3 = "BEL"
