schema_version = 1

[[country]]
id = "BG"
kind = "country"
official_languages = ["bg"]

[country.names]
"ca" = "Bulgària"
"da" = "Bulgarien"
"de" = "Bulgarien"
"et" = "Bulgaaria"
"en" = "Bulgaria"
"es" = "Bulgaria"
"fr" = "Bulgarie"
"oc" = "Bolgària"
"lb" = "Bulgarien"
"ga" = "an Bhulgáir"
"hr" = "Bugarska"
"it" = "Bulgaria"
"lt" = "Bulgarija"
"lv" = "Bulgārija"
"nl" = "Bulgarije"
"hu" = "Bulgária"
"no" = "Bulgaria"
"pl" = "Bułgaria"
"pt-PT" = "Bulgária"
"ro" = "Bulgaria"
"sk" = "Bulharsko"
"sl" = "Bolgarija"
"sr" = "Бугарска"
"fi" = "Bulgaria"
"sv" = "Bulgarien"
"ru" = "Болгария"
"uk" = "Болгарія"
"el" = "Βουλγαρία"
"zh-CN" = "保加利亚"
"zh-TW" = "保加利亞"
"ja" = "ブルガリア"
"ko" = "불가리아"
"bg" = "България"
"cs" = "Bulharsko"
"mt" = "il-Bulgarija"

[country.slugs]
"ca" = "bulgària"
"da" = "bulgarien"
"de" = "bulgarien"
"et" = "bulgaaria"
"en" = "bulgaria"
"es" = "bulgaria"
"fr" = "bulgarie"
"oc" = "bolgària"
"lb" = "bulgarien"
"ga" = "an-bhulgáir"
"hr" = "bugarska"
"it" = "bulgaria"
"lt" = "bulgarija"
"lv" = "bulgārija"
"nl" = "bulgarije"
"hu" = "bulgária"
"no" = "bulgaria"
"pl" = "bułgaria"
"pt-PT" = "bulgária"
"ro" = "bulgaria"
"sk" = "bulharsko"
"sl" = "bolgarija"
"sr" = "бугарска"
"fi" = "bulgaria"
"sv" = "bulgarien"
"ru" = "болгария"
"uk" = "болгарія"
"el" = "βουλγαρία"
"zh-CN" = "保加利亚"
"zh-TW" = "保加利亞"
"ja" = "ブルガリア"
"ko" = "불가리아"
"bg" = "българия"
"cs" = "bulharsko"
"mt" = "il-bulgarija"

[country.codes]
gisco_cntr_id = "BG"
iso_3166_1_alpha2 = "BG"
iso_3166_1_alpha3 = "BGR"
