schema_version = 1

[[country]]
id = "BM"
kind = "country"
official_languages = ["en"]

[country.names]
"ca" = "Bermudes"
"da" = "Bermuda"
"de" = "Bermuda"
"et" = "Bermuda"
"en" = "Bermuda"
"es" = "Bermudas"
"fr" = "Bermudes"
"oc" = "Bermuda"
"lb" = "Bermuda"
"ga" = "Beirmiúda"
"hr" = "Bermudi"
"it" = "Bermuda"
"lt" = "Bermuda"
"lv" = "Bermudu salas"
"nl" = "Bermuda"
"hu" = "Bermuda"
"no" = "Bermuda"
"pl" = "Bermudy"
"pt-PT" = "Bermudas"
"ro" = "Bermuda"
"sk" = "Bermudy"
"sl" = "Bermudi"
"sr" = "Бермуди"
"fi" = "Bermuda"
"sv" = "Bermuda"
"ru" = "Бермудские о-ва"
"uk" = "Бермудські Острови"
"el" = "Βερμούδες"
"zh-CN" = "百慕大"
"zh-TW" = "百慕達"
"ja" = "バミューダ"
"ko" = "버뮤다"
"bg" = "Бермудски острови"
"cs" = "Bermudy"
"mt" = "Bermuda"

[country.slugs]
"ca" = "bermudes"
"da" = "bermuda"
"de" = "bermuda"
"et" = "bermuda"
"en" = "bermuda"
"es" = "bermudas"
"fr" = "bermudes"
"oc" = "bermuda"
"lb" = "bermuda"
"ga" = "beirmiúda"
"hr" = "bermudi"
"it" = "bermuda"
"lt" = "bermuda"
"lv" = "bermudu-salas"
"nl" = "bermuda"
"hu" = "bermuda"
"no" = "bermuda"
"pl" = "bermudy"
"pt-PT" = "bermudas"
"ro" = "bermuda"
"sk" = "bermudy"
"sl" = "bermudi"
"sr" = "бермуди"
"fi" = "bermuda"
"sv" = "bermuda"
"ru" = "бермудские-о-ва"
"uk" = "бермудські-острови"
"el" = "βερμούδεσ"
"zh-CN" = "百慕大"
"zh-TW" = "百慕達"
"ja" = "バミューダ"
"ko" = "버뮤다"
"bg" = "бермудски-острови"
"cs" = "bermudy"
"mt" = "bermuda"

[country.codes]
gisco_cntr_id = "BM"
iso_3166_1_alpha2 = "BM"
iso_3166_1_alpha3 = "BMU"
