schema_version = 1

[[country]]
id = "BR"
kind = "country"
official_languages = ["pt"]

[country.names]
"ca" = "Brasil"
"da" = "Brasilien"
"de" = "Brasilien"
"et" = "Brasiilia"
"en" = "Brazil"
"es" = "Brasil"
"fr" = "Brésil"
"oc" = "Brasil"
"lb" = "Brasilien"
"ga" = "an Bhrasaíl"
"hr" = "Brazil"
"it" = "Brasile"
"lt" = "Brazilija"
"lv" = "Brazīlija"
"nl" = "Brazilië"
"hu" = "Brazília"
"no" = "Brasil"
"pl" = "Brazylia"
"pt-PT" = "Brasil"
"ro" = "Brazilia"
"sk" = "Brazília"
"sl" = "Brazilija"
"sr" = "Бразил"
"fi" = "Brasilia"
"sv" = "Brasilien"
"ru" = "Бразилия"
"uk" = "Бразилія"
"el" = "Βραζιλία"
"zh-CN" = "巴西"
"zh-TW" = "巴西"
"ja" = "ブラジル"
"ko" = "브라질"
"bg" = "Бразилия"
"cs" = "Brazílie"
"mt" = "Il-Brażil"
"pt" = "Brasil"

[country.slugs]
"ca" = "brasil"
"da" = "brasilien"
"de" = "brasilien"
"et" = "brasiilia"
"en" = "brazil"
"es" = "brasil"
"fr" = "brésil"
"oc" = "brasil"
"lb" = "brasilien"
"ga" = "an-bhrasaíl"
"hr" = "brazil"
"it" = "brasile"
"lt" = "brazilija"
"lv" = "brazīlija"
"nl" = "brazilië"
"hu" = "brazília"
"no" = "brasil"
"pl" = "brazylia"
"pt-PT" = "brasil"
"ro" = "brazilia"
"sk" = "brazília"
"sl" = "brazilija"
"sr" = "бразил"
"fi" = "brasilia"
"sv" = "brasilien"
"ru" = "бразилия"
"uk" = "бразилія"
"el" = "βραζιλία"
"zh-CN" = "巴西"
"zh-TW" = "巴西"
"ja" = "ブラジル"
"ko" = "브라질"
"bg" = "бразилия"
"cs" = "brazílie"
"mt" = "il-brażil"

[country.codes]
gisco_cntr_id = "BR"
iso_3166_1_alpha2 = "BR"
iso_3166_1_alpha3 = "BRA"
