schema_version = 1

[[country]]
id = "BY"
kind = "country"
official_languages = ["be", "ru"]

[country.names]
"ca" = "Belarús"
"da" = "Belarus"
"de" = "Belarus"
"et" = "Valgevene"
"en" = "Belarus"
"es" = "Bielorrusia"
"fr" = "Biélorussie"
"oc" = "Bielorussia"
"lb" = "Wäissrussland"
"ga" = "an Bhealarúis"
"hr" = "Bjelorusija"
"it" = "Bielorussia"
"lt" = "Baltarusija"
"lv" = "Baltkrievija"
"nl" = "Belarus"
"hu" = "Belarusz"
"no" = "Belarus"
"pl" = "Białoruś"
"pt-PT" = "Bielorrússia"
"ro" = "Belarus"
"sk" = "Bielorusko"
"sl" = "Belorusija"
"sr" = "Белорусија"
"fi" = "Valko-Venäjä"
"sv" = "Belarus"
"ru" = "Беларусь"
"uk" = "Білорусь"
"el" = "Λευκορωσία"
"zh-CN" = "白俄罗斯"
"zh-TW" = "白俄羅斯"
"ja" = "ベラルーシ"
"ko" = "벨라루스"
"bg" = "Беларус"
"cs" = "Bělorusko"
"mt" = "il-Belarussja"
"be" = "Беларусь"

[country.slugs]
"ca" = "belarús"
"da" = "belarus"
"de" = "belarus"
"et" = "valgevene"
"en" = "belarus"
"es" = "bielorrusia"
"fr" = "biélorussie"
"oc" = "bielorussia"
"lb" = "wäissrussland"
"ga" = "an-bhealarúis"
"hr" = "bjelorusija"
"it" = "bielorussia"
"lt" = "baltarusija"
"lv" = "baltkrievija"
"nl" = "belarus"
"hu" = "belarusz"
"no" = "belarus"
"pl" = "białoruś"
"pt-PT" = "bielorrússia"
"ro" = "belarus"
"sk" = "bielorusko"
"sl" = "belorusija"
"sr" = "белорусија"
"fi" = "valko-venäjä"
"sv" = "belarus"
"ru" = "беларусь"
"uk" = "білорусь"
"el" = "λευκορωσία"
"zh-CN" = "白俄罗斯"
"zh-TW" = "白俄羅斯"
"ja" = "ベラルーシ"
"ko" = "벨라루스"
"bg" = "беларус"
"cs" = "bělorusko"
"mt" = "il-belarussja"

[country.codes]
gisco_cntr_id = "BY"
iso_3166_1_alpha2 = "BY"
iso_3166_1_alpha3 = "BLR"
