schema_version = 1

[[country]]
id = "CA"
kind = "country"
official_languages = ["en", "fr"]

[country.names]
"ca" = "Canadà"
"da" = "Canada"
"de" = "Kanada"
"et" = "Kanada"
"en" = "Canada"
"es" = "Canadá"
"fr" = "Canada"
"oc" = "Canadà"
"lb" = "Kanada"
"ga" = "Ceanada"
"hr" = "Kanada"
"it" = "Canada"
"lt" = "Kanada"
"lv" = "Kanāda"
"nl" = "Canada"
"hu" = "Kanada"
"no" = "Canada"
"pl" = "Kanada"
"pt-PT" = "Canadá"
"ro" = "Canada"
"sk" = "Kanada"
"sl" = "Kanada"
"sr" = "Канада"
"fi" = "Kanada"
"sv" = "Kanada"
"ru" = "Канада"
"uk" = "Канада"
"el" = "Καναδάς"
"zh-CN" = "加拿大"
"zh-TW" = "加拿大"
"ja" = "カナダ"
"ko" = "캐나다"
"bg" = "Канада"
"cs" = "Kanada"
"mt" = "il-Kanada"

[country.slugs]
"ca" = "canadà"
"da" = "canada"
"de" = "kanada"
"et" = "kanada"
"en" = "canada"
"es" = "canadá"
"fr" = "canada"
"oc" = "canadà"
"lb" = "kanada"
"ga" = "ceanada"
"hr" = "kanada"
"it" = "canada"
"lt" = "kanada"
"lv" = "kanāda"
"nl" = "canada"
"hu" = "kanada"
"no" = "canada"
"pl" = "kanada"
"pt-PT" = "canadá"
"ro" = "canada"
"sk" = "kanada"
"sl" = "kanada"
"sr" = "канада"
"fi" = "kanada"
"sv" = "kanada"
"ru" = "канада"
"uk" = "канада"
"el" = "καναδάσ"
"zh-CN" = "加拿大"
"zh-TW" = "加拿大"
"ja" = "カナダ"
"ko" = "캐나다"
"bg" = "канада"
"cs" = "kanada"
"mt" = "il-kanada"

[country.codes]
gisco_cntr_id = "CA"
iso_3166_1_alpha2 = "CA"
iso_3166_1_alpha3 = "CAN"
