schema_version = 1

[[country]]
id = "CF"
kind = "country"
official_languages = ["fr", "sg"]

[country.names]
"ca" = "República Centreafricana"
"da" = "Den Centralafrikanske Republik"
"de" = "Zentralafrikanische Republik"
"et" = "Kesk-Aafrika Vabariik"
"en" = "Central African Republic"
"es" = "República Centroafricana"
"fr" = "République centrafricaine"
"oc" = "Republica Centraficana"
"lb" = "Zentralafrikanesch Republik"
"ga" = "Poblacht na hAfraice Láir"
"hr" = "Srednjoafrička Republika"
"it" = "Repubblica Centrafricana"
"lt" = "Centrinės Afrikos Respublika"
"lv" = "Centrālāfrikas Republika"
"nl" = "Centraal-Afrikaanse Republiek"
"hu" = "Közép-afrikai Köztársaság"
"no" = "Den sentralafrikanske republikk"
"pl" = "Republika Środkowoafrykańska"
"pt-PT" = "República Centro-Africana"
"ro" = "Republica Centrafricană"
"sk" = "Stredoafrická republika"
"sl" = "Srednjeafriška republika"
"sr" = "Централноафричка Република"
"fi" = "Keski-Afrikan tasavalta"
"sv" = "Centralafrikanska republiken"
"ru" = "Центрально-Африканская Республика"
"uk" = "Центральноафриканська Республіка"
"el" = "Κεντροαφρικανική Δημοκρατία"
"zh-CN" = "中非共和国"
"zh-TW" = "中非共和國"
"ja" = "中央アフリカ共和国"
"ko" = "중앙 아프리카 공화국"
"bg" = "Централноафриканска република"
"cs" = "Středoafrická republika"
"mt" = "ir-Repubblika Ċentru-Afrikana"
"sg" = "Ködörösêse tî Bêafrîka"

[country.slugs]
"ca" = "república-centreafricana"
"da" = "den-centralafrikanske-republik"
"de" = "zentralafrikanische-republik"
"et" = "kesk-aafrika-vabariik"
"en" = "central-african-republic"
"es" = "república-centroafricana"
"fr" = "république-centrafricaine"
"oc" = "republica-centraficana"
"lb" = "zentralafrikanesch-republik"
"ga" = "poblacht-na-hafraice-láir"
"hr" = "srednjoafrička-republika"
"it" = "repubblica-centrafricana"
"lt" = "centrinės-afrikos-respublika"
"lv" = "centrālāfrikas-republika"
"nl" = "centraal-afrikaanse-republiek"
"hu" = "közép-afrikai-köztársaság"
"no" = "den-sentralafrikanske-republikk"
"pl" = "republika-środkowoafrykańska"
"pt-PT" = "república-centro-africana"
"ro" = "republica-centrafricană"
"sk" = "stredoafrická-republika"
"sl" = "srednjeafriška-republika"
"sr" = "централноафричка-република"
"fi" = "keski-afrikan-tasavalta"
"sv" = "centralafrikanska-republiken"
"ru" = "центрально-африканская-республика"
"uk" = "центральноафриканська-республіка"
"el" = "κεντροαφρικανική-δημοκρατία"
"zh-CN" = "中非共和国"
"zh-TW" = "中非共和國"
"ja" = "中央アフリカ共和国"
"ko" = "중앙-아프리카-공화국"
"bg" = "централноафриканска-република"
"cs" = "středoafrická-republika"
"mt" = "ir-repubblika-ċentru-afrikana"

[country.codes]
gisco_cntr_id = "CF"
iso_3166_1_alpha2 = "CF"
iso_3166_1_alpha3 = "CAF"
