schema_version = 1

[[country]]
id = "CH"
kind = "country"
official_languages = ["de", "fr", "it", "rm"]

[country.names]
"ca" = "Suïssa"
"da" = "Schweiz"
"de" = "Schweiz"
"et" = "Šveits"
"en" = "Switzerland"
"es" = "Suiza"
"fr" = "Suisse"
"oc" = "Soïssa"
"lb" = "Schwäiz"
"ga" = "an Eilvéis"
"hr" = "Švicarska"
"it" = "Svizzera"
"lt" = "Šveicarija"
"lv" = "Šveice"
"nl" = "Zwitserland"
"hu" = "Svájc"
"no" = "Sveits"
"pl" = "Szwajcaria"
"pt-PT" = "Suíça"
"ro" = "Elveția"
"sk" = "Švajčiarsko"
"sl" = "Švica"
"sr" = "Швајцарска"
"fi" = "Sveitsi"
"sv" = "Schweiz"
"ru" = "Швейцария"
"uk" = "Швейцарія"
"el" = "Ελβετία"
"zh-CN" = "瑞士"
"zh-TW" = "瑞士"
"ja" = "スイス"
"ko" = "스위스"
"bg" = "Швейцария"
"cs" = "Švýcarsko"
"mt" = "l-Iżvizzera"
"rm" = "Svizra"

[country.slugs]
"ca" = "suïssa"
"da" = "schweiz"
"de" = "schweiz"
"et" = "šveits"
"en" = "switzerland"
"es" = "suiza"
"fr" = "suisse"
"oc" = "soïssa"
"lb" = "schwäiz"
"ga" = "an-eilvéis"
"hr" = "švicarska"
"it" = "svizzera"
"lt" = "šveicarija"
"lv" = "šveice"
"nl" = "zwitserland"
"hu" = "svájc"
"no" = "sveits"
"pl" = "szwajcaria"
"pt-PT" = "suíça"
"ro" = "elveția"
"sk" = "švajčiarsko"
"sl" = "švica"
"sr" = "швајцарска"
"fi" = "sveitsi"
"sv" = "schweiz"
"ru" = "швейцария"
"uk" = "швейцарія"
"el" = "ελβετία"
"zh-CN" = "瑞士"
"zh-TW" = "瑞士"
"ja" = "スイス"
"ko" = "스위스"
"bg" = "швейцария"
"cs" = "švýcarsko"
"mt" = "l-iżvizzera"

[country.codes]
gisco_cntr_id = "CH"
iso_3166_1_alpha2 = "CH"
iso_3166_1_alpha3 = "CHE"
