schema_version = 1

[[country]]
id = "CN"
kind = "country"
official_languages = ["zh-CN"]

[country.names]
"ca" = "Xina"
"da" = "Kina"
"de" = "China"
"et" = "Hiina"
"en" = "China"
"es" = "China"
"fr" = "Chine"
"oc" = "China"
"lb" = "China"
"ga" = "an tSín"
"hr" = "Kina"
"it" = "Cina"
"lt" = "Kinija"
"lv" = "Ķīna"
"nl" = "China"
"hu" = "Kína"
"no" = "Kina"
"pl" = "Chiny"
"pt-PT" = "China"
"ro" = "China"
"sk" = "Čína"
"sl" = "Kitajska"
"sr" = "Кина"
"fi" = "Kiina"
"sv" = "Kina"
"ru" = "Китай"
"uk" = "Китай"
"el" = "Κίνα"
"zh-CN" = "中国"
"zh-TW" = "中國"
"ja" = "中国"
"ko" = "중국"
"bg" = "Китай"
"cs" = "Čína"
"mt" = "iċ-Ċina"

[country.slugs]
"ca" = "xina"
"da" = "kina"
"de" = "china"
"et" = "hiina"
"en" = "china"
"es" = "china"
"fr" = "chine"
"oc" = "china"
"lb" = "china"
"ga" = "an-tsín"
"hr" = "kina"
"it" = "cina"
"lt" = "kinija"
"lv" = "ķīna"
"nl" = "china"
"hu" = "kína"
"no" = "kina"
"pl" = "chiny"
"pt-PT" = "china"
"ro" = "china"
"sk" = "čína"
"sl" = "kitajska"
"sr" = "кина"
"fi" = "kiina"
"sv" = "kina"
"ru" = "китай"
"uk" = "китай"
"el" = "κίνα"
"zh-CN" = "中国"
"zh-TW" = "中國"
"ja" = "中国"
"ko" = "중국"
"bg" = "китай"
"cs" = "čína"
"mt" = "iċ-ċina"

[country.codes]
gisco_cntr_id = "CN"
iso_3166_1_alpha2 = "CN"
iso_3166_1_alpha3 = "CHN"
