schema_version = 1

[[country]]
id = "CO"
kind = "country"
official_languages = ["es"]

[country.names]
"ca" = "Colòmbia"
"da" = "Colombia"
"de" = "Kolumbien"
"et" = "Colombia"
"en" = "Colombia"
"es" = "Colombia"
"fr" = "Colombie"
"oc" = "Colómbia"
"lb" = "Kolumbien"
"ga" = "an Cholóim"
"hr" = "Kolumbija"
"it" = "Colombia"
"lt" = "Kolumbija"
"lv" = "Kolumbija"
"nl" = "Colombia"
"hu" = "Kolumbia"
"no" = "Colombia"
"pl" = "Kolumbia"
"pt-PT" = "Colômbia"
"ro" = "Columbia"
"sk" = "Kolumbia"
"sl" = "Kolumbija"
"sr" = "Колумбија"
"fi" = "Kolumbia"
"sv" = "Colombia"
"ru" = "Колумбия"
"uk" = "Колумбія"
"el" = "Κολομβία"
"zh-CN" = "哥伦比亚"
"zh-TW" = "哥倫比亞"
"ja" = "コロンビア"
"ko" = "콜롬비아"
"bg" = "Колумбия"
"cs" = "Kolumbie"
"mt" = "il-Kolombja"

[country.slugs]
"ca" = "colòmbia"
"da" = "colombia"
"de" = "kolumbien"
"et" = "colombia"
"en" = "colombia"
"es" = "colombia"
"fr" = "colombie"
"oc" = "colómbia"
"lb" = "kolumbien"
"ga" = "an-cholóim"
"hr" = "kolumbija"
"it" = "colombia"
"lt" = "kolumbija"
"lv" = "kolumbija"
"nl" = "colombia"
"hu" = "kolumbia"
"no" = "colombia"
"pl" = "kolumbia"
"pt-PT" = "colômbia"
"ro" = "columbia"
"sk" = "kolumbia"
"sl" = "kolumbija"
"sr" = "колумбија"
"fi" = "kolumbia"
"sv" = "colombia"
"ru" = "колумбия"
"uk" = "колумбія"
"el" = "κολομβία"
"zh-CN" = "哥伦比亚"
"zh-TW" = "哥倫比亞"
"ja" = "コロンビア"
"ko" = "콜롬비아"
"bg" = "колумбия"
"cs" = "kolumbie"
"mt" = "il-kolombja"

[country.codes]
gisco_cntr_id = "CO"
iso_3166_1_alpha2 = "CO"
iso_3166_1_alpha3 = "COL"
