schema_version = 1

[[country]]
id = "CY"
kind = "country"
official_languages = ["el", "tr"]

[country.names]
"ca" = "Xipre"
"da" = "Cypern"
"de" = "Zypern"
"et" = "Küpros"
"en" = "Cyprus"
"es" = "Chipre"
"fr" = "Chypre"
"oc" = "Chipre"
"lb" = "Zypern"
"ga" = "an Chipir"
"hr" = "Cipar"
"it" = "Cipro"
"lt" = "Kipras"
"lv" = "Kipra"
"nl" = "Cyprus"
"hu" = "Ciprus"
"no" = "Kypros"
"pl" = "Cypr"
"pt-PT" = "Chipre"
"ro" = "Cipru"
"sk" = "Cyprus"
"sl" = "Ciper"
"sr" = "Кипар"
"fi" = "Kypros"
"sv" = "Cypern"
"ru" = "Кипр"
"uk" = "Кіпр"
"el" = "Κύπρος"
"zh-CN" = "塞浦路斯"
"zh-TW" = "賽普勒斯"
"ja" = "キプロス"
"ko" = "키프로스"
"bg" = "Кипър"
"cs" = "Kypr"
"mt" = "Ċipru"
"tr" = "Kıbrıs"

[country.slugs]
"ca" = "xipre"
"da" = "cypern"
"de" = "zypern"
"et" = "küpros"
"en" = "cyprus"
"es" = "chipre"
"fr" = "chypre"
"oc" = "chipre"
"lb" = "zypern"
"ga" = "an-chipir"
"hr" = "cipar"
"it" = "cipro"
"lt" = "kipras"
"lv" = "kipra"
"nl" = "cyprus"
"hu" = "ciprus"
"no" = "kypros"
"pl" = "cypr"
"pt-PT" = "chipre"
"ro" = "cipru"
"sk" = "cyprus"
"sl" = "ciper"
"sr" = "кипар"
"fi" = "kypros"
"sv" = "cypern"
"ru" = "кипр"
"uk" = "кіпр"
"el" = "κύπροσ"
"zh-CN" = "塞浦路斯"
"zh-TW" = "賽普勒斯"
"ja" = "キプロス"
"ko" = "키프로스"
"bg" = "кипър"
"cs" = "kypr"
"mt" = "ċipru"

[country.codes]
gisco_cntr_id = "CY"
iso_3166_1_alpha2 = "CY"
iso_3166_1_alpha3 = "CYP"
