schema_version = 1

[[country]]
id = "CZ"
kind = "country"
official_languages = ["cs"]

[country.names]
"ca" = "Txèquia"
"da" = "Tjekkiet"
"de" = "Tschechien"
"et" = "Tšehhi"
"en" = "Czechia"
"es" = "Chequia"
"fr" = "Tchéquie"
"oc" = "Chequia"
"lb" = "Tschechien"
"ga" = "an tSeicia"
"hr" = "Češka"
"it" = "Cechia"
"lt" = "Čekija"
"lv" = "Čehija"
"nl" = "Tsjechië"
"hu" = "Csehország"
"no" = "Tsjekkia"
"pl" = "Czechy"
"pt-PT" = "Chéquia"
"ro" = "Cehia"
"sk" = "Česko"
"sl" = "Češka"
"sr" = "Чешка"
"fi" = "Tšekki"
"sv" = "Tjeckien"
"ru" = "Чехия"
"uk" = "Чехія"
"el" = "Τσεχία"
"zh-CN" = "捷克"
"zh-TW" = "捷克"
"ja" = "チェコ"
"ko" = "체코"
"bg" = "Чехия"
"cs" = "Česko"
"mt" = "ir-Repubblika Ċeka"

[country.slugs]
"ca" = "txèquia"
"da" = "tjekkiet"
"de" = "tschechien"
"et" = "tšehhi"
"en" = "czechia"
"es" = "chequia"
"fr" = "tchéquie"
"oc" = "chequia"
"lb" = "tschechien"
"ga" = "an-tseicia"
"hr" = "češka"
"it" = "cechia"
"lt" = "čekija"
"lv" = "čehija"
"nl" = "tsjechië"
"hu" = "csehország"
"no" = "tsjekkia"
"pl" = "czechy"
"pt-PT" = "chéquia"
"ro" = "cehia"
"sk" = "česko"
"sl" = "češka"
"sr" = "чешка"
"fi" = "tšekki"
"sv" = "tjeckien"
"ru" = "чехия"
"uk" = "чехія"
"el" = "τσεχία"
"zh-CN" = "捷克"
"zh-TW" = "捷克"
"ja" = "チェコ"
"ko" = "체코"
"bg" = "чехия"
"cs" = "česko"
"mt" = "ir-repubblika-ċeka"

[country.codes]
gisco_cntr_id = "CZ"
iso_3166_1_alpha2 = "CZ"
iso_3166_1_alpha3 = "CZE"
