schema_version = 1

[[country]]
id = "DE"
kind = "country"
official_languages = ["de"]

[country.names]
"ca" = "Alemanya"
"da" = "Tyskland"
"de" = "Deutschland"
"et" = "Saksamaa"
"en" = "Germany"
"es" = "Alemania"
"fr" = "Allemagne"
"oc" = "Alemanha"
"lb" = "Däitschland"
"ga" = "an Ghearmáin"
"hr" = "Njemačka"
"it" = "Germania"
"lt" = "Vokietija"
"lv" = "Vācija"
"nl" = "Duitsland"
"hu" = "Németország"
"no" = "Tyskland"
"pl" = "Niemcy"
"pt-PT" = "Alemanha"
"ro" = "Germania"
"sk" = "Nemecko"
"sl" = "Nemčija"
"sr" = "Немачка"
"fi" = "Saksa"
"sv" = "Tyskland"
"ru" = "Германия"
"uk" = "Німеччина"
"el" = "Γερμανία"
"zh-CN" = "德国"
"zh-TW" = "德國"
"ja" = "ドイツ"
"ko" = "독일"
"bg" = "Германия"
"cs" = "Německo"
"mt" = "il-Ġermanja"

[country.slugs]
"ca" = "alemanya"
"da" = "tyskland"
"de" = "deutschland"
"et" = "saksamaa"
"en" = "germany"
"es" = "alemania"
"fr" = "allemagne"
"oc" = "alemanha"
"lb" = "däitschland"
"ga" = "an-ghearmáin"
"hr" = "njemačka"
"it" = "germania"
"lt" = "vokietija"
"lv" = "vācija"
"nl" = "duitsland"
"hu" = "németország"
"no" = "tyskland"
"pl" = "niemcy"
"pt-PT" = "alemanha"
"ro" = "germania"
"sk" = "nemecko"
"sl" = "nemčija"
"sr" = "немачка"
"fi" = "saksa"
"sv" = "tyskland"
"ru" = "германия"
"uk" = "німеччина"
"el" = "γερμανία"
"zh-CN" = "德国"
"zh-TW" = "德國"
"ja" = "ドイツ"
"ko" = "독일"
"bg" = "германия"
"cs" = "německo"
"mt" = "il-ġermanja"

[country.codes]
gisco_cntr_id = "DE"
iso_3166_1_alpha2 = "DE"
iso_3166_1_alpha3 = "DEU"
