schema_version = 1

[[country]]
id = "DK"
kind = "country"
official_languages = ["da"]

[country.names]
"ca" = "Dinamarca"
"da" = "Danmark"
"de" = "Dänemark"
"et" = "Taani"
"en" = "Denmark"
"es" = "Dinamarca"
"fr" = "Danemark"
"oc" = "Danemarc"
"lb" = "Dänemark"
"ga" = "an Danmhairg"
"hr" = "Danska"
"it" = "Danimarca"
"lt" = "Danija"
"lv" = "Dānija"
"nl" = "Denemarken"
"hu" = "Dánia"
"no" = "Danmark"
"pl" = "Dania"
"pt-PT" = "Dinamarca"
"ro" = "Danemarca"
"sk" = "Dánsko"
"sl" = "Danska"
"sr" = "Данска"
"fi" = "Tanska"
"sv" = "Danmark"
"ru" = "Дания"
"uk" = "Данія"
"el" = "Δανία"
"zh-CN" = "丹麦"
"zh-TW" = "丹麥"
"ja" = "デンマーク"
"ko" = "덴마크"
"bg" = "Дания"
"cs" = "Dánsko"
"mt" = "id-Danimarka"

[country.slugs]
"ca" = "dinamarca"
"da" = "danmark"
"de" = "dänemark"
"et" = "taani"
"en" = "denmark"
"es" = "dinamarca"
"fr" = "danemark"
"oc" = "danemarc"
"lb" = "dänemark"
"ga" = "an-danmhairg"
"hr" = "danska"
"it" = "danimarca"
"lt" = "danija"
"lv" = "dānija"
"nl" = "denemarken"
"hu" = "dánia"
"no" = "danmark"
"pl" = "dania"
"pt-PT" = "dinamarca"
"ro" = "danemarca"
"sk" = "dánsko"
"sl" = "danska"
"sr" = "данска"
"fi" = "tanska"
"sv" = "danmark"
"ru" = "дания"
"uk" = "данія"
"el" = "δανία"
"zh-CN" = "丹麦"
"zh-TW" = "丹麥"
"ja" = "デンマーク"
"ko" = "덴마크"
"bg" = "дания"
"cs" = "dánsko"
"mt" = "id-danimarka"

[country.codes]
gisco_cntr_id = "DK"
iso_3166_1_alpha2 = "DK"
iso_3166_1_alpha3 = "DNK"
