schema_version = 1

[[country]]
id = "DZ"
kind = "country"
official_languages = ["ar", "tzm"]

[country.names]
"ca" = "Algèria"
"da" = "Algeriet"
"de" = "Algerien"
"et" = "Alžeeria"
"en" = "Algeria"
"es" = "Argelia"
"fr" = "Algérie"
"oc" = "Argeria"
"lb" = "Algerien"
"ga" = "An Ailgéir"
"hr" = "Alžir"
"it" = "Algeria"
"lt" = "Alžyras"
"lv" = "Alžīrija"
"nl" = "Algerije"
"hu" = "Algéria"
"no" = "Algerie"
"pl" = "Algieria"
"pt-PT" = "Argélia"
"ro" = "Algeria"
"sk" = "Alžírsko"
"sl" = "Alžirija"
"sr" = "Алжир"
"fi" = "Algeria"
"sv" = "Algeriet"
"ru" = "Алжир"
"uk" = "Алжир"
"el" = "Αλγερία"
"zh-CN" = "阿尔及利亚"
"zh-TW" = "阿爾及利亞"
"ja" = "アルジェリア"
"ko" = "알제리"
"bg" = "Алжир"
"cs" = "Alžírsko"
"mt" = "l-Alġerija"
"ar" = "الجزائر"
"tzm" = "Dzayer"

[country.slugs]
"ca" = "algèria"
"da" = "algeriet"
"de" = "algerien"
"et" = "alžeeria"
"en" = "algeria"
"es" = "argelia"
"fr" = "algérie"
"oc" = "argeria"
"lb" = "algerien"
"ga" = "an-ailgéir"
"hr" = "alžir"
"it" = "algeria"
"lt" = "alžyras"
"lv" = "alžīrija"
"nl" = "algerije"
"hu" = "algéria"
"no" = "algerie"
"pl" = "algieria"
"pt-PT" = "argélia"
"ro" = "algeria"
"sk" = "alžírsko"
"sl" = "alžirija"
"sr" = "алжир"
"fi" = "algeria"
"sv" = "algeriet"
"ru" = "алжир"
"uk" = "алжир"
"el" = "αλγερία"
"zh-CN" = "阿尔及利亚"
"zh-TW" = "阿爾及利亞"
"ja" = "アルジェリア"
"ko" = "알제리"
"bg" = "алжир"
"cs" = "alžírsko"
"mt" = "l-alġerija"

[country.codes]
gisco_cntr_id = "DZ"
iso_3166_1_alpha2 = "DZ"
iso_3166_1_alpha3 = "DZA"
