schema_version = 1

[[country]]
id = "EE"
kind = "country"
official_languages = ["et"]

[country.names]
"ca" = "Estònia"
"da" = "Estland"
"de" = "Estland"
"et" = "Eesti"
"en" = "Estonia"
"es" = "Estonia"
"fr" = "Estonie"
"oc" = "Estònia"
"lb" = "Estland"
"ga" = "an Eastóin"
"hr" = "Estonija"
"it" = "Estonia"
"lt" = "Estija"
"lv" = "Igaunija"
"nl" = "Estland"
"hu" = "Észtország"
"no" = "Estland"
"pl" = "Estonia"
"pt-PT" = "Estónia"
"ro" = "Estonia"
"sk" = "Estónsko"
"sl" = "Estonija"
"sr" = "Естонија"
"fi" = "Viro"
"sv" = "Estland"
"ru" = "Эстония"
"uk" = "Естонія"
"el" = "Εσθονία"
"zh-CN" = "爱沙尼亚"
"zh-TW" = "愛沙尼亞"
"ja" = "エストニア"
"ko" = "에스토니아"
"bg" = "Естония"
"cs" = "Estonsko"
"mt" = "l-Estonja"

[country.slugs]
"ca" = "estònia"
"da" = "estland"
"de" = "estland"
"et" = "eesti"
"en" = "estonia"
"es" = "estonia"
"fr" = "estonie"
"oc" = "estònia"
"lb" = "estland"
"ga" = "an-eastóin"
"hr" = "estonija"
"it" = "estonia"
"lt" = "estija"
"lv" = "igaunija"
"nl" = "estland"
"hu" = "észtország"
"no" = "estland"
"pl" = "estonia"
"pt-PT" = "estónia"
"ro" = "estonia"
"sk" = "estónsko"
"sl" = "estonija"
"sr" = "естонија"
"fi" = "viro"
"sv" = "estland"
"ru" = "эстония"
"uk" = "естонія"
"el" = "εσθονία"
"zh-CN" = "爱沙尼亚"
"zh-TW" = "愛沙尼亞"
"ja" = "エストニア"
"ko" = "에스토니아"
"bg" = "естония"
"cs" = "estonsko"
"mt" = "l-estonja"

[country.codes]
gisco_cntr_id = "EE"
iso_3166_1_alpha2 = "EE"
iso_3166_1_alpha3 = "EST"
