schema_version = 1

[[country]]
id = "EL"
kind = "country"
official_languages = ["el"]

[country.names]
"ca" = "Grècia"
"da" = "Grækenland"
"de" = "Griechenland"
"et" = "Kreeka"
"en" = "Greece"
"es" = "Grecia"
"fr" = "Grèce"
"oc" = "Grècia"
"lb" = "Griicheland"
"ga" = "an Ghréig"
"hr" = "Grčka"
"it" = "Grecia"
"lt" = "Graikija"
"lv" = "Grieķija"
"nl" = "Griekenland"
"hu" = "Görögország"
"no" = "Hellas"
"pl" = "Grecja"
"pt-PT" = "Grécia"
"ro" = "Grecia"
"sk" = "Grécko"
"sl" = "Grčija"
"sr" = "Грчка"
"fi" = "Kreikka"
"sv" = "Grekland"
"ru" = "Греция"
"uk" = "Греція"
"el" = "Ελλάδα"
"zh-CN" = "希腊"
"zh-TW" = "希臘"
"ja" = "ギリシャ"
"ko" = "그리스"
"bg" = "Гърция"
"cs" = "Řecko"
"mt" = "il-Greċja"

[country.slugs]
"ca" = "grècia"
"da" = "grækenland"
"de" = "griechenland"
"et" = "kreeka"
"en" = "greece"
"es" = "grecia"
"fr" = "grèce"
"oc" = "grècia"
"lb" = "griicheland"
"ga" = "an-ghréig"
"hr" = "grčka"
"it" = "grecia"
"lt" = "graikija"
"lv" = "grieķija"
"nl" = "griekenland"
"hu" = "görögország"
"no" = "hellas"
"pl" = "grecja"
"pt-PT" = "grécia"
"ro" = "grecia"
"sk" = "grécko"
"sl" = "grčija"
"sr" = "грчка"
"fi" = "kreikka"
"sv" = "grekland"
"ru" = "греция"
"uk" = "греція"
"el" = "ελλάδα"
"zh-CN" = "希腊"
"zh-TW" = "希臘"
"ja" = "ギリシャ"
"ko" = "그리스"
"bg" = "гърция"
"cs" = "řecko"
"mt" = "il-greċja"

[country.codes]
gisco_cntr_id = "EL"
iso_3166_1_alpha2 = "GR"
iso_3166_1_alpha3 = "GRC"
