schema_version = 1

[[country]]
id = "ES"
kind = "country"
official_languages = ["es"]

[country.names]
"ca" = "Espanya"
"da" = "Spanien"
"de" = "Spanien"
"et" = "Hispaania"
"en" = "Spain"
"es" = "España"
"fr" = "Espagne"
"oc" = "Espanha"
"lb" = "Spanien"
"ga" = "an Spáinn"
"hr" = "Španjolska"
"it" = "Spagna"
"lt" = "Ispanija"
"lv" = "Spānija"
"nl" = "Spanje"
"hu" = "Spanyolország"
"no" = "Spania"
"pl" = "Hiszpania"
"pt-PT" = "Espanha"
"ro" = "Spania"
"sk" = "Španielsko"
"sl" = "Španija"
"sr" = "Шпанија"
"fi" = "Espanja"
"sv" = "Spanien"
"ru" = "Испания"
"uk" = "Іспанія"
"el" = "Ισπανία"
"zh-CN" = "西班牙"
"zh-TW" = "西班牙"
"ja" = "スペイン"
"ko" = "스페인"
"bg" = "Испания"
"cs" = "Španělsko"
"mt" = "Spanja"

[country.slugs]
"ca" = "espanya"
"da" = "spanien"
"de" = "spanien"
"et" = "hispaania"
"en" = "spain"
"es" = "españa"
"fr" = "espagne"
"oc" = "espanha"
"lb" = "spanien"
"ga" = "an-spáinn"
"hr" = "španjolska"
"it" = "spagna"
"lt" = "ispanija"
"lv" = "spānija"
"nl" = "spanje"
"hu" = "spanyolország"
"no" = "spania"
"pl" = "hiszpania"
"pt-PT" = "espanha"
"ro" = "spania"
"sk" = "španielsko"
"sl" = "španija"
"sr" = "шпанија"
"fi" = "espanja"
"sv" = "spanien"
"ru" = "испания"
"uk" = "іспанія"
"el" = "ισπανία"
"zh-CN" = "西班牙"
"zh-TW" = "西班牙"
"ja" = "スペイン"
"ko" = "스페인"
"bg" = "испания"
"cs" = "španělsko"
"mt" = "spanja"

[country.codes]
gisco_cntr_id = "ES"
iso_3166_1_alpha2 = "ES"
iso_3166_1_alpha3 = "ESP"
