schema_version = 1

[[country]]
id = "ET"
kind = "country"
official_languages = ["am"]

[country.names]
"ca" = "Etiòpia"
"da" = "Etiopien"
"de" = "Äthiopien"
"et" = "Etioopia"
"en" = "Ethiopia"
"es" = "Etiopía"
"fr" = "Éthiopie"
"oc" = "Etiopia"
"lb" = "Ethiopien"
"ga" = "an Aetóip"
"hr" = "Etiopija"
"it" = "Etiopia"
"lt" = "Etiopija"
"lv" = "Etiopija"
"nl" = "Ethiopië"
"hu" = "Etiópia"
"no" = "Etiopia"
"pl" = "Etiopia"
"pt-PT" = "Etiópia"
"ro" = "Etiopia"
"sk" = "Etiópia"
"sl" = "Etiopija"
"sr" = "Етиопија"
"fi" = "Etiopia"
"sv" = "Etiopien"
"ru" = "Эфиопия"
"uk" = "Ефіопія"
"el" = "Αιθιοπία"
"zh-CN" = "埃塞俄比亚"
"zh-TW" = "衣索比亞"
"ja" = "エチオピア"
"ko" = "에티오피아"
"bg" = "Етиопия"
"cs" = "Etiopie"
"mt" = "l-Etjopja"
"am" = "ኢትዮጵያ"

[country.slugs]
"ca" = "etiòpia"
"da" = "etiopien"
"de" = "äthiopien"
"et" = "etioopia"
"en" = "ethiopia"
"es" = "etiopía"
"fr" = "éthiopie"
"oc" = "etiopia"
"lb" = "ethiopien"
"ga" = "an-aetóip"
"hr" = "etiopija"
"it" = "etiopia"
"lt" = "etiopija"
"lv" = "etiopija"
"nl" = "ethiopië"
"hu" = "etiópia"
"no" = "etiopia"
"pl" = "etiopia"
"pt-PT" = "etiópia"
"ro" = "etiopia"
"sk" = "etiópia"
"sl" = "etiopija"
"sr" = "етиопија"
"fi" = "etiopia"
"sv" = "etiopien"
"ru" = "эфиопия"
"uk" = "ефіопія"
"el" = "αιθιοπία"
"zh-CN" = "埃塞俄比亚"
"zh-TW" = "衣索比亞"
"ja" = "エチオピア"
"ko" = "에티오피아"
"bg" = "етиопия"
"cs" = "etiopie"
"mt" = "l-etjopja"

[country.codes]
gisco_cntr_id = "ET"
iso_3166_1_alpha2 = "ET"
iso_3166_1_alpha3 = "ETH"
