schema_version = 1

[[country]]
id = "FI"
kind = "country"
official_languages = ["fi", "sv"]

[country.names]
"ca" = "Finlàndia"
"da" = "Finland"
"de" = "Finnland"
"et" = "Soome"
"en" = "Finland"
"es" = "Finlandia"
"fr" = "Finlande"
"oc" = "Finlàndia"
"lb" = "Finnland"
"ga" = "an Fhionlainn"
"hr" = "Finska"
"it" = "Finlandia"
"lt" = "Suomija"
"lv" = "Somija"
"nl" = "Finland"
"hu" = "Finnország"
"no" = "Finland"
"pl" = "Finlandia"
"pt-PT" = "Finlândia"
"ro" = "Finlanda"
"sk" = "Fínsko"
"sl" = "Finska"
"sr" = "Финска"
"fi" = "Suomi"
"sv" = "Finland"
"ru" = "Финляндия"
"uk" = "Фінляндія"
"el" = "Φινλανδία"
"zh-CN" = "芬兰"
"zh-TW" = "芬蘭"
"ja" = "フィンランド"
"ko" = "핀란드"
"bg" = "Финландия"
"cs" = "Finsko"
"mt" = "il-Finlandja"

[country.slugs]
"ca" = "finlàndia"
"da" = "finland"
"de" = "finnland"
"et" = "soome"
"en" = "finland"
"es" = "finlandia"
"fr" = "finlande"
"oc" = "finlàndia"
"lb" = "finnland"
"ga" = "an-fhionlainn"
"hr" = "finska"
"it" = "finlandia"
"lt" = "suomija"
"lv" = "somija"
"nl" = "finland"
"hu" = "finnország"
"no" = "finland"
"pl" = "finlandia"
"pt-PT" = "finlândia"
"ro" = "finlanda"
"sk" = "fínsko"
"sl" = "finska"
"sr" = "финска"
"fi" = "suomi"
"sv" = "finland"
"ru" = "финляндия"
"uk" = "фінляндія"
"el" = "φινλανδία"
"zh-CN" = "芬兰"
"zh-TW" = "芬蘭"
"ja" = "フィンランド"
"ko" = "핀란드"
"bg" = "финландия"
"cs" = "finsko"
"mt" = "il-finlandja"

[country.codes]
gisco_cntr_id = "FI"
iso_3166_1_alpha2 = "FI"
iso_3166_1_alpha3 = "FIN"
