schema_version = 1

[[country]]
id = "FR"
kind = "country"
official_languages = ["fr"]

[country.names]
"ca" = "França"
"da" = "Frankrig"
"de" = "Frankreich"
"et" = "Prantsusmaa"
"en" = "France"
"es" = "Francia"
"fr" = "France"
"oc" = "França"
"lb" = "Frankräich"
"ga" = "an Fhrainc"
"hr" = "Francuska"
"it" = "Francia"
"lt" = "Prancūzija"
"lv" = "Francija"
"nl" = "Frankrijk"
"hu" = "Franciaország"
"no" = "Frankrike"
"pl" = "Francja"
"pt-PT" = "França"
"ro" = "Franța"
"sk" = "Francúzsko"
"sl" = "Francija"
"sr" = "Француска"
"fi" = "Ranska"
"sv" = "Frankrike"
"ru" = "Франция"
"uk" = "Франція"
"el" = "Γαλλία"
"zh-CN" = "法国"
"zh-TW" = "法國"
"ja" = "フランス"
"ko" = "프랑스"
"bg" = "Франция"
"cs" = "Francie"
"mt" = "Franza"

[country.slugs]
"ca" = "frança"
"da" = "frankrig"
"de" = "frankreich"
"et" = "prantsusmaa"
"en" = "france"
"es" = "francia"
"fr" = "france"
"oc" = "frança"
"lb" = "frankräich"
"ga" = "an-fhrainc"
"hr" = "francuska"
"it" = "francia"
"lt" = "prancūzija"
"lv" = "francija"
"nl" = "frankrijk"
"hu" = "franciaország"
"no" = "frankrike"
"pl" = "francja"
"pt-PT" = "frança"
"ro" = "franța"
"sk" = "francúzsko"
"sl" = "francija"
"sr" = "француска"
"fi" = "ranska"
"sv" = "frankrike"
"ru" = "франция"
"uk" = "франція"
"el" = "γαλλία"
"zh-CN" = "法国"
"zh-TW" = "法國"
"ja" = "フランス"
"ko" = "프랑스"
"bg" = "франция"
"cs" = "francie"
"mt" = "franza"

[country.codes]
gisco_cntr_id = "FR"
iso_3166_1_alpha2 = "FR"
iso_3166_1_alpha3 = "FRA"
