schema_version = 1

[[country]]
id = "GL"
kind = "country"
official_languages = ["kl"]

[country.names]
"ca" = "Groenlàndia"
"da" = "Grønland"
"de" = "Grönland"
"et" = "Gröönimaa"
"en" = "Greenland"
"es" = "Groenlandia"
"fr" = "Groenland"
"oc" = "Groenlàndia"
"lb" = "Grönland"
"ga" = "an Ghraonlainn"
"hr" = "Grenland"
"it" = "Groenlandia"
"lt" = "Grenlandija"
"lv" = "Grenlande"
"nl" = "Groenland"
"hu" = "Grönland"
"no" = "Grønland"
"pl" = "Grenlandia"
"pt-PT" = "Gronelândia"
"ro" = "Groenlanda"
"sk" = "Grónsko"
"sl" = "Grenlandija"
"sr" = "Гренланд"
"fi" = "Grönlanti"
"sv" = "Grönland"
"ru" = "Гренландия"
"uk" = "Гренландія"
"el" = "Γροιλανδία"
"zh-CN" = "格陵兰"
"zh-TW" = "格陵蘭"
"ja" = "グリーンランド"
"ko" = "그린란드"
"bg" = "Гренландия"
"cs" = "Grónsko"
"mt" = "Greenland"
"kl" = "Kalaallit Nunaat"

[country.slugs]
"ca" = "groenlàndia"
"da" = "grønland"
"de" = "grönland"
"et" = "gröönimaa"
"en" = "greenland"
"es" = "groenlandia"
"fr" = "groenland"
"oc" = "groenlàndia"
"lb" = "grönland"
"ga" = "an-ghraonlainn"
"hr" = "grenland"
"it" = "groenlandia"
"lt" = "grenlandija"
"lv" = "grenlande"
"nl" = "groenland"
"hu" = "grönland"
"no" = "grønland"
"pl" = "grenlandia"
"pt-PT" = "gronelândia"
"ro" = "groenlanda"
"sk" = "grónsko"
"sl" = "grenlandija"
"sr" = "гренланд"
"fi" = "grönlanti"
"sv" = "grönland"
"ru" = "гренландия"
"uk" = "гренландія"
"el" = "γροιλανδία"
"zh-CN" = "格陵兰"
"zh-TW" = "格陵蘭"
"ja" = "グリーンランド"
"ko" = "그린란드"
"bg" = "гренландия"
"cs" = "grónsko"
"mt" = "greenland"

[country.codes]
gisco_cntr_id = "GL"
iso_3166_1_alpha2 = "GL"
iso_3166_1_alpha3 = "GRL"
