schema_version = 1

[[country]]
id = "HK"
kind = "country"
official_languages = ["zh-TW", "en"]

[country.names]
"ca" = "Hong Kong (RAE Xina)"
"da" = "SAR Hongkong"
"de" = "Sonderverwaltungsregion Hongkong"
"et" = "Hongkongi erihalduspiirkond"
"en" = "Hong Kong SAR China"
"es" = "RAE de Hong Kong (China)"
"fr" = "R.A.S. chinoise de Hong Kong"
"oc" = "Hong Kong"
"lb" = "Spezialverwaltungszon Hong Kong"
"ga" = "Sainréigiún Riaracháin Hong Cong, Daonphoblacht na Síne"
"hr" = "PUP Hong Kong Kina"
"it" = "RAS di Hong Kong"
"lt" = "Ypatingasis Administracinis Kinijos Regionas Honkongas"
"lv" = "Ķīnas īpašās pārvaldes apgabals Honkonga"
"nl" = "Hongkong SAR van China"
"hu" = "Hongkong KKT"
"no" = "Hongkong SAR Kina"
"pl" = "SRA Hongkong (Chiny)"
"pt-PT" = "Hong Kong, RAE da China"
"ro" = "R.A.S. Hong Kong, China"
"sk" = "Hongkong – OAO Číny"
"sl" = "Posebno upravno območje Ljudske republike Kitajske Hongkong"
"sr" = "САР Хонгконг (Кина)"
"fi" = "Hongkong – Kiinan erityishallintoalue"
"sv" = "Hongkong SAR"
"ru" = "Гонконг (САР)"
"uk" = "Гонконг, ОАР Китаю"
"el" = "Χονγκ Κονγκ ΕΔΠ Κίνας"
"zh-CN" = "中国香港特别行政区"
"zh-TW" = "中國香港特別行政區"
"ja" = "中華人民共和国香港特別行政区"
"ko" = "홍콩(중국 특별행정구)"
"bg" = "Хонконг, САР на Китай"
"cs" = "Hongkong – ZAO Číny"
"mt" = "ir-Reġjun Amministrattiv Speċjali ta’ Hong Kong tar-Repubblika tal-Poplu taċ-Ċina"

[country.slugs]
"ca" = "hong-kong-rae-xina"
"da" = "sar-hongkong"
"de" = "sonderverwaltungsregion-hongkong"
"et" = "hongkongi-erihalduspiirkond"
"en" = "hong-kong-sar-china"
"es" = "rae-de-hong-kong-china"
"fr" = "r-a-s-chinoise-de-hong-kong"
"oc" = "hong-kong"
"lb" = "spezialverwaltungszon-hong-kong"
"ga" = "sainréigiún-riaracháin-hong-cong-daonphoblacht-na-síne"
"hr" = "pup-hong-kong-kina"
"it" = "ras-di-hong-kong"
"lt" = "ypatingasis-administracinis-kinijos-regionas-honkongas"
"lv" = "ķīnas-īpašās-pārvaldes-apgabals-honkonga"
"nl" = "hongkong-sar-van-china"
"hu" = "hongkong-kkt"
"no" = "hongkong-sar-kina"
"pl" = "sra-hongkong-chiny"
"pt-PT" = "hong-kong-rae-da-china"
"ro" = "r-a-s-hong-kong-china"
"sk" = "hongkong-oao-číny"
"sl" = "posebno-upravno-območje-ljudske-republike-kitajske-hongkong"
"sr" = "сар-хонгконг-кина"
"fi" = "hongkong-kiinan-erityishallintoalue"
"sv" = "hongkong-sar"
"ru" = "гонконг-сар"
"uk" = "гонконг-оар-китаю"
"el" = "χονγκ-κονγκ-εδπ-κίνασ"
"zh-CN" = "中国香港特别行政区"
"zh-TW" = "中國香港特別行政區"
"ja" = "中華人民共和国香港特別行政区"
"ko" = "홍콩-중국-특별행정구"
"bg" = "хонконг-сар-на-китай"
"cs" = "hongkong-zao-číny"
"mt" = "ir-reġjun-amministrattiv-speċjali-ta-hong-kong-tar-repubblika-tal-poplu-taċ-ċina"

[country.codes]
gisco_cntr_id = "HK"
iso_3166_1_alpha2 = "HK"
iso_3166_1_alpha3 = "HKG"
