schema_version = 1

[[country]]
id = "HR"
kind = "country"
official_languages = ["hr"]

[country.names]
"ca" = "Croàcia"
"da" = "Kroatien"
"de" = "Kroatien"
"et" = "Horvaatia"
"en" = "Croatia"
"es" = "Croacia"
"fr" = "Croatie"
"oc" = "Croàcia"
"lb" = "Kroatien"
"ga" = "an Chróit"
"hr" = "Hrvatska"
"it" = "Croazia"
"lt" = "Kroatija"
"lv" = "Horvātija"
"nl" = "Kroatië"
"hu" = "Horvátország"
"no" = "Kroatia"
"pl" = "Chorwacja"
"pt-PT" = "Croácia"
"ro" = "Croația"
"sk" = "Chorvátsko"
"sl" = "Hrvaška"
"sr" = "Хрватска"
"fi" = "Kroatia"
"sv" = "Kroatien"
"ru" = "Хорватия"
"uk" = "Хорватія"
"el" = "Κροατία"
"zh-CN" = "克罗地亚"
"zh-TW" = "克羅埃西亞"
"ja" = "クロアチア"
"ko" = "크로아티아"
"bg" = "Хърватия"
"cs" = "Chorvatsko"
"mt" = "il-Kroazja"

[country.slugs]
"ca" = "croàcia"
"da" = "kroatien"
"de" = "kroatien"
"et" = "horvaatia"
"en" = "croatia"
"es" = "croacia"
"fr" = "croatie"
"oc" = "croàcia"
"lb" = "kroatien"
"ga" = "an-chróit"
"hr" = "hrvatska"
"it" = "croazia"
"lt" = "kroatija"
"lv" = "horvātija"
"nl" = "kroatië"
"hu" = "horvátország"
"no" = "kroatia"
"pl" = "chorwacja"
"pt-PT" = "croácia"
"ro" = "croația"
"sk" = "chorvátsko"
"sl" = "hrvaška"
"sr" = "хрватска"
"fi" = "kroatia"
"sv" = "kroatien"
"ru" = "хорватия"
"uk" = "хорватія"
"el" = "κροατία"
"zh-CN" = "克罗地亚"
"zh-TW" = "克羅埃西亞"
"ja" = "クロアチア"
"ko" = "크로아티아"
"bg" = "хърватия"
"cs" = "chorvatsko"
"mt" = "il-kroazja"

[country.codes]
gisco_cntr_id = "HR"
iso_3166_1_alpha2 = "HR"
iso_3166_1_alpha3 = "HRV"
