schema_version = 1

[[country]]
id = "HU"
kind = "country"
official_languages = ["hu"]

[country.names]
"ca" = "Hongria"
"da" = "Ungarn"
"de" = "Ungarn"
"et" = "Ungari"
"en" = "Hungary"
"es" = "Hungría"
"fr" = "Hongrie"
"oc" = "Ongria"
"lb" = "Ungarn"
"ga" = "an Ungáir"
"hr" = "Mađarska"
"it" = "Ungheria"
"lt" = "Vengrija"
"lv" = "Ungārija"
"nl" = "Hongarije"
"hu" = "Magyarország"
"no" = "Ungarn"
"pl" = "Węgry"
"pt-PT" = "Hungria"
"ro" = "Ungaria"
"sk" = "Maďarsko"
"sl" = "Madžarska"
"sr" = "Мађарска"
"fi" = "Unkari"
"sv" = "Ungern"
"ru" = "Венгрия"
"uk" = "Угорщина"
"el" = "Ουγγαρία"
"zh-CN" = "匈牙利"
"zh-TW" = "匈牙利"
"ja" = "ハンガリー"
"ko" = "헝가리"
"bg" = "Унгария"
"cs" = "Maďarsko"
"mt" = "l-Ungerija"

[country.slugs]
"ca" = "hongria"
"da" = "ungarn"
"de" = "ungarn"
"et" = "ungari"
"en" = "hungary"
"es" = "hungría"
"fr" = "hongrie"
"oc" = "ongria"
"lb" = "ungarn"
"ga" = "an-ungáir"
"hr" = "mađarska"
"it" = "ungheria"
"lt" = "vengrija"
"lv" = "ungārija"
"nl" = "hongarije"
"hu" = "magyarország"
"no" = "ungarn"
"pl" = "węgry"
"pt-PT" = "hungria"
"ro" = "ungaria"
"sk" = "maďarsko"
"sl" = "madžarska"
"sr" = "мађарска"
"fi" = "unkari"
"sv" = "ungern"
"ru" = "венгрия"
"uk" = "угорщина"
"el" = "ουγγαρία"
"zh-CN" = "匈牙利"
"zh-TW" = "匈牙利"
"ja" = "ハンガリー"
"ko" = "헝가리"
"bg" = "унгария"
"cs" = "maďarsko"
"mt" = "l-ungerija"

[country.codes]
gisco_cntr_id = "HU"
iso_3166_1_alpha2 = "HU"
iso_3166_1_alpha3 = "HUN"
