schema_version = 1

[[country]]
id = "ID"
kind = "country"
official_languages = ["id"]

[country.names]
"ca" = "Indonèsia"
"da" = "Indonesien"
"de" = "Indonesien"
"et" = "Indoneesia"
"en" = "Indonesia"
"es" = "Indonesia"
"fr" = "Indonésie"
"oc" = "Indonesia"
"lb" = "Indonesien"
"ga" = "an Indinéis"
"hr" = "Indonezija"
"it" = "Indonesia"
"lt" = "Indonezija"
"lv" = "Indonēzija"
"nl" = "Indonesië"
"hu" = "Indonézia"
"no" = "Indonesia"
"pl" = "Indonezja"
"pt-PT" = "Indonésia"
"ro" = "Indonezia"
"sk" = "Indonézia"
"sl" = "Indonezija"
"sr" = "Индонезија"
"fi" = "Indonesia"
"sv" = "Indonesien"
"ru" = "Индонезия"
"uk" = "Індонезія"
"el" = "Ινδονησία"
"zh-CN" = "印度尼西亚"
"zh-TW" = "印尼"
"ja" = "インドネシア"
"ko" = "인도네시아"
"bg" = "Индонезия"
"cs" = "Indonésie"
"mt" = "l-Indoneżja"
"id" = "Indonesia"

[country.slugs]
"ca" = "indonèsia"
"da" = "indonesien"
"de" = "indonesien"
"et" = "indoneesia"
"en" = "indonesia"
"es" = "indonesia"
"fr" = "indonésie"
"oc" = "indonesia"
"lb" = "indonesien"
"ga" = "an-indinéis"
"hr" = "indonezija"
"it" = "indonesia"
"lt" = "indonezija"
"lv" = "indonēzija"
"nl" = "indonesië"
"hu" = "indonézia"
"no" = "indonesia"
"pl" = "indonezja"
"pt-PT" = "indonésia"
"ro" = "indonezia"
"sk" = "indonézia"
"sl" = "indonezija"
"sr" = "индонезија"
"fi" = "indonesia"
"sv" = "indonesien"
"ru" = "индонезия"
"uk" = "індонезія"
"el" = "ινδονησία"
"zh-CN" = "印度尼西亚"
"zh-TW" = "印尼"
"ja" = "インドネシア"
"ko" = "인도네시아"
"bg" = "индонезия"
"cs" = "indonésie"
"mt" = "l-indoneżja"

[country.codes]
gisco_cntr_id = "ID"
iso_3166_1_alpha2 = "ID"
iso_3166_1_alpha3 = "IDN"
