schema_version = 1

[[country]]
id = "IE"
kind = "country"
official_languages = ["ga", "en"]

[country.names]
"ca" = "Irlanda"
"da" = "Irland"
"de" = "Irland"
"et" = "Iirimaa"
"en" = "Ireland"
"es" = "Irlanda"
"fr" = "Irlande"
"oc" = "Irlanda"
"lb" = "Irland"
"ga" = "Éire"
"hr" = "Irska"
"it" = "Irlanda"
"lt" = "Airija"
"lv" = "Īrija"
"nl" = "Ierland"
"hu" = "Írország"
"no" = "Irland"
"pl" = "Irlandia"
"pt-PT" = "Irlanda"
"ro" = "Irlanda"
"sk" = "Írsko"
"sl" = "Irska"
"sr" = "Ирска"
"fi" = "Irlanti"
"sv" = "Irland"
"ru" = "Ирландия"
"uk" = "Ірландія"
"el" = "Ιρλανδία"
"zh-CN" = "爱尔兰"
"zh-TW" = "愛爾蘭"
"ja" = "アイルランド"
"ko" = "아일랜드"
"bg" = "Ирландия"
"cs" = "Irsko"
"mt" = "l-Irlanda"

[country.slugs]
"ca" = "irlanda"
"da" = "irland"
"de" = "irland"
"et" = "iirimaa"
"en" = "ireland"
"es" = "irlanda"
"fr" = "irlande"
"oc" = "irlanda"
"lb" = "irland"
"ga" = "éire"
"hr" = "irska"
"it" = "irlanda"
"lt" = "airija"
"lv" = "īrija"
"nl" = "ierland"
"hu" = "írország"
"no" = "irland"
"pl" = "irlandia"
"pt-PT" = "irlanda"
"ro" = "irlanda"
"sk" = "írsko"
"sl" = "irska"
"sr" = "ирска"
"fi" = "irlanti"
"sv" = "irland"
"ru" = "ирландия"
"uk" = "ірландія"
"el" = "ιρλανδία"
"zh-CN" = "爱尔兰"
"zh-TW" = "愛爾蘭"
"ja" = "アイルランド"
"ko" = "아일랜드"
"bg" = "ирландия"
"cs" = "irsko"
"mt" = "l-irlanda"

[country.codes]
gisco_cntr_id = "IE"
iso_3166_1_alpha2 = "IE"
iso_3166_1_alpha3 = "IRL"
