schema_version = 1

[[country]]
id = "IN"
kind = "country"
official_languages = ["hi", "en"]

[country.names]
"ca" = "Índia"
"da" = "Indien"
"de" = "Indien"
"et" = "India"
"en" = "India"
"es" = "India"
"fr" = "Inde"
"oc" = "Índia"
"lb" = "Indien"
"ga" = "an India"
"hr" = "Indija"
"it" = "India"
"lt" = "Indija"
"lv" = "Indija"
"nl" = "India"
"hu" = "India"
"no" = "India"
"pl" = "Indie"
"pt-PT" = "Índia"
"ro" = "India"
"sk" = "India"
"sl" = "Indija"
"sr" = "Индија"
"fi" = "Intia"
"sv" = "Indien"
"ru" = "Индия"
"uk" = "Індія"
"el" = "Ινδία"
"zh-CN" = "印度"
"zh-TW" = "印度"
"ja" = "インド"
"ko" = "인도"
"bg" = "Индия"
"cs" = "Indie"
"mt" = "l-Indja"
"hi" = "भारत"

[country.slugs]
"ca" = "índia"
"da" = "indien"
"de" = "indien"
"et" = "india"
"en" = "india"
"es" = "india"
"fr" = "inde"
"oc" = "índia"
"lb" = "indien"
"ga" = "an-india"
"hr" = "indija"
"it" = "india"
"lt" = "indija"
"lv" = "indija"
"nl" = "india"
"hu" = "india"
"no" = "india"
"pl" = "indie"
"pt-PT" = "índia"
"ro" = "india"
"sk" = "india"
"sl" = "indija"
"sr" = "индија"
"fi" = "intia"
"sv" = "indien"
"ru" = "индия"
"uk" = "індія"
"el" = "ινδία"
"zh-CN" = "印度"
"zh-TW" = "印度"
"ja" = "インド"
"ko" = "인도"
"bg" = "индия"
"cs" = "indie"
"mt" = "l-indja"

[country.codes]
gisco_cntr_id = "IN"
iso_3166_1_alpha2 = "IN"
iso_3166_1_alpha3 = "IND"
