schema_version = 1

[[country]]
id = "IS"
kind = "country"
official_languages = ["is"]

[country.names]
"ca" = "Islàndia"
"da" = "Island"
"de" = "Island"
"et" = "Island"
"en" = "Iceland"
"es" = "Islandia"
"fr" = "Islande"
"oc" = "Islàndia"
"lb" = "Island"
"ga" = "an Íoslainn"
"hr" = "Island"
"it" = "Islanda"
"lt" = "Islandija"
"lv" = "Islande"
"nl" = "IJsland"
"hu" = "Izland"
"no" = "Island"
"pl" = "Islandia"
"pt-PT" = "Islândia"
"ro" = "Islanda"
"sk" = "Island"
"sl" = "Islandija"
"sr" = "Исланд"
"fi" = "Islanti"
"sv" = "Island"
"ru" = "Исландия"
"uk" = "Ісландія"
"el" = "Ισλανδία"
"zh-CN" = "冰岛"
"zh-TW" = "冰島"
"ja" = "アイスランド"
"ko" = "아이슬란드"
"bg" = "Исландия"
"cs" = "Island"
"mt" = "l-Iżlanda"
"is" = "Ísland"

[country.slugs]
"ca" = "islàndia"
"da" = "island"
"de" = "island"
"et" = "island"
"en" = "iceland"
"es" = "islandia"
"fr" = "islande"
"oc" = "islàndia"
"lb" = "island"
"ga" = "an-íoslainn"
"hr" = "island"
"it" = "islanda"
"lt" = "islandija"
"lv" = "islande"
"nl" = "ijsland"
"hu" = "izland"
"no" = "island"
"pl" = "islandia"
"pt-PT" = "islândia"
"ro" = "islanda"
"sk" = "island"
"sl" = "islandija"
"sr" = "исланд"
"fi" = "islanti"
"sv" = "island"
"ru" = "исландия"
"uk" = "ісландія"
"el" = "ισλανδία"
"zh-CN" = "冰岛"
"zh-TW" = "冰島"
"ja" = "アイスランド"
"ko" = "아이슬란드"
"bg" = "исландия"
"cs" = "island"
"mt" = "l-iżlanda"

[country.codes]
gisco_cntr_id = "IS"
iso_3166_1_alpha2 = "IS"
iso_3166_1_alpha3 = "ISL"
