schema_version = 1

[[country]]
id = "IT"
kind = "country"
official_languages = ["it"]

[country.names]
"ca" = "Itàlia"
"da" = "Italien"
"de" = "Italien"
"et" = "Itaalia"
"en" = "Italy"
"es" = "Italia"
"fr" = "Italie"
"oc" = "Itàlia"
"lb" = "Italien"
"ga" = "an Iodáil"
"hr" = "Italija"
"it" = "Italia"
"lt" = "Italija"
"lv" = "Itālija"
"nl" = "Italië"
"hu" = "Olaszország"
"no" = "Italia"
"pl" = "Włochy"
"pt-PT" = "Itália"
"ro" = "Italia"
"sk" = "Taliansko"
"sl" = "Italija"
"sr" = "Италија"
"fi" = "Italia"
"sv" = "Italien"
"ru" = "Италия"
"uk" = "Італія"
"el" = "Ιταλία"
"zh-CN" = "意大利"
"zh-TW" = "義大利"
"ja" = "イタリア"
"ko" = "이탈리아"
"bg" = "Италия"
"cs" = "Itálie"
"mt" = "l-Italja"

[country.slugs]
"ca" = "itàlia"
"da" = "italien"
"de" = "italien"
"et" = "itaalia"
"en" = "italy"
"es" = "italia"
"fr" = "italie"
"oc" = "itàlia"
"lb" = "italien"
"ga" = "an-iodáil"
"hr" = "italija"
"it" = "italia"
"lt" = "italija"
"lv" = "itālija"
"nl" = "italië"
"hu" = "olaszország"
"no" = "italia"
"pl" = "włochy"
"pt-PT" = "itália"
"ro" = "italia"
"sk" = "taliansko"
"sl" = "italija"
"sr" = "италија"
"fi" = "italia"
"sv" = "italien"
"ru" = "италия"
"uk" = "італія"
"el" = "ιταλία"
"zh-CN" = "意大利"
"zh-TW" = "義大利"
"ja" = "イタリア"
"ko" = "이탈리아"
"bg" = "италия"
"cs" = "itálie"
"mt" = "l-italja"

[country.codes]
gisco_cntr_id = "IT"
iso_3166_1_alpha2 = "IT"
iso_3166_1_alpha3 = "ITA"
