schema_version = 1

[[country]]
id = "JP"
kind = "country"
official_languages = ["ja"]

[country.names]
"ca" = "Japó"
"da" = "Japan"
"de" = "Japan"
"et" = "Jaapan"
"en" = "Japan"
"es" = "Japón"
"fr" = "Japon"
"oc" = "Japon"
"lb" = "Japan"
"ga" = "an tSeapáin"
"hr" = "Japan"
"it" = "Giappone"
"lt" = "Japonija"
"lv" = "Japāna"
"nl" = "Japan"
"hu" = "Japán"
"no" = "Japan"
"pl" = "Japonia"
"pt-PT" = "Japão"
"ro" = "Japonia"
"sk" = "Japonsko"
"sl" = "Japonska"
"sr" = "Јапан"
"fi" = "Japani"
"sv" = "Japan"
"ru" = "Япония"
"uk" = "Японія"
"el" = "Ιαπωνία"
"zh-CN" = "日本"
"zh-TW" = "日本"
"ja" = "日本"
"ko" = "일본"
"bg" = "Япония"
"cs" = "Japonsko"
"mt" = "il-Ġappun"

[country.slugs]
"ca" = "japó"
"da" = "japan"
"de" = "japan"
"et" = "jaapan"
"en" = "japan"
"es" = "japón"
"fr" = "japon"
"oc" = "japon"
"lb" = "japan"
"ga" = "an-tseapáin"
"hr" = "japan"
"it" = "giappone"
"lt" = "japonija"
"lv" = "japāna"
"nl" = "japan"
"hu" = "japán"
"no" = "japan"
"pl" = "japonia"
"pt-PT" = "japão"
"ro" = "japonia"
"sk" = "japonsko"
"sl" = "japonska"
"sr" = "јапан"
"fi" = "japani"
"sv" = "japan"
"ru" = "япония"
"uk" = "японія"
"el" = "ιαπωνία"
"zh-CN" = "日本"
"zh-TW" = "日本"
"ja" = "日本"
"ko" = "일본"
"bg" = "япония"
"cs" = "japonsko"
"mt" = "il-ġappun"

[country.codes]
gisco_cntr_id = "JP"
iso_3166_1_alpha2 = "JP"
iso_3166_1_alpha3 = "JPN"
