schema_version = 1

[[country]]
id = "KR"
kind = "country"
official_languages = ["ko"]

[country.names]
"ca" = "Corea del Sud"
"da" = "Sydkorea"
"de" = "Südkorea"
"et" = "Lõuna-Korea"
"en" = "South Korea"
"es" = "Corea del Sur"
"fr" = "Corée du Sud"
"oc" = "Corèa del Sud"
"lb" = "Südkorea"
"ga" = "an Chóiré Theas"
"hr" = "Južna Koreja"
"it" = "Corea del Sud"
"lt" = "Pietų Korėja"
"lv" = "Dienvidkoreja"
"nl" = "Zuid-Korea"
"hu" = "Dél-Korea"
"no" = "Sør-Korea"
"pl" = "Korea Południowa"
"pt-PT" = "Coreia do Sul"
"ro" = "Coreea de Sud"
"sk" = "Južná Kórea"
"sl" = "Južna Koreja"
"sr" = "Јужна Кореја"
"fi" = "Etelä-Korea"
"sv" = "Sydkorea"
"ru" = "Республика Корея"
"uk" = "Південна Корея"
"el" = "Νότια Κορέα"
"zh-CN" = "韩国"
"zh-TW" = "南韓"
"ja" = "韓国"
"ko" = "대한민국"
"bg" = "Южна Корея"
"cs" = "Jižní Korea"
"mt" = "il-Korea t’Isfel"

[country.slugs]
"ca" = "corea-del-sud"
"da" = "sydkorea"
"de" = "südkorea"
"et" = "lõuna-korea"
"en" = "south-korea"
"es" = "corea-del-sur"
"fr" = "corée-du-sud"
"oc" = "corèa-del-sud"
"lb" = "südkorea"
"ga" = "an-chóiré-theas"
"hr" = "južna-koreja"
"it" = "corea-del-sud"
"lt" = "pietų-korėja"
"lv" = "dienvidkoreja"
"nl" = "zuid-korea"
"hu" = "dél-korea"
"no" = "sør-korea"
"pl" = "korea-południowa"
"pt-PT" = "coreia-do-sul"
"ro" = "coreea-de-sud"
"sk" = "južná-kórea"
"sl" = "južna-koreja"
"sr" = "јужна-кореја"
"fi" = "etelä-korea"
"sv" = "sydkorea"
"ru" = "республика-корея"
"uk" = "південна-корея"
"el" = "νότια-κορέα"
"zh-CN" = "韩国"
"zh-TW" = "南韓"
"ja" = "韓国"
"ko" = "대한민국"
"bg" = "южна-корея"
"cs" = "jižní-korea"
"mt" = "il-korea-tisfel"

[country.codes]
gisco_cntr_id = "KR"
iso_3166_1_alpha2 = "KR"
iso_3166_1_alpha3 = "KOR"
