schema_version = 1

[[country]]
id = "LA"
kind = "country"
official_languages = ["lo"]

[country.names]
"ca" = "Lao"
"da" = "Laos"
"de" = "Laos"
"et" = "Laos"
"en" = "Laos"
"es" = "Laos"
"fr" = "Laos"
"oc" = "Laos"
"lb" = "Laos"
"ga" = "Laos"
"hr" = "Laos"
"it" = "Laos"
"lt" = "Laosas"
"lv" = "Laosa"
"nl" = "Laos"
"hu" = "Laosz"
"no" = "Laos"
"pl" = "Laos"
"pt-PT" = "Laos"
"ro" = "Laos"
"sk" = "Laos"
"sl" = "Laos"
"sr" = "Лаос"
"fi" = "Laos"
"sv" = "Laos"
"ru" = "Лаос"
"uk" = "Лаос"
"el" = "Λάος"
"zh-CN" = "老挝"
"zh-TW" = "寮國"
"ja" = "ラオス"
"ko" = "라오스"
"bg" = "Лаос"
"cs" = "Laos"
"mt" = "il-Laos"
"lo" = "ລາວ"

[country.slugs]
"ca" = "lao"
"da" = "laos"
"de" = "laos"
"et" = "laos"
"en" = "laos"
"es" = "laos"
"fr" = "laos"
"oc" = "laos"
"lb" = "laos"
"ga" = "laos"
"hr" = "laos"
"it" = "laos"
"lt" = "laosas"
"lv" = "laosa"
"nl" = "laos"
"hu" = "laosz"
"no" = "laos"
"pl" = "laos"
"pt-PT" = "laos"
"ro" = "laos"
"sk" = "laos"
"sl" = "laos"
"sr" = "лаос"
"fi" = "laos"
"sv" = "laos"
"ru" = "лаос"
"uk" = "лаос"
"el" = "λάοσ"
"zh-CN" = "老挝"
"zh-TW" = "寮國"
"ja" = "ラオス"
"ko" = "라오스"
"bg" = "лаос"
"cs" = "laos"
"mt" = "il-laos"

[country.codes]
gisco_cntr_id = "LA"
iso_3166_1_alpha2 = "LA"
iso_3166_1_alpha3 = "LAO"
