schema_version = 1

[[country]]
id = "LI"
kind = "country"
official_languages = ["de"]

[country.names]
"ca" = "Liechtenstein"
"da" = "Liechtenstein"
"de" = "Liechtenstein"
"et" = "Liechtenstein"
"en" = "Liechtenstein"
"es" = "Liechtenstein"
"fr" = "Liechtenstein"
"oc" = "Liechtenstein"
"lb" = "Liechtenstein"
"ga" = "Lichtinstéin"
"hr" = "Lihtenštajn"
"it" = "Liechtenstein"
"lt" = "Lichtenšteinas"
"lv" = "Lihtenšteina"
"nl" = "Liechtenstein"
"hu" = "Liechtenstein"
"no" = "Liechtenstein"
"pl" = "Liechtenstein"
"pt-PT" = "Listenstaine"
"ro" = "Liechtenstein"
"sk" = "Lichtenštajnsko"
"sl" = "Lihtenštajn"
"sr" = "Лихтенштајн"
"fi" = "Liechtenstein"
"sv" = "Liechtenstein"
"ru" = "Лихтенштейн"
"uk" = "Ліхтенштейн"
"el" = "Λιχτενστάιν"
"zh-CN" = "列支敦士登"
"zh-TW" = "列支敦斯登"
"ja" = "リヒテンシュタイン"
"ko" = "리히텐슈타인"
"bg" = "Лихтенщайн"
"cs" = "Lichtenštejnsko"
"mt" = "il-Liechtenstein"

[country.slugs]
"ca" = "liechtenstein"
"da" = "liechtenstein"
"de" = "liechtenstein"
"et" = "liechtenstein"
"en" = "liechtenstein"
"es" = "liechtenstein"
"fr" = "liechtenstein"
"oc" = "liechtenstein"
"lb" = "liechtenstein"
"ga" = "lichtinstéin"
"hr" = "lihtenštajn"
"it" = "liechtenstein"
"lt" = "lichtenšteinas"
"lv" = "lihtenšteina"
"nl" = "liechtenstein"
"hu" = "liechtenstein"
"no" = "liechtenstein"
"pl" = "liechtenstein"
"pt-PT" = "listenstaine"
"ro" = "liechtenstein"
"sk" = "lichtenštajnsko"
"sl" = "lihtenštajn"
"sr" = "лихтенштајн"
"fi" = "liechtenstein"
"sv" = "liechtenstein"
"ru" = "лихтенштейн"
"uk" = "ліхтенштейн"
"el" = "λιχτενστάιν"
"zh-CN" = "列支敦士登"
"zh-TW" = "列支敦斯登"
"ja" = "リヒテンシュタイン"
"ko" = "리히텐슈타인"
"bg" = "лихтенщайн"
"cs" = "lichtenštejnsko"
"mt" = "il-liechtenstein"

[country.codes]
gisco_cntr_id = "LI"
iso_3166_1_alpha2 = "LI"
iso_3166_1_alpha3 = "LIE"
