schema_version = 1

[[country]]
id = "LK"
kind = "country"
official_languages = ["si", "ta"]

[country.names]
"ca" = "Sri Lanka"
"da" = "Sri Lanka"
"de" = "Sri Lanka"
"et" = "Sri Lanka"
"en" = "Sri Lanka"
"es" = "Sri Lanka"
"fr" = "Sri Lanka"
"oc" = "Sri Lanka"
"lb" = "Sri Lanka"
"ga" = "Srí Lanca"
"hr" = "Šri Lanka"
"it" = "Sri Lanka"
"lt" = "Šri Lanka"
"lv" = "Šrilanka"
"nl" = "Sri Lanka"
"hu" = "Srí Lanka"
"no" = "Sri Lanka"
"pl" = "Sri Lanka"
"pt-PT" = "Sri Lanca"
"ro" = "Sri Lanka"
"sk" = "Srí Lanka"
"sl" = "Šrilanka"
"sr" = "Шри Ланка"
"fi" = "Sri Lanka"
"sv" = "Sri Lanka"
"ru" = "Шри-Ланка"
"uk" = "Шрі-Ланка"
"el" = "Σρι Λάνκα"
"zh-CN" = "斯里兰卡"
"zh-TW" = "斯里蘭卡"
"ja" = "スリランカ"
"ko" = "스리랑카"
"bg" = "Шри Ланка"
"cs" = "Srí Lanka"
"mt" = "is-Sri Lanka"
"si" = "ශ්‍රී ලංකාව"
"ta" = "இலங்கை"

[country.slugs]
"ca" = "sri-lanka"
"da" = "sri-lanka"
"de" = "sri-lanka"
"et" = "sri-lanka"
"en" = "sri-lanka"
"es" = "sri-lanka"
"fr" = "sri-lanka"
"oc" = "sri-lanka"
"lb" = "sri-lanka"
"ga" = "srí-lanca"
"hr" = "šri-lanka"
"it" = "sri-lanka"
"lt" = "šri-lanka"
"lv" = "šrilanka"
"nl" = "sri-lanka"
"hu" = "srí-lanka"
"no" = "sri-lanka"
"pl" = "sri-lanka"
"pt-PT" = "sri-lanca"
"ro" = "sri-lanka"
"sk" = "srí-lanka"
"sl" = "šrilanka"
"sr" = "шри-ланка"
"fi" = "sri-lanka"
"sv" = "sri-lanka"
"ru" = "шри-ланка"
"uk" = "шрі-ланка"
"el" = "σρι-λάνκα"
"zh-CN" = "斯里兰卡"
"zh-TW" = "斯里蘭卡"
"ja" = "スリランカ"
"ko" = "스리랑카"
"bg" = "шри-ланка"
"cs" = "srí-lanka"
"mt" = "is-sri-lanka"

[country.codes]
gisco_cntr_id = "LK"
iso_3166_1_alpha2 = "LK"
iso_3166_1_alpha3 = "LKA"
