schema_version = 1

[[country]]
id = "LT"
kind = "country"
official_languages = ["lt"]

[country.names]
"ca" = "Lituània"
"da" = "Litauen"
"de" = "Litauen"
"et" = "Leedu"
"en" = "Lithuania"
"es" = "Lituania"
"fr" = "Lituanie"
"oc" = "Lituània"
"lb" = "Litauen"
"ga" = "an Liotuáin"
"hr" = "Litva"
"it" = "Lituania"
"lt" = "Lietuva"
"lv" = "Lietuva"
"nl" = "Litouwen"
"hu" = "Litvánia"
"no" = "Litauen"
"pl" = "Litwa"
"pt-PT" = "Lituânia"
"ro" = "Lituania"
"sk" = "Litva"
"sl" = "Litva"
"sr" = "Литванија"
"fi" = "Liettua"
"sv" = "Litauen"
"ru" = "Литва"
"uk" = "Литва"
"el" = "Λιθουανία"
"zh-CN" = "立陶宛"
"zh-TW" = "立陶宛"
"ja" = "リトアニア"
"ko" = "리투아니아"
"bg" = "Литва"
"cs" = "Litva"
"mt" = "il-Litwanja"

[country.slugs]
"ca" = "lituània"
"da" = "litauen"
"de" = "litauen"
"et" = "leedu"
"en" = "lithuania"
"es" = "lituania"
"fr" = "lituanie"
"oc" = "lituània"
"lb" = "litauen"
"ga" = "an-liotuáin"
"hr" = "litva"
"it" = "lituania"
"lt" = "lietuva"
"lv" = "lietuva"
"nl" = "litouwen"
"hu" = "litvánia"
"no" = "litauen"
"pl" = "litwa"
"pt-PT" = "lituânia"
"ro" = "lituania"
"sk" = "litva"
"sl" = "litva"
"sr" = "литванија"
"fi" = "liettua"
"sv" = "litauen"
"ru" = "литва"
"uk" = "литва"
"el" = "λιθουανία"
"zh-CN" = "立陶宛"
"zh-TW" = "立陶宛"
"ja" = "リトアニア"
"ko" = "리투아니아"
"bg" = "литва"
"cs" = "litva"
"mt" = "il-litwanja"

[country.codes]
gisco_cntr_id = "LT"
iso_3166_1_alpha2 = "LT"
iso_3166_1_alpha3 = "LTU"
