schema_version = 1

[[country]]
id = "LU"
kind = "country"
official_languages = ["lb", "fr", "de"]

[country.names]
"ca" = "Luxemburg"
"da" = "Luxembourg"
"de" = "Luxemburg"
"et" = "Luksemburg"
"en" = "Luxembourg"
"es" = "Luxemburgo"
"fr" = "Luxembourg"
"oc" = "Luxemborg"
"lb" = "Lëtzebuerg"
"ga" = "Lucsamburg"
"hr" = "Luksemburg"
"it" = "Lussemburgo"
"lt" = "Liuksemburgas"
"lv" = "Luksemburga"
"nl" = "Luxemburg"
"hu" = "Luxemburg"
"no" = "Luxemburg"
"pl" = "Luksemburg"
"pt-PT" = "Luxemburgo"
"ro" = "Luxemburg"
"sk" = "Luxembursko"
"sl" = "Luksemburg"
"sr" = "Луксембург"
"fi" = "Luxemburg"
"sv" = "Luxemburg"
"ru" = "Люксембург"
"uk" = "Люксембург"
"el" = "Λουξεμβούργο"
"zh-CN" = "卢森堡"
"zh-TW" = "盧森堡"
"ja" = "ルクセンブルク"
"ko" = "룩셈부르크"
"bg" = "Люксембург"
"cs" = "Lucembursko"
"mt" = "il-Lussemburgu"

[country.slugs]
"ca" = "luxemburg"
"da" = "luxembourg"
"de" = "luxemburg"
"et" = "luksemburg"
"en" = "luxembourg"
"es" = "luxemburgo"
"fr" = "luxembourg"
"oc" = "luxemborg"
"lb" = "lëtzebuerg"
"ga" = "lucsamburg"
"hr" = "luksemburg"
"it" = "lussemburgo"
"lt" = "liuksemburgas"
"lv" = "luksemburga"
"nl" = "luxemburg"
"hu" = "luxemburg"
"no" = "luxemburg"
"pl" = "luksemburg"
"pt-PT" = "luxemburgo"
"ro" = "luxemburg"
"sk" = "luxembursko"
"sl" = "luksemburg"
"sr" = "луксембург"
"fi" = "luxemburg"
"sv" = "luxemburg"
"ru" = "люксембург"
"uk" = "люксембург"
"el" = "λουξεμβούργο"
"zh-CN" = "卢森堡"
"zh-TW" = "盧森堡"
"ja" = "ルクセンブルク"
"ko" = "룩셈부르크"
"bg" = "люксембург"
"cs" = "lucembursko"
"mt" = "il-lussemburgu"

[country.codes]
gisco_cntr_id = "LU"
iso_3166_1_alpha2 = "LU"
iso_3166_1_alpha3 = "LUX"
