schema_version = 1

[[country]]
id = "LV"
kind = "country"
official_languages = ["lv"]

[country.names]
"ca" = "Letònia"
"da" = "Letland"
"de" = "Lettland"
"et" = "Läti"
"en" = "Latvia"
"es" = "Letonia"
"fr" = "Lettonie"
"oc" = "Letònia"
"lb" = "Lettland"
"ga" = "an Laitvia"
"hr" = "Latvija"
"it" = "Lettonia"
"lt" = "Latvija"
"lv" = "Latvija"
"nl" = "Letland"
"hu" = "Lettország"
"no" = "Latvia"
"pl" = "Łotwa"
"pt-PT" = "Letónia"
"ro" = "Letonia"
"sk" = "Lotyšsko"
"sl" = "Latvija"
"sr" = "Летонија"
"fi" = "Latvia"
"sv" = "Lettland"
"ru" = "Латвия"
"uk" = "Латвія"
"el" = "Λετονία"
"zh-CN" = "拉脱维亚"
"zh-TW" = "拉脫維亞"
"ja" = "ラトビア"
"ko" = "라트비아"
"bg" = "Латвия"
"cs" = "Lotyšsko"
"mt" = "il-Latvja"

[country.slugs]
"ca" = "letònia"
"da" = "letland"
"de" = "lettland"
"et" = "läti"
"en" = "latvia"
"es" = "letonia"
"fr" = "lettonie"
"oc" = "letònia"
"lb" = "lettland"
"ga" = "an-laitvia"
"hr" = "latvija"
"it" = "lettonia"
"lt" = "latvija"
"lv" = "latvija"
"nl" = "letland"
"hu" = "lettország"
"no" = "latvia"
"pl" = "łotwa"
"pt-PT" = "letónia"
"ro" = "letonia"
"sk" = "lotyšsko"
"sl" = "latvija"
"sr" = "летонија"
"fi" = "latvia"
"sv" = "lettland"
"ru" = "латвия"
"uk" = "латвія"
"el" = "λετονία"
"zh-CN" = "拉脱维亚"
"zh-TW" = "拉脫維亞"
"ja" = "ラトビア"
"ko" = "라트비아"
"bg" = "латвия"
"cs" = "lotyšsko"
"mt" = "il-latvja"

[country.codes]
gisco_cntr_id = "LV"
iso_3166_1_alpha2 = "LV"
iso_3166_1_alpha3 = "LVA"
