schema_version = 1

[[country]]
id = "MC"
kind = "country"
official_languages = ["fr"]

[country.names]
"ca" = "Mònaco"
"da" = "Monaco"
"de" = "Monaco"
"et" = "Monaco"
"en" = "Monaco"
"es" = "Mónaco"
"fr" = "Monaco"
"oc" = "Mónegue"
"lb" = "Monaco"
"ga" = "Monacó"
"hr" = "Monako"
"it" = "Monaco"
"lt" = "Monakas"
"lv" = "Monako"
"nl" = "Monaco"
"hu" = "Monaco"
"no" = "Monaco"
"pl" = "Monako"
"pt-PT" = "Mónaco"
"ro" = "Monaco"
"sk" = "Monako"
"sl" = "Monako"
"sr" = "Монако"
"fi" = "Monaco"
"sv" = "Monaco"
"ru" = "Монако"
"uk" = "Монако"
"el" = "Μονακό"
"zh-CN" = "摩纳哥"
"zh-TW" = "摩納哥"
"ja" = "モナコ"
"ko" = "모나코"
"bg" = "Монако"
"cs" = "Monako"
"mt" = "Monaco"

[country.slugs]
"ca" = "mònaco"
"da" = "monaco"
"de" = "monaco"
"et" = "monaco"
"en" = "monaco"
"es" = "mónaco"
"fr" = "monaco"
"oc" = "mónegue"
"lb" = "monaco"
"ga" = "monacó"
"hr" = "monako"
"it" = "monaco"
"lt" = "monakas"
"lv" = "monako"
"nl" = "monaco"
"hu" = "monaco"
"no" = "monaco"
"pl" = "monako"
"pt-PT" = "mónaco"
"ro" = "monaco"
"sk" = "monako"
"sl" = "monako"
"sr" = "монако"
"fi" = "monaco"
"sv" = "monaco"
"ru" = "монако"
"uk" = "монако"
"el" = "μονακό"
"zh-CN" = "摩纳哥"
"zh-TW" = "摩納哥"
"ja" = "モナコ"
"ko" = "모나코"
"bg" = "монако"
"cs" = "monako"
"mt" = "monaco"

[country.codes]
gisco_cntr_id = "MC"
iso_3166_1_alpha2 = "MC"
iso_3166_1_alpha3 = "MCO"
