schema_version = 1

[[country]]
id = "MD"
kind = "country"
official_languages = ["ro"]

[country.names]
"ca" = "Moldàvia"
"da" = "Moldova"
"de" = "Republik Moldau"
"et" = "Moldova"
"en" = "Moldova"
"es" = "Moldavia"
"fr" = "Moldavie"
"oc" = "Moldàvia"
"lb" = "Moldawien"
"ga" = "an Mholdóiv"
"hr" = "Moldavija"
"it" = "Moldavia"
"lt" = "Moldova"
"lv" = "Moldova"
"nl" = "Moldavië"
"hu" = "Moldova"
"no" = "Moldova"
"pl" = "Mołdawia"
"pt-PT" = "Moldávia"
"ro" = "Republica Moldova"
"sk" = "Moldavsko"
"sl" = "Moldavija"
"sr" = "Молдавија"
"fi" = "Moldova"
"sv" = "Moldavien"
"ru" = "Молдова"
"uk" = "Молдова"
"el" = "Μολδαβία"
"zh-CN" = "摩尔多瓦"
"zh-TW" = "摩爾多瓦"
"ja" = "モルドバ"
"ko" = "몰도바"
"bg" = "Молдова"
"cs" = "Moldavsko"
"mt" = "il-Moldova"

[country.slugs]
"ca" = "moldàvia"
"da" = "moldova"
"de" = "republik-moldau"
"et" = "moldova"
"en" = "moldova"
"es" = "moldavia"
"fr" = "moldavie"
"oc" = "moldàvia"
"lb" = "moldawien"
"ga" = "an-mholdóiv"
"hr" = "moldavija"
"it" = "moldavia"
"lt" = "moldova"
"lv" = "moldova"
"nl" = "moldavië"
"hu" = "moldova"
"no" = "moldova"
"pl" = "mołdawia"
"pt-PT" = "moldávia"
"ro" = "republica-moldova"
"sk" = "moldavsko"
"sl" = "moldavija"
"sr" = "молдавија"
"fi" = "moldova"
"sv" = "moldavien"
"ru" = "молдова"
"uk" = "молдова"
"el" = "μολδαβία"
"zh-CN" = "摩尔多瓦"
"zh-TW" = "摩爾多瓦"
"ja" = "モルドバ"
"ko" = "몰도바"
"bg" = "молдова"
"cs" = "moldavsko"
"mt" = "il-moldova"

[country.codes]
gisco_cntr_id = "MD"
iso_3166_1_alpha2 = "MD"
iso_3166_1_alpha3 = "MDA"
