schema_version = 1

[[country]]
id = "ME"
kind = "country"
official_languages = ["cnr"]

[country.names]
"ca" = "Montenegro"
"da" = "Montenegro"
"de" = "Montenegro"
"et" = "Montenegro"
"en" = "Montenegro"
"es" = "Montenegro"
"fr" = "Monténégro"
"oc" = "Montenegro"
"lb" = "Montenegro"
"ga" = "Montainéagró"
"hr" = "Crna Gora"
"it" = "Montenegro"
"lt" = "Juodkalnija"
"lv" = "Melnkalne"
"nl" = "Montenegro"
"hu" = "Montenegró"
"no" = "Montenegro"
"pl" = "Czarnogóra"
"pt-PT" = "Montenegro"
"ro" = "Muntenegru"
"sk" = "Čierna Hora"
"sl" = "Črna gora"
"sr" = "Црна Гора"
"fi" = "Montenegro"
"sv" = "Montenegro"
"ru" = "Черногория"
"uk" = "Чорногорія"
"el" = "Μαυροβούνιο"
"zh-CN" = "黑山"
"zh-TW" = "蒙特內哥羅"
"ja" = "モンテネグロ"
"ko" = "몬테네그로"
"bg" = "Черна гора"
"cs" = "Černá Hora"
"mt" = "il-Montenegro"
"cnr" = "Crna Gora"

[country.slugs]
"ca" = "montenegro"
"da" = "montenegro"
"de" = "montenegro"
"et" = "montenegro"
"en" = "montenegro"
"es" = "montenegro"
"fr" = "monténégro"
"oc" = "montenegro"
"lb" = "montenegro"
"ga" = "montainéagró"
"hr" = "crna-gora"
"it" = "montenegro"
"lt" = "juodkalnija"
"lv" = "melnkalne"
"nl" = "montenegro"
"hu" = "montenegró"
"no" = "montenegro"
"pl" = "czarnogóra"
"pt-PT" = "montenegro"
"ro" = "muntenegru"
"sk" = "čierna-hora"
"sl" = "črna-gora"
"sr" = "црна-гора"
"fi" = "montenegro"
"sv" = "montenegro"
"ru" = "черногория"
"uk" = "чорногорія"
"el" = "μαυροβούνιο"
"zh-CN" = "黑山"
"zh-TW" = "蒙特內哥羅"
"ja" = "モンテネグロ"
"ko" = "몬테네그로"
"bg" = "черна-гора"
"cs" = "černá-hora"
"mt" = "il-montenegro"

[country.codes]
gisco_cntr_id = "ME"
iso_3166_1_alpha2 = "ME"
iso_3166_1_alpha3 = "MNE"
