schema_version = 1

[[country]]
id = "MM"
kind = "country"
official_languages = ["my"]

[country.names]
"ca" = "Myanmar (Birmània)"
"da" = "Myanmar (Burma)"
"de" = "Myanmar"
"et" = "Myanmar (Birma)"
"en" = "Myanmar (Burma)"
"es" = "Myanmar (Birmania)"
"fr" = "Myanmar (Birmanie)"
"oc" = "Birmania"
"lb" = "Myanmar"
"ga" = "Maenmar (Burma)"
"hr" = "Mjanmar (Burma)"
"it" = "Myanmar (Birmania)"
"lt" = "Mianmaras (Birma)"
"lv" = "Mjanma (Birma)"
"nl" = "Myanmar (Birma)"
"hu" = "Mianmar"
"no" = "Myanmar (Burma)"
"pl" = "Mjanma (Birma)"
"pt-PT" = "Mianmar (Birmânia)"
"ro" = "Myanmar (Birmania)"
"sk" = "Mjanmarsko"
"sl" = "Mjanmar (Burma)"
"sr" = "Мијанмар (Бурма)"
"fi" = "Myanmar (Burma)"
"sv" = "Myanmar (Burma)"
"ru" = "Мьянма (Бирма)"
"uk" = "Мʼянма (Бірма)"
"el" = "Μιανμάρ (Βιρμανία)"
"zh-CN" = "缅甸"
"zh-TW" = "緬甸"
"ja" = "ミャンマー (ビルマ)"
"ko" = "미얀마"
"bg" = "Мианмар (Бирма)"
"cs" = "Myanmar (Barma)"
"mt" = "il-Myanmar/Burma"
"my" = "မြန်မာ"

[country.slugs]
"ca" = "myanmar-birmània"
"da" = "myanmar-burma"
"de" = "myanmar"
"et" = "myanmar-birma"
"en" = "myanmar-burma"
"es" = "myanmar-birmania"
"fr" = "myanmar-birmanie"
"oc" = "birmania"
"lb" = "myanmar"
"ga" = "maenmar-burma"
"hr" = "mjanmar-burma"
"it" = "myanmar-birmania"
"lt" = "mianmaras-birma"
"lv" = "mjanma-birma"
"nl" = "myanmar-birma"
"hu" = "mianmar"
"no" = "myanmar-burma"
"pl" = "mjanma-birma"
"pt-PT" = "mianmar-birmânia"
"ro" = "myanmar-birmania"
"sk" = "mjanmarsko"
"sl" = "mjanmar-burma"
"sr" = "мијанмар-бурма"
"fi" = "myanmar-burma"
"sv" = "myanmar-burma"
"ru" = "мьянма-бирма"
"uk" = "мʼянма-бірма"
"el" = "μιανμάρ-βιρμανία"
"zh-CN" = "缅甸"
"zh-TW" = "緬甸"
"ja" = "ミャンマー-ビルマ"
"ko" = "미얀마"
"bg" = "мианмар-бирма"
"cs" = "myanmar-barma"
"mt" = "il-myanmar-burma"

[country.codes]
gisco_cntr_id = "MM"
iso_3166_1_alpha2 = "MM"
iso_3166_1_alpha3 = "MMR"
