schema_version = 1

[[country]]
id = "MX"
kind = "country"
official_languages = ["es"]

[country.names]
"ca" = "Mèxic"
"da" = "Mexico"
"de" = "Mexiko"
"et" = "Mehhiko"
"en" = "Mexico"
"es" = "México"
"fr" = "Mexique"
"oc" = "Mexic"
"lb" = "Mexiko"
"ga" = "Meicsiceo"
"hr" = "Meksiko"
"it" = "Messico"
"lt" = "Meksika"
"lv" = "Meksika"
"nl" = "Mexico"
"hu" = "Mexikó"
"no" = "Mexico"
"pl" = "Meksyk"
"pt-PT" = "México"
"ro" = "Mexic"
"sk" = "Mexiko"
"sl" = "Mehika"
"sr" = "Мексико"
"fi" = "Meksiko"
"sv" = "Mexiko"
"ru" = "Мексика"
"uk" = "Мексика"
"el" = "Μεξικό"
"zh-CN" = "墨西哥"
"zh-TW" = "墨西哥"
"ja" = "メキシコ"
"ko" = "멕시코"
"bg" = "Мексико"
"cs" = "Mexiko"
"mt" = "il-Messiku"

[country.slugs]
"ca" = "mèxic"
"da" = "mexico"
"de" = "mexiko"
"et" = "mehhiko"
"en" = "mexico"
"es" = "méxico"
"fr" = "mexique"
"oc" = "mexic"
"lb" = "mexiko"
"ga" = "meicsiceo"
"hr" = "meksiko"
"it" = "messico"
"lt" = "meksika"
"lv" = "meksika"
"nl" = "mexico"
"hu" = "mexikó"
"no" = "mexico"
"pl" = "meksyk"
"pt-PT" = "méxico"
"ro" = "mexic"
"sk" = "mexiko"
"sl" = "mehika"
"sr" = "мексико"
"fi" = "meksiko"
"sv" = "mexiko"
"ru" = "мексика"
"uk" = "мексика"
"el" = "μεξικό"
"zh-CN" = "墨西哥"
"zh-TW" = "墨西哥"
"ja" = "メキシコ"
"ko" = "멕시코"
"bg" = "мексико"
"cs" = "mexiko"
"mt" = "il-messiku"

[country.codes]
gisco_cntr_id = "MX"
iso_3166_1_alpha2 = "MX"
iso_3166_1_alpha3 = "MEX"
