schema_version = 1

[[country]]
id = "MY"
kind = "country"
official_languages = ["ms"]

[country.names]
"ca" = "Malàisia"
"da" = "Malaysia"
"de" = "Malaysia"
"et" = "Malaisia"
"en" = "Malaysia"
"es" = "Malasia"
"fr" = "Malaisie"
"oc" = "Malàisia"
"lb" = "Malaysia"
"ga" = "an Mhalaeisia"
"hr" = "Malezija"
"it" = "Malaysia"
"lt" = "Malaizija"
"lv" = "Malaizija"
"nl" = "Maleisië"
"hu" = "Malajzia"
"no" = "Malaysia"
"pl" = "Malezja"
"pt-PT" = "Malásia"
"ro" = "Malaysia"
"sk" = "Malajzia"
"sl" = "Malezija"
"sr" = "Малезија"
"fi" = "Malesia"
"sv" = "Malaysia"
"ru" = "Малайзия"
"uk" = "Малайзія"
"el" = "Μαλαισία"
"zh-CN" = "马来西亚"
"zh-TW" = "馬來西亞"
"ja" = "マレーシア"
"ko" = "말레이시아"
"bg" = "Малайзия"
"cs" = "Malajsie"
"mt" = "il-Malasja"
"ms" = "Malaysia"

[country.slugs]
"ca" = "malàisia"
"da" = "malaysia"
"de" = "malaysia"
"et" = "malaisia"
"en" = "malaysia"
"es" = "malasia"
"fr" = "malaisie"
"oc" = "malàisia"
"lb" = "malaysia"
"ga" = "an-mhalaeisia"
"hr" = "malezija"
"it" = "malaysia"
"lt" = "malaizija"
"lv" = "malaizija"
"nl" = "maleisië"
"hu" = "malajzia"
"no" = "malaysia"
"pl" = "malezja"
"pt-PT" = "malásia"
"ro" = "malaysia"
"sk" = "malajzia"
"sl" = "malezija"
"sr" = "малезија"
"fi" = "malesia"
"sv" = "malaysia"
"ru" = "малайзия"
"uk" = "малайзія"
"el" = "μαλαισία"
"zh-CN" = "马来西亚"
"zh-TW" = "馬來西亞"
"ja" = "マレーシア"
"ko" = "말레이시아"
"bg" = "малайзия"
"cs" = "malajsie"
"mt" = "il-malasja"

[country.codes]
gisco_cntr_id = "MY"
iso_3166_1_alpha2 = "MY"
iso_3166_1_alpha3 = "MYS"
