schema_version = 1

[[country]]
id = "NC"
kind = "country"
official_languages = ["fr"]

[country.names]
"ca" = "Nova Caledònia"
"da" = "Ny Kaledonien"
"de" = "Neukaledonien"
"et" = "Uus-Kaledoonia"
"en" = "New Caledonia"
"es" = "Nueva Caledonia"
"fr" = "Nouvelle-Calédonie"
"oc" = "Nòva Caledonia"
"lb" = "Neikaledonien"
"ga" = "an Nua-Chaladóin"
"hr" = "Nova Kaledonija"
"it" = "Nuova Caledonia"
"lt" = "Naujoji Kaledonija"
"lv" = "Jaunkaledonija"
"nl" = "Nieuw-Caledonië"
"hu" = "Új-Kaledónia"
"no" = "Ny-Caledonia"
"pl" = "Nowa Kaledonia"
"pt-PT" = "Nova Caledónia"
"ro" = "Noua Caledonie"
"sk" = "Nová Kaledónia"
"sl" = "Nova Kaledonija"
"sr" = "Нова Каледонија"
"fi" = "Uusi-Kaledonia"
"sv" = "Nya Kaledonien"
"ru" = "Новая Каледония"
"uk" = "Нова Каледонія"
"el" = "Νέα Καληδονία"
"zh-CN" = "新喀里多尼亚"
"zh-TW" = "新喀里多尼亞"
"ja" = "ニューカレドニア"
"ko" = "뉴칼레도니아"
"bg" = "Нова Каледония"
"cs" = "Nová Kaledonie"
"mt" = "New Caledonia"

[country.slugs]
"ca" = "nova-caledònia"
"da" = "ny-kaledonien"
"de" = "neukaledonien"
"et" = "uus-kaledoonia"
"en" = "new-caledonia"
"es" = "nueva-caledonia"
"fr" = "nouvelle-calédonie"
"oc" = "nòva-caledonia"
"lb" = "neikaledonien"
"ga" = "an-nua-chaladóin"
"hr" = "nova-kaledonija"
"it" = "nuova-caledonia"
"lt" = "naujoji-kaledonija"
"lv" = "jaunkaledonija"
"nl" = "nieuw-caledonië"
"hu" = "új-kaledónia"
"no" = "ny-caledonia"
"pl" = "nowa-kaledonia"
"pt-PT" = "nova-caledónia"
"ro" = "noua-caledonie"
"sk" = "nová-kaledónia"
"sl" = "nova-kaledonija"
"sr" = "нова-каледонија"
"fi" = "uusi-kaledonia"
"sv" = "nya-kaledonien"
"ru" = "новая-каледония"
"uk" = "нова-каледонія"
"el" = "νέα-καληδονία"
"zh-CN" = "新喀里多尼亚"
"zh-TW" = "新喀里多尼亞"
"ja" = "ニューカレドニア"
"ko" = "뉴칼레도니아"
"bg" = "нова-каледония"
"cs" = "nová-kaledonie"
"mt" = "new-caledonia"

[country.codes]
gisco_cntr_id = "NC"
iso_3166_1_alpha2 = "NC"
iso_3166_1_alpha3 = "NCL"
