schema_version = 1

[[country]]
id = "NL"
kind = "country"
official_languages = ["nl"]

[country.names]
"ca" = "Països Baixos"
"da" = "Nederlandene"
"de" = "Niederlande"
"et" = "Holland"
"en" = "Netherlands"
"es" = "Países Bajos"
"fr" = "Pays-Bas"
"oc" = "Païses Basses"
"lb" = "Holland"
"ga" = "an Ísiltír"
"hr" = "Nizozemska"
"it" = "Paesi Bassi"
"lt" = "Nyderlandai"
"lv" = "Nīderlande"
"nl" = "Nederland"
"hu" = "Hollandia"
"no" = "Nederland"
"pl" = "Holandia"
"pt-PT" = "Países Baixos"
"ro" = "Țările de Jos"
"sk" = "Holandsko"
"sl" = "Nizozemska"
"sr" = "Холандија"
"fi" = "Alankomaat"
"sv" = "Nederländerna"
"ru" = "Нидерланды"
"uk" = "Нідерланди"
"el" = "Κάτω Χώρες"
"zh-CN" = "荷兰"
"zh-TW" = "荷蘭"
"ja" = "オランダ"
"ko" = "네덜란드"
"bg" = "Нидерландия"
"cs" = "Nizozemsko"
"mt" = "in-Netherlands"

[country.slugs]
"ca" = "països-baixos"
"da" = "nederlandene"
"de" = "niederlande"
"et" = "holland"
"en" = "netherlands"
"es" = "países-bajos"
"fr" = "pays-bas"
"oc" = "païses-basses"
"lb" = "holland"
"ga" = "an-ísiltír"
"hr" = "nizozemska"
"it" = "paesi-bassi"
"lt" = "nyderlandai"
"lv" = "nīderlande"
"nl" = "nederland"
"hu" = "hollandia"
"no" = "nederland"
"pl" = "holandia"
"pt-PT" = "países-baixos"
"ro" = "țările-de-jos"
"sk" = "holandsko"
"sl" = "nizozemska"
"sr" = "холандија"
"fi" = "alankomaat"
"sv" = "nederländerna"
"ru" = "нидерланды"
"uk" = "нідерланди"
"el" = "κάτω-χώρεσ"
"zh-CN" = "荷兰"
"zh-TW" = "荷蘭"
"ja" = "オランダ"
"ko" = "네덜란드"
"bg" = "нидерландия"
"cs" = "nizozemsko"
"mt" = "in-netherlands"

[country.codes]
gisco_cntr_id = "NL"
iso_3166_1_alpha2 = "NL"
iso_3166_1_alpha3 = "NLD"
