schema_version = 1

[[country]]
id = "NO"
kind = "country"
official_languages = ["no"]

[country.names]
"ca" = "Noruega"
"da" = "Norge"
"de" = "Norwegen"
"et" = "Norra"
"en" = "Norway"
"es" = "Noruega"
"fr" = "Norvège"
"oc" = "Norvègia"
"lb" = "Norwegen"
"ga" = "an Iorua"
"hr" = "Norveška"
"it" = "Norvegia"
"lt" = "Norvegija"
"lv" = "Norvēģija"
"nl" = "Noorwegen"
"hu" = "Norvégia"
"no" = "Norge"
"pl" = "Norwegia"
"pt-PT" = "Noruega"
"ro" = "Norvegia"
"sk" = "Nórsko"
"sl" = "Norveška"
"sr" = "Норвешка"
"fi" = "Norja"
"sv" = "Norge"
"ru" = "Норвегия"
"uk" = "Норвегія"
"el" = "Νορβηγία"
"zh-CN" = "挪威"
"zh-TW" = "挪威"
"ja" = "ノルウェー"
"ko" = "노르웨이"
"bg" = "Норвегия"
"cs" = "Norsko"
"mt" = "in-Norveġja"

[country.slugs]
"ca" = "noruega"
"da" = "norge"
"de" = "norwegen"
"et" = "norra"
"en" = "norway"
"es" = "noruega"
"fr" = "norvège"
"oc" = "norvègia"
"lb" = "norwegen"
"ga" = "an-iorua"
"hr" = "norveška"
"it" = "norvegia"
"lt" = "norvegija"
"lv" = "norvēģija"
"nl" = "noorwegen"
"hu" = "norvégia"
"no" = "norge"
"pl" = "norwegia"
"pt-PT" = "noruega"
"ro" = "norvegia"
"sk" = "nórsko"
"sl" = "norveška"
"sr" = "норвешка"
"fi" = "norja"
"sv" = "norge"
"ru" = "норвегия"
"uk" = "норвегія"
"el" = "νορβηγία"
"zh-CN" = "挪威"
"zh-TW" = "挪威"
"ja" = "ノルウェー"
"ko" = "노르웨이"
"bg" = "норвегия"
"cs" = "norsko"
"mt" = "in-norveġja"

[country.codes]
gisco_cntr_id = "NO"
iso_3166_1_alpha2 = "NO"
iso_3166_1_alpha3 = "NOR"
