schema_version = 1

[[country]]
id = "NP"
kind = "country"
official_languages = ["ne"]

[country.names]
"ca" = "Nepal"
"da" = "Nepal"
"de" = "Nepal"
"et" = "Nepal"
"en" = "Nepal"
"es" = "Nepal"
"fr" = "Népal"
"oc" = "Nepal"
"lb" = "Nepal"
"ga" = "Neipeal"
"hr" = "Nepal"
"it" = "Nepal"
"lt" = "Nepalas"
"lv" = "Nepāla"
"nl" = "Nepal"
"hu" = "Nepál"
"no" = "Nepal"
"pl" = "Nepal"
"pt-PT" = "Nepal"
"ro" = "Nepal"
"sk" = "Nepál"
"sl" = "Nepal"
"sr" = "Непал"
"fi" = "Nepal"
"sv" = "Nepal"
"ru" = "Непал"
"uk" = "Непал"
"el" = "Νεπάλ"
"zh-CN" = "尼泊尔"
"zh-TW" = "尼泊爾"
"ja" = "ネパール"
"ko" = "네팔"
"bg" = "Непал"
"cs" = "Nepál"
"mt" = "in-Nepal"
"ne" = "नेपाल"

[country.slugs]
"ca" = "nepal"
"da" = "nepal"
"de" = "nepal"
"et" = "nepal"
"en" = "nepal"
"es" = "nepal"
"fr" = "népal"
"oc" = "nepal"
"lb" = "nepal"
"ga" = "neipeal"
"hr" = "nepal"
"it" = "nepal"
"lt" = "nepalas"
"lv" = "nepāla"
"nl" = "nepal"
"hu" = "nepál"
"no" = "nepal"
"pl" = "nepal"
"pt-PT" = "nepal"
"ro" = "nepal"
"sk" = "nepál"
"sl" = "nepal"
"sr" = "непал"
"fi" = "nepal"
"sv" = "nepal"
"ru" = "непал"
"uk" = "непал"
"el" = "νεπάλ"
"zh-CN" = "尼泊尔"
"zh-TW" = "尼泊爾"
"ja" = "ネパール"
"ko" = "네팔"
"bg" = "непал"
"cs" = "nepál"
"mt" = "in-nepal"

[country.codes]
gisco_cntr_id = "NP"
iso_3166_1_alpha2 = "NP"
iso_3166_1_alpha3 = "NPL"
