schema_version = 1

[[country]]
id = "NZ"
kind = "country"
official_languages = ["en", "mi"]

[country.names]
"ca" = "Nova Zelanda"
"da" = "New Zealand"
"de" = "Neuseeland"
"et" = "Uus-Meremaa"
"en" = "New Zealand"
"es" = "Nueva Zelanda"
"fr" = "Nouvelle-Zélande"
"oc" = "Nòva Zelanda"
"lb" = "Neiséiland"
"ga" = "an Nua-Shéalainn"
"hr" = "Novi Zeland"
"it" = "Nuova Zelanda"
"lt" = "Naujoji Zelandija"
"lv" = "Jaunzēlande"
"nl" = "Nieuw-Zeeland"
"hu" = "Új-Zéland"
"no" = "New Zealand"
"pl" = "Nowa Zelandia"
"pt-PT" = "Nova Zelândia"
"ro" = "Noua Zeelandă"
"sk" = "Nový Zéland"
"sl" = "Nova Zelandija"
"sr" = "Нови Зеланд"
"fi" = "Uusi-Seelanti"
"sv" = "Nya Zeeland"
"ru" = "Новая Зеландия"
"uk" = "Нова Зеландія"
"el" = "Νέα Ζηλανδία"
"zh-CN" = "新西兰"
"zh-TW" = "紐西蘭"
"ja" = "ニュージーランド"
"ko" = "뉴질랜드"
"bg" = "Нова Зеландия"
"cs" = "Nový Zéland"
"mt" = "New Zealand"
"mi" = "Aotearoa"

[country.slugs]
"ca" = "nova-zelanda"
"da" = "new-zealand"
"de" = "neuseeland"
"et" = "uus-meremaa"
"en" = "new-zealand"
"es" = "nueva-zelanda"
"fr" = "nouvelle-zélande"
"oc" = "nòva-zelanda"
"lb" = "neiséiland"
"ga" = "an-nua-shéalainn"
"hr" = "novi-zeland"
"it" = "nuova-zelanda"
"lt" = "naujoji-zelandija"
"lv" = "jaunzēlande"
"nl" = "nieuw-zeeland"
"hu" = "új-zéland"
"no" = "new-zealand"
"pl" = "nowa-zelandia"
"pt-PT" = "nova-zelândia"
"ro" = "noua-zeelandă"
"sk" = "nový-zéland"
"sl" = "nova-zelandija"
"sr" = "нови-зеланд"
"fi" = "uusi-seelanti"
"sv" = "nya-zeeland"
"ru" = "новая-зеландия"
"uk" = "нова-зеландія"
"el" = "νέα-ζηλανδία"
"zh-CN" = "新西兰"
"zh-TW" = "紐西蘭"
"ja" = "ニュージーランド"
"ko" = "뉴질랜드"
"bg" = "нова-зеландия"
"cs" = "nový-zéland"
"mt" = "new-zealand"

[country.codes]
gisco_cntr_id = "NZ"
iso_3166_1_alpha2 = "NZ"
iso_3166_1_alpha3 = "NZL"
