schema_version = 1

[[country]]
id = "OM"
kind = "country"
official_languages = ["ar"]

[country.names]
"ca" = "Oman"
"da" = "Oman"
"de" = "Oman"
"et" = "Omaan"
"en" = "Oman"
"es" = "Omán"
"fr" = "Oman"
"oc" = "Òman"
"lb" = "Oman"
"ga" = "Óman"
"hr" = "Oman"
"it" = "Oman"
"lt" = "Omanas"
"lv" = "Omāna"
"nl" = "Oman"
"hu" = "Omán"
"no" = "Oman"
"pl" = "Oman"
"pt-PT" = "Omã"
"ro" = "Oman"
"sk" = "Omán"
"sl" = "Oman"
"sr" = "Оман"
"fi" = "Oman"
"sv" = "Oman"
"ru" = "Оман"
"uk" = "Оман"
"el" = "Ομάν"
"zh-CN" = "阿曼"
"zh-TW" = "阿曼"
"ja" = "オマーン"
"ko" = "오만"
"bg" = "Оман"
"cs" = "Omán"
"mt" = "l-Oman"
"ar" = "عُمان"

[country.slugs]
"ca" = "oman"
"da" = "oman"
"de" = "oman"
"et" = "omaan"
"en" = "oman"
"es" = "omán"
"fr" = "oman"
"oc" = "òman"
"lb" = "oman"
"ga" = "óman"
"hr" = "oman"
"it" = "oman"
"lt" = "omanas"
"lv" = "omāna"
"nl" = "oman"
"hu" = "omán"
"no" = "oman"
"pl" = "oman"
"pt-PT" = "omã"
"ro" = "oman"
"sk" = "omán"
"sl" = "oman"
"sr" = "оман"
"fi" = "oman"
"sv" = "oman"
"ru" = "оман"
"uk" = "оман"
"el" = "ομάν"
"zh-CN" = "阿曼"
"zh-TW" = "阿曼"
"ja" = "オマーン"
"ko" = "오만"
"bg" = "оман"
"cs" = "omán"
"mt" = "l-oman"

[country.codes]
gisco_cntr_id = "OM"
iso_3166_1_alpha2 = "OM"
iso_3166_1_alpha3 = "OMN"
