schema_version = 1

[[country]]
id = "PL"
kind = "country"
official_languages = ["pl"]

[country.names]
"ca" = "Polònia"
"da" = "Polen"
"de" = "Polen"
"et" = "Poola"
"en" = "Poland"
"es" = "Polonia"
"fr" = "Pologne"
"oc" = "Polonha"
"lb" = "Polen"
"ga" = "an Pholainn"
"hr" = "Poljska"
"it" = "Polonia"
"lt" = "Lenkija"
"lv" = "Polija"
"nl" = "Polen"
"hu" = "Lengyelország"
"no" = "Polen"
"pl" = "Polska"
"pt-PT" = "Polónia"
"ro" = "Polonia"
"sk" = "Poľsko"
"sl" = "Poljska"
"sr" = "Пољска"
"fi" = "Puola"
"sv" = "Polen"
"ru" = "Польша"
"uk" = "Польща"
"el" = "Πολωνία"
"zh-CN" = "波兰"
"zh-TW" = "波蘭"
"ja" = "ポーランド"
"ko" = "폴란드"
"bg" = "Полша"
"cs" = "Polsko"
"mt" = "il-Polonja"

[country.slugs]
"ca" = "polònia"
"da" = "polen"
"de" = "polen"
"et" = "poola"
"en" = "poland"
"es" = "polonia"
"fr" = "pologne"
"oc" = "polonha"
"lb" = "polen"
"ga" = "an-pholainn"
"hr" = "poljska"
"it" = "polonia"
"lt" = "lenkija"
"lv" = "polija"
"nl" = "polen"
"hu" = "lengyelország"
"no" = "polen"
"pl" = "polska"
"pt-PT" = "polónia"
"ro" = "polonia"
"sk" = "poľsko"
"sl" = "poljska"
"sr" = "пољска"
"fi" = "puola"
"sv" = "polen"
"ru" = "польша"
"uk" = "польща"
"el" = "πολωνία"
"zh-CN" = "波兰"
"zh-TW" = "波蘭"
"ja" = "ポーランド"
"ko" = "폴란드"
"bg" = "полша"
"cs" = "polsko"
"mt" = "il-polonja"

[country.codes]
gisco_cntr_id = "PL"
iso_3166_1_alpha2 = "PL"
iso_3166_1_alpha3 = "POL"
