schema_version = 1

[[country]]
id = "PR"
kind = "country"
official_languages = ["es", "en"]

[country.names]
"ca" = "Puerto Rico"
"da" = "Puerto Rico"
"de" = "Puerto Rico"
"et" = "Puerto Rico"
"en" = "Puerto Rico"
"es" = "Puerto Rico"
"fr" = "Porto Rico"
"oc" = "Puerto Rico"
"lb" = "Puerto Rico"
"ga" = "Pórtó Ríce"
"hr" = "Portoriko"
"it" = "Portorico"
"lt" = "Puerto Rikas"
"lv" = "Puertoriko"
"nl" = "Puerto Rico"
"hu" = "Puerto Rico"
"no" = "Puerto Rico"
"pl" = "Portoryko"
"pt-PT" = "Porto Rico"
"ro" = "Puerto Rico"
"sk" = "Portoriko"
"sl" = "Portoriko"
"sr" = "Порторико"
"fi" = "Puerto Rico"
"sv" = "Puerto Rico"
"ru" = "Пуэрто-Рико"
"uk" = "Пуерто-Рико"
"el" = "Πουέρτο Ρίκο"
"zh-CN" = "波多黎各"
"zh-TW" = "波多黎各"
"ja" = "プエルトリコ"
"ko" = "푸에르토리코"
"bg" = "Пуерто Рико"
"cs" = "Portoriko"
"mt" = "Puerto Rico"

[country.slugs]
"ca" = "puerto-rico"
"da" = "puerto-rico"
"de" = "puerto-rico"
"et" = "puerto-rico"
"en" = "puerto-rico"
"es" = "puerto-rico"
"fr" = "porto-rico"
"oc" = "puerto-rico"
"lb" = "puerto-rico"
"ga" = "pórtó-ríce"
"hr" = "portoriko"
"it" = "portorico"
"lt" = "puerto-rikas"
"lv" = "puertoriko"
"nl" = "puerto-rico"
"hu" = "puerto-rico"
"no" = "puerto-rico"
"pl" = "portoryko"
"pt-PT" = "porto-rico"
"ro" = "puerto-rico"
"sk" = "portoriko"
"sl" = "portoriko"
"sr" = "порторико"
"fi" = "puerto-rico"
"sv" = "puerto-rico"
"ru" = "пуэрто-рико"
"uk" = "пуерто-рико"
"el" = "πουέρτο-ρίκο"
"zh-CN" = "波多黎各"
"zh-TW" = "波多黎各"
"ja" = "プエルトリコ"
"ko" = "푸에르토리코"
"bg" = "пуерто-рико"
"cs" = "portoriko"
"mt" = "puerto-rico"

[country.codes]
gisco_cntr_id = "PR"
iso_3166_1_alpha2 = "PR"
iso_3166_1_alpha3 = "PRI"
