schema_version = 1

[[country]]
id = "PT"
kind = "country"
official_languages = ["pt"]

[country.names]
"ca" = "Portugal"
"da" = "Portugal"
"de" = "Portugal"
"et" = "Portugal"
"en" = "Portugal"
"es" = "Portugal"
"fr" = "Portugal"
"oc" = "Portugal"
"lb" = "Portugal"
"ga" = "an Phortaingéil"
"hr" = "Portugal"
"it" = "Portogallo"
"lt" = "Portugalija"
"lv" = "Portugāle"
"nl" = "Portugal"
"hu" = "Portugália"
"no" = "Portugal"
"pl" = "Portugalia"
"pt-PT" = "Portugal"
"ro" = "Portugalia"
"sk" = "Portugalsko"
"sl" = "Portugalska"
"sr" = "Португалија"
"fi" = "Portugali"
"sv" = "Portugal"
"ru" = "Португалия"
"uk" = "Португалія"
"el" = "Πορτογαλία"
"zh-CN" = "葡萄牙"
"zh-TW" = "葡萄牙"
"ja" = "ポルトガル"
"ko" = "포르투갈"
"bg" = "Португалия"
"cs" = "Portugalsko"
"mt" = "il-Portugall"
"pt" = "Portugal"

[country.slugs]
"ca" = "portugal"
"da" = "portugal"
"de" = "portugal"
"et" = "portugal"
"en" = "portugal"
"es" = "portugal"
"fr" = "portugal"
"oc" = "portugal"
"lb" = "portugal"
"ga" = "an-phortaingéil"
"hr" = "portugal"
"it" = "portogallo"
"lt" = "portugalija"
"lv" = "portugāle"
"nl" = "portugal"
"hu" = "portugália"
"no" = "portugal"
"pl" = "portugalia"
"pt-PT" = "portugal"
"ro" = "portugalia"
"sk" = "portugalsko"
"sl" = "portugalska"
"sr" = "португалија"
"fi" = "portugali"
"sv" = "portugal"
"ru" = "португалия"
"uk" = "португалія"
"el" = "πορτογαλία"
"zh-CN" = "葡萄牙"
"zh-TW" = "葡萄牙"
"ja" = "ポルトガル"
"ko" = "포르투갈"
"bg" = "португалия"
"cs" = "portugalsko"
"mt" = "il-portugall"

[country.codes]
gisco_cntr_id = "PT"
iso_3166_1_alpha2 = "PT"
iso_3166_1_alpha3 = "PRT"
