schema_version = 1

[[country]]
id = "RO"
kind = "country"
official_languages = ["ro"]

[country.names]
"ca" = "Romania"
"da" = "Rumænien"
"de" = "Rumänien"
"et" = "Rumeenia"
"en" = "Romania"
"es" = "Rumanía"
"fr" = "Roumanie"
"oc" = "Romania"
"lb" = "Rumänien"
"ga" = "an Rómáin"
"hr" = "Rumunjska"
"it" = "Romania"
"lt" = "Rumunija"
"lv" = "Rumānija"
"nl" = "Roemenië"
"hu" = "Románia"
"no" = "Romania"
"pl" = "Rumunia"
"pt-PT" = "Roménia"
"ro" = "România"
"sk" = "Rumunsko"
"sl" = "Romunija"
"sr" = "Румунија"
"fi" = "Romania"
"sv" = "Rumänien"
"ru" = "Румыния"
"uk" = "Румунія"
"el" = "Ρουμανία"
"zh-CN" = "罗马尼亚"
"zh-TW" = "羅馬尼亞"
"ja" = "ルーマニア"
"ko" = "루마니아"
"bg" = "Румъния"
"cs" = "Rumunsko"
"mt" = "ir-Rumanija"

[country.slugs]
"ca" = "romania"
"da" = "rumænien"
"de" = "rumänien"
"et" = "rumeenia"
"en" = "romania"
"es" = "rumanía"
"fr" = "roumanie"
"oc" = "romania"
"lb" = "rumänien"
"ga" = "an-rómáin"
"hr" = "rumunjska"
"it" = "romania"
"lt" = "rumunija"
"lv" = "rumānija"
"nl" = "roemenië"
"hu" = "románia"
"no" = "romania"
"pl" = "rumunia"
"pt-PT" = "roménia"
"ro" = "românia"
"sk" = "rumunsko"
"sl" = "romunija"
"sr" = "румунија"
"fi" = "romania"
"sv" = "rumänien"
"ru" = "румыния"
"uk" = "румунія"
"el" = "ρουμανία"
"zh-CN" = "罗马尼亚"
"zh-TW" = "羅馬尼亞"
"ja" = "ルーマニア"
"ko" = "루마니아"
"bg" = "румъния"
"cs" = "rumunsko"
"mt" = "ir-rumanija"

[country.codes]
gisco_cntr_id = "RO"
iso_3166_1_alpha2 = "RO"
iso_3166_1_alpha3 = "ROU"
