schema_version = 1

[[country]]
id = "RS"
kind = "country"
official_languages = ["sr"]

[country.names]
"ca" = "Sèrbia"
"da" = "Serbien"
"de" = "Serbien"
"et" = "Serbia"
"en" = "Serbia"
"es" = "Serbia"
"fr" = "Serbie"
"oc" = "Serbia"
"lb" = "Serbien"
"ga" = "an tSeirbia"
"hr" = "Srbija"
"it" = "Serbia"
"lt" = "Serbija"
"lv" = "Serbija"
"nl" = "Servië"
"hu" = "Szerbia"
"no" = "Serbia"
"pl" = "Serbia"
"pt-PT" = "Sérvia"
"ro" = "Serbia"
"sk" = "Srbsko"
"sl" = "Srbija"
"sr" = "Србија"
"fi" = "Serbia"
"sv" = "Serbien"
"ru" = "Сербия"
"uk" = "Сербія"
"el" = "Σερβία"
"zh-CN" = "塞尔维亚"
"zh-TW" = "塞爾維亞"
"ja" = "セルビア"
"ko" = "세르비아"
"bg" = "Сърбия"
"cs" = "Srbsko"
"mt" = "is-Serbja"

[country.slugs]
"ca" = "sèrbia"
"da" = "serbien"
"de" = "serbien"
"et" = "serbia"
"en" = "serbia"
"es" = "serbia"
"fr" = "serbie"
"oc" = "serbia"
"lb" = "serbien"
"ga" = "an-tseirbia"
"hr" = "srbija"
"it" = "serbia"
"lt" = "serbija"
"lv" = "serbija"
"nl" = "servië"
"hu" = "szerbia"
"no" = "serbia"
"pl" = "serbia"
"pt-PT" = "sérvia"
"ro" = "serbia"
"sk" = "srbsko"
"sl" = "srbija"
"sr" = "србија"
"fi" = "serbia"
"sv" = "serbien"
"ru" = "сербия"
"uk" = "сербія"
"el" = "σερβία"
"zh-CN" = "塞尔维亚"
"zh-TW" = "塞爾維亞"
"ja" = "セルビア"
"ko" = "세르비아"
"bg" = "сърбия"
"cs" = "srbsko"
"mt" = "is-serbja"

[country.codes]
gisco_cntr_id = "RS"
iso_3166_1_alpha2 = "RS"
iso_3166_1_alpha3 = "SRB"
