schema_version = 1

[[country]]
id = "RU"
kind = "country"
official_languages = ["ru"]

[country.names]
"ca" = "Rússia"
"da" = "Rusland"
"de" = "Russland"
"et" = "Venemaa"
"en" = "Russia"
"es" = "Rusia"
"fr" = "Russie"
"oc" = "Russia"
"lb" = "Russland"
"ga" = "an Rúis"
"hr" = "Rusija"
"it" = "Russia"
"lt" = "Rusija"
"lv" = "Krievija"
"nl" = "Rusland"
"hu" = "Oroszország"
"no" = "Russland"
"pl" = "Rosja"
"pt-PT" = "Rússia"
"ro" = "Rusia"
"sk" = "Rusko"
"sl" = "Rusija"
"sr" = "Русија"
"fi" = "Venäjä"
"sv" = "Ryssland"
"ru" = "Россия"
"uk" = "Росія"
"el" = "Ρωσία"
"zh-CN" = "俄罗斯"
"zh-TW" = "俄羅斯"
"ja" = "ロシア"
"ko" = "러시아"
"bg" = "Русия"
"cs" = "Rusko"
"mt" = "ir-Russja"

[country.slugs]
"ca" = "rússia"
"da" = "rusland"
"de" = "russland"
"et" = "venemaa"
"en" = "russia"
"es" = "rusia"
"fr" = "russie"
"oc" = "russia"
"lb" = "russland"
"ga" = "an-rúis"
"hr" = "rusija"
"it" = "russia"
"lt" = "rusija"
"lv" = "krievija"
"nl" = "rusland"
"hu" = "oroszország"
"no" = "russland"
"pl" = "rosja"
"pt-PT" = "rússia"
"ro" = "rusia"
"sk" = "rusko"
"sl" = "rusija"
"sr" = "русија"
"fi" = "venäjä"
"sv" = "ryssland"
"ru" = "россия"
"uk" = "росія"
"el" = "ρωσία"
"zh-CN" = "俄罗斯"
"zh-TW" = "俄羅斯"
"ja" = "ロシア"
"ko" = "러시아"
"bg" = "русия"
"cs" = "rusko"
"mt" = "ir-russja"

[country.codes]
gisco_cntr_id = "RU"
iso_3166_1_alpha2 = "RU"
iso_3166_1_alpha3 = "RUS"
