schema_version = 1

[[country]]
id = "SE"
kind = "country"
official_languages = ["sv"]

[country.names]
"ca" = "Suècia"
"da" = "Sverige"
"de" = "Schweden"
"et" = "Rootsi"
"en" = "Sweden"
"es" = "Suecia"
"fr" = "Suède"
"oc" = "Suècia"
"lb" = "Schweden"
"ga" = "an tSualainn"
"hr" = "Švedska"
"it" = "Svezia"
"lt" = "Švedija"
"lv" = "Zviedrija"
"nl" = "Zweden"
"hu" = "Svédország"
"no" = "Sverige"
"pl" = "Szwecja"
"pt-PT" = "Suécia"
"ro" = "Suedia"
"sk" = "Švédsko"
"sl" = "Švedska"
"sr" = "Шведска"
"fi" = "Ruotsi"
"sv" = "Sverige"
"ru" = "Швеция"
"uk" = "Швеція"
"el" = "Σουηδία"
"zh-CN" = "瑞典"
"zh-TW" = "瑞典"
"ja" = "スウェーデン"
"ko" = "스웨덴"
"bg" = "Швеция"
"cs" = "Švédsko"
"mt" = "l-Iżvezja"

[country.slugs]
"ca" = "suècia"
"da" = "sverige"
"de" = "schweden"
"et" = "rootsi"
"en" = "sweden"
"es" = "suecia"
"fr" = "suède"
"oc" = "suècia"
"lb" = "schweden"
"ga" = "an-tsualainn"
"hr" = "švedska"
"it" = "svezia"
"lt" = "švedija"
"lv" = "zviedrija"
"nl" = "zweden"
"hu" = "svédország"
"no" = "sverige"
"pl" = "szwecja"
"pt-PT" = "suécia"
"ro" = "suedia"
"sk" = "švédsko"
"sl" = "švedska"
"sr" = "шведска"
"fi" = "ruotsi"
"sv" = "sverige"
"ru" = "швеция"
"uk" = "швеція"
"el" = "σουηδία"
"zh-CN" = "瑞典"
"zh-TW" = "瑞典"
"ja" = "スウェーデン"
"ko" = "스웨덴"
"bg" = "швеция"
"cs" = "švédsko"
"mt" = "l-iżvezja"

[country.codes]
gisco_cntr_id = "SE"
iso_3166_1_alpha2 = "SE"
iso_3166_1_alpha3 = "SWE"
