schema_version = 1

[[country]]
id = "SG"
kind = "country"
official_languages = ["en", "ms", "ta", "zh-CN"]

[country.names]
"ca" = "Singapur"
"da" = "Singapore"
"de" = "Singapur"
"et" = "Singapur"
"en" = "Singapore"
"es" = "Singapur"
"fr" = "Singapour"
"oc" = "Singapor"
"lb" = "Singapur"
"ga" = "Singeapór"
"hr" = "Singapur"
"it" = "Singapore"
"lt" = "Singapūras"
"lv" = "Singapūra"
"nl" = "Singapore"
"hu" = "Szingapúr"
"no" = "Singapore"
"pl" = "Singapur"
"pt-PT" = "Singapura"
"ro" = "Singapore"
"sk" = "Singapur"
"sl" = "Singapur"
"sr" = "Сингапур"
"fi" = "Singapore"
"sv" = "Singapore"
"ru" = "Сингапур"
"uk" = "Сінгапур"
"el" = "Σιγκαπούρη"
"zh-CN" = "新加坡"
"zh-TW" = "新加坡"
"ja" = "シンガポール"
"ko" = "싱가포르"
"bg" = "Сингапур"
"cs" = "Singapur"
"mt" = "Singapore"
"ms" = "Singapura"
"ta" = "சிங்கப்பூர்"

[country.slugs]
"ca" = "singapur"
"da" = "singapore"
"de" = "singapur"
"et" = "singapur"
"en" = "singapore"
"es" = "singapur"
"fr" = "singapour"
"oc" = "singapor"
"lb" = "singapur"
"ga" = "singeapór"
"hr" = "singapur"
"it" = "singapore"
"lt" = "singapūras"
"lv" = "singapūra"
"nl" = "singapore"
"hu" = "szingapúr"
"no" = "singapore"
"pl" = "singapur"
"pt-PT" = "singapura"
"ro" = "singapore"
"sk" = "singapur"
"sl" = "singapur"
"sr" = "сингапур"
"fi" = "singapore"
"sv" = "singapore"
"ru" = "сингапур"
"uk" = "сінгапур"
"el" = "σιγκαπούρη"
"zh-CN" = "新加坡"
"zh-TW" = "新加坡"
"ja" = "シンガポール"
"ko" = "싱가포르"
"bg" = "сингапур"
"cs" = "singapur"
"mt" = "singapore"

[country.codes]
gisco_cntr_id = "SG"
iso_3166_1_alpha2 = "SG"
iso_3166_1_alpha3 = "SGP"
