schema_version = 1

[[country]]
id = "SI"
kind = "country"
official_languages = ["sl"]

[country.names]
"ca" = "Eslovènia"
"da" = "Slovenien"
"de" = "Slowenien"
"et" = "Sloveenia"
"en" = "Slovenia"
"es" = "Eslovenia"
"fr" = "Slovénie"
"oc" = "Eslovènia"
"lb" = "Slowenien"
"ga" = "an tSlóivéin"
"hr" = "Slovenija"
"it" = "Slovenia"
"lt" = "Slovėnija"
"lv" = "Slovēnija"
"nl" = "Slovenië"
"hu" = "Szlovénia"
"no" = "Slovenia"
"pl" = "Słowenia"
"pt-PT" = "Eslovénia"
"ro" = "Slovenia"
"sk" = "Slovinsko"
"sl" = "Slovenija"
"sr" = "Словенија"
"fi" = "Slovenia"
"sv" = "Slovenien"
"ru" = "Словения"
"uk" = "Словенія"
"el" = "Σλοβενία"
"zh-CN" = "斯洛文尼亚"
"zh-TW" = "斯洛維尼亞"
"ja" = "スロベニア"
"ko" = "슬로베니아"
"bg" = "Словения"
"cs" = "Slovinsko"
"mt" = "is-Slovenja"

[country.slugs]
"ca" = "eslovènia"
"da" = "slovenien"
"de" = "slowenien"
"et" = "sloveenia"
"en" = "slovenia"
"es" = "eslovenia"
"fr" = "slovénie"
"oc" = "eslovènia"
"lb" = "slowenien"
"ga" = "an-tslóivéin"
"hr" = "slovenija"
"it" = "slovenia"
"lt" = "slovėnija"
"lv" = "slovēnija"
"nl" = "slovenië"
"hu" = "szlovénia"
"no" = "slovenia"
"pl" = "słowenia"
"pt-PT" = "eslovénia"
"ro" = "slovenia"
"sk" = "slovinsko"
"sl" = "slovenija"
"sr" = "словенија"
"fi" = "slovenia"
"sv" = "slovenien"
"ru" = "словения"
"uk" = "словенія"
"el" = "σλοβενία"
"zh-CN" = "斯洛文尼亚"
"zh-TW" = "斯洛維尼亞"
"ja" = "スロベニア"
"ko" = "슬로베니아"
"bg" = "словения"
"cs" = "slovinsko"
"mt" = "is-slovenja"

[country.codes]
gisco_cntr_id = "SI"
iso_3166_1_alpha2 = "SI"
iso_3166_1_alpha3 = "SVN"
