schema_version = 1

[[country]]
id = "SK"
kind = "country"
official_languages = ["sk"]

[country.names]
"ca" = "Eslovàquia"
"da" = "Slovakiet"
"de" = "Slowakei"
"et" = "Slovakkia"
"en" = "Slovakia"
"es" = "Eslovaquia"
"fr" = "Slovaquie"
"oc" = "Eslovaquia"
"lb" = "Slowakei"
"ga" = "an tSlóvaic"
"hr" = "Slovačka"
"it" = "Slovacchia"
"lt" = "Slovakija"
"lv" = "Slovākija"
"nl" = "Slowakije"
"hu" = "Szlovákia"
"no" = "Slovakia"
"pl" = "Słowacja"
"pt-PT" = "Eslováquia"
"ro" = "Slovacia"
"sk" = "Slovensko"
"sl" = "Slovaška"
"sr" = "Словачка"
"fi" = "Slovakia"
"sv" = "Slovakien"
"ru" = "Словакия"
"uk" = "Словаччина"
"el" = "Σλοβακία"
"zh-CN" = "斯洛伐克"
"zh-TW" = "斯洛伐克"
"ja" = "スロバキア"
"ko" = "슬로바키아"
"bg" = "Словакия"
"cs" = "Slovensko"
"mt" = "is-Slovakkja"

[country.slugs]
"ca" = "eslovàquia"
"da" = "slovakiet"
"de" = "slowakei"
"et" = "slovakkia"
"en" = "slovakia"
"es" = "eslovaquia"
"fr" = "slovaquie"
"oc" = "eslovaquia"
"lb" = "slowakei"
"ga" = "an-tslóvaic"
"hr" = "slovačka"
"it" = "slovacchia"
"lt" = "slovakija"
"lv" = "slovākija"
"nl" = "slowakije"
"hu" = "szlovákia"
"no" = "slovakia"
"pl" = "słowacja"
"pt-PT" = "eslováquia"
"ro" = "slovacia"
"sk" = "slovensko"
"sl" = "slovaška"
"sr" = "словачка"
"fi" = "slovakia"
"sv" = "slovakien"
"ru" = "словакия"
"uk" = "словаччина"
"el" = "σλοβακία"
"zh-CN" = "斯洛伐克"
"zh-TW" = "斯洛伐克"
"ja" = "スロバキア"
"ko" = "슬로바키아"
"bg" = "словакия"
"cs" = "slovensko"
"mt" = "is-slovakkja"

[country.codes]
gisco_cntr_id = "SK"
iso_3166_1_alpha2 = "SK"
iso_3166_1_alpha3 = "SVK"
