schema_version = 1

[[country]]
id = "TH"
kind = "country"
official_languages = ["th"]

[country.names]
"ca" = "Tailàndia"
"da" = "Thailand"
"de" = "Thailand"
"et" = "Tai"
"en" = "Thailand"
"es" = "Tailandia"
"fr" = "Thaïlande"
"oc" = "Tailàndia"
"lb" = "Thailand"
"ga" = "an Téalainn"
"hr" = "Tajland"
"it" = "Thailandia"
"lt" = "Tailandas"
"lv" = "Taizeme"
"nl" = "Thailand"
"hu" = "Thaiföld"
"no" = "Thailand"
"pl" = "Tajlandia"
"pt-PT" = "Tailândia"
"ro" = "Thailanda"
"sk" = "Thajsko"
"sl" = "Tajska"
"sr" = "Тајланд"
"fi" = "Thaimaa"
"sv" = "Thailand"
"ru" = "Таиланд"
"uk" = "Таїланд"
"el" = "Ταϊλάνδη"
"zh-CN" = "泰国"
"zh-TW" = "泰國"
"ja" = "タイ"
"ko" = "태국"
"bg" = "Тайланд"
"cs" = "Thajsko"
"mt" = "it-Tajlandja"
"th" = "ไทย"

[country.slugs]
"ca" = "tailàndia"
"da" = "thailand"
"de" = "thailand"
"et" = "tai"
"en" = "thailand"
"es" = "tailandia"
"fr" = "thaïlande"
"oc" = "tailàndia"
"lb" = "thailand"
"ga" = "an-téalainn"
"hr" = "tajland"
"it" = "thailandia"
"lt" = "tailandas"
"lv" = "taizeme"
"nl" = "thailand"
"hu" = "thaiföld"
"no" = "thailand"
"pl" = "tajlandia"
"pt-PT" = "tailândia"
"ro" = "thailanda"
"sk" = "thajsko"
"sl" = "tajska"
"sr" = "тајланд"
"fi" = "thaimaa"
"sv" = "thailand"
"ru" = "таиланд"
"uk" = "таїланд"
"el" = "ταϊλάνδη"
"zh-CN" = "泰国"
"zh-TW" = "泰國"
"ja" = "タイ"
"ko" = "태국"
"bg" = "тайланд"
"cs" = "thajsko"
"mt" = "it-tajlandja"

[country.codes]
gisco_cntr_id = "TH"
iso_3166_1_alpha2 = "TH"
iso_3166_1_alpha3 = "THA"
