schema_version = 1

[[country]]
id = "TR"
kind = "country"
official_languages = ["tr"]

[country.names]
"ca" = "Turquia"
"da" = "Tyrkiet"
"de" = "Türkei"
"et" = "Türgi"
"en" = "Türkiye"
"es" = "Turquía"
"fr" = "Turquie"
"oc" = "Turquia"
"lb" = "Tierkei"
"ga" = "an Tuirc"
"hr" = "Turska"
"it" = "Turchia"
"lt" = "Turkija"
"lv" = "Turcija"
"nl" = "Turkije"
"hu" = "Törökország"
"no" = "Tyrkia"
"pl" = "Turcja"
"pt-PT" = "Turquia"
"ro" = "Turcia"
"sk" = "Turecko"
"sl" = "Turčija"
"sr" = "Турска"
"fi" = "Turkki"
"sv" = "Turkiet"
"ru" = "Турция"
"uk" = "Туреччина"
"el" = "Τουρκία"
"zh-CN" = "土耳其"
"zh-TW" = "土耳其"
"ja" = "トルコ"
"ko" = "튀르키예"
"bg" = "Турция"
"cs" = "Turecko"
"mt" = "it-Turkija"
"tr" = "Türkiye"

[country.slugs]
"ca" = "turquia"
"da" = "tyrkiet"
"de" = "türkei"
"et" = "türgi"
"en" = "türkiye"
"es" = "turquía"
"fr" = "turquie"
"oc" = "turquia"
"lb" = "tierkei"
"ga" = "an-tuirc"
"hr" = "turska"
"it" = "turchia"
"lt" = "turkija"
"lv" = "turcija"
"nl" = "turkije"
"hu" = "törökország"
"no" = "tyrkia"
"pl" = "turcja"
"pt-PT" = "turquia"
"ro" = "turcia"
"sk" = "turecko"
"sl" = "turčija"
"sr" = "турска"
"fi" = "turkki"
"sv" = "turkiet"
"ru" = "турция"
"uk" = "туреччина"
"el" = "τουρκία"
"zh-CN" = "土耳其"
"zh-TW" = "土耳其"
"ja" = "トルコ"
"ko" = "튀르키예"
"bg" = "турция"
"cs" = "turecko"
"mt" = "it-turkija"

[country.codes]
gisco_cntr_id = "TR"
iso_3166_1_alpha2 = "TR"
iso_3166_1_alpha3 = "TUR"
