schema_version = 1

[[country]]
id = "UA"
kind = "country"
official_languages = ["uk"]

[country.names]
"ca" = "Ucraïna"
"da" = "Ukraine"
"de" = "Ukraine"
"et" = "Ukraina"
"en" = "Ukraine"
"es" = "Ucrania"
"fr" = "Ukraine"
"oc" = "Ucraïna"
"lb" = "Ukrain"
"ga" = "an Úcráin"
"hr" = "Ukrajina"
"it" = "Ucraina"
"lt" = "Ukraina"
"lv" = "Ukraina"
"nl" = "Oekraïne"
"hu" = "Ukrajna"
"no" = "Ukraina"
"pl" = "Ukraina"
"pt-PT" = "Ucrânia"
"ro" = "Ucraina"
"sk" = "Ukrajina"
"sl" = "Ukrajina"
"sr" = "Украјина"
"fi" = "Ukraina"
"sv" = "Ukraina"
"ru" = "Украина"
"uk" = "Україна"
"el" = "Ουκρανία"
"zh-CN" = "乌克兰"
"zh-TW" = "烏克蘭"
"ja" = "ウクライナ"
"ko" = "우크라이나"
"bg" = "Украйна"
"cs" = "Ukrajina"
"mt" = "l-Ukrajna"

[country.slugs]
"ca" = "ucraïna"
"da" = "ukraine"
"de" = "ukraine"
"et" = "ukraina"
"en" = "ukraine"
"es" = "ucrania"
"fr" = "ukraine"
"oc" = "ucraïna"
"lb" = "ukrain"
"ga" = "an-úcráin"
"hr" = "ukrajina"
"it" = "ucraina"
"lt" = "ukraina"
"lv" = "ukraina"
"nl" = "oekraïne"
"hu" = "ukrajna"
"no" = "ukraina"
"pl" = "ukraina"
"pt-PT" = "ucrânia"
"ro" = "ucraina"
"sk" = "ukrajina"
"sl" = "ukrajina"
"sr" = "украјина"
"fi" = "ukraina"
"sv" = "ukraina"
"ru" = "украина"
"uk" = "україна"
"el" = "ουκρανία"
"zh-CN" = "乌克兰"
"zh-TW" = "烏克蘭"
"ja" = "ウクライナ"
"ko" = "우크라이나"
"bg" = "украйна"
"cs" = "ukrajina"
"mt" = "l-ukrajna"

[country.codes]
gisco_cntr_id = "UA"
iso_3166_1_alpha2 = "UA"
iso_3166_1_alpha3 = "UKR"
