schema_version = 1

[[country]]
id = "UK"
kind = "country"
official_languages = ["en"]

[country.names]
"ca" = "Regne Unit"
"da" = "Storbritannien"
"de" = "Vereinigtes Königreich"
"et" = "Ühendkuningriik"
"en" = "United Kingdom"
"es" = "Reino Unido"
"fr" = "Royaume-Uni"
"oc" = "Reiaume Unit"
"lb" = "Groussbritannien"
"ga" = "an Ríocht Aontaithe"
"hr" = "Ujedinjeno Kraljevstvo"
"it" = "Regno Unito"
"lt" = "Jungtinė Karalystė"
"lv" = "Apvienotā Karaliste"
"nl" = "Verenigd Koninkrijk"
"hu" = "Egyesült Királyság"
"no" = "Storbritannia"
"pl" = "Wielka Brytania"
"pt-PT" = "Reino Unido"
"ro" = "Regatul Unit"
"sk" = "Spojené kráľovstvo"
"sl" = "Združeno kraljestvo"
"sr" = "Уједињено Краљевство"
"fi" = "Iso-Britannia"
"sv" = "Storbritannien"
"ru" = "Великобритания"
"uk" = "Велика Британія"
"el" = "Ηνωμένο Βασίλειο"
"zh-CN" = "英国"
"zh-TW" = "英國"
"ja" = "イギリス"
"ko" = "영국"
"bg" = "Обединеното кралство"
"cs" = "Spojené království"
"mt" = "ir-Renju Unit"

[country.slugs]
"ca" = "regne-unit"
"da" = "storbritannien"
"de" = "vereinigtes-königreich"
"et" = "ühendkuningriik"
"en" = "united-kingdom"
"es" = "reino-unido"
"fr" = "royaume-uni"
"oc" = "reiaume-unit"
"lb" = "groussbritannien"
"ga" = "an-ríocht-aontaithe"
"hr" = "ujedinjeno-kraljevstvo"
"it" = "regno-unito"
"lt" = "jungtinė-karalystė"
"lv" = "apvienotā-karaliste"
"nl" = "verenigd-koninkrijk"
"hu" = "egyesült-királyság"
"no" = "storbritannia"
"pl" = "wielka-brytania"
"pt-PT" = "reino-unido"
"ro" = "regatul-unit"
"sk" = "spojené-kráľovstvo"
"sl" = "združeno-kraljestvo"
"sr" = "уједињено-краљевство"
"fi" = "iso-britannia"
"sv" = "storbritannien"
"ru" = "великобритания"
"uk" = "велика-британія"
"el" = "ηνωμένο-βασίλειο"
"zh-CN" = "英国"
"zh-TW" = "英國"
"ja" = "イギリス"
"ko" = "영국"
"bg" = "обединеното-кралство"
"cs" = "spojené-království"
"mt" = "ir-renju-unit"

[country.codes]
gisco_cntr_id = "UK"
iso_3166_1_alpha2 = "GB"
iso_3166_1_alpha3 = "GBR"
