schema_version = 1

[[country]]
id = "US"
kind = "country"
official_languages = ["en"]

[country.names]
"ca" = "Estats Units"
"da" = "USA"
"de" = "Vereinigte Staaten"
"et" = "Ameerika Ühendriigid"
"en" = "United States"
"es" = "Estados Unidos"
"fr" = "États-Unis"
"oc" = "Estats Units"
"lb" = "Vereenegt Staaten"
"ga" = "Stáit Aontaithe Mheiriceá"
"hr" = "Sjedinjene Američke Države"
"it" = "Stati Uniti"
"lt" = "Jungtinės Valstijos"
"lv" = "Amerikas Savienotās Valstis"
"nl" = "Verenigde Staten"
"hu" = "Egyesült Államok"
"no" = "USA"
"pl" = "Stany Zjednoczone"
"pt-PT" = "Estados Unidos"
"ro" = "Statele Unite ale Americii"
"sk" = "Spojené štáty"
"sl" = "Združene države Amerike"
"sr" = "Сједињене Државе"
"fi" = "Yhdysvallat"
"sv" = "USA"
"ru" = "Соединенные Штаты"
"uk" = "Сполучені Штати"
"el" = "Ηνωμένες Πολιτείες"
"zh-CN" = "美国"
"zh-TW" = "美國"
"ja" = "アメリカ合衆国"
"ko" = "미국"
"bg" = "Съединени щати"
"cs" = "Spojené státy"
"mt" = "l-Istati Uniti"

[country.slugs]
"ca" = "estats-units"
"da" = "usa"
"de" = "vereinigte-staaten"
"et" = "ameerika-ühendriigid"
"en" = "united-states"
"es" = "estados-unidos"
"fr" = "états-unis"
"oc" = "estats-units"
"lb" = "vereenegt-staaten"
"ga" = "stáit-aontaithe-mheiriceá"
"hr" = "sjedinjene-američke-države"
"it" = "stati-uniti"
"lt" = "jungtinės-valstijos"
"lv" = "amerikas-savienotās-valstis"
"nl" = "verenigde-staten"
"hu" = "egyesült-államok"
"no" = "usa"
"pl" = "stany-zjednoczone"
"pt-PT" = "estados-unidos"
"ro" = "statele-unite-ale-americii"
"sk" = "spojené-štáty"
"sl" = "združene-države-amerike"
"sr" = "сједињене-државе"
"fi" = "yhdysvallat"
"sv" = "usa"
"ru" = "соединенные-штаты"
"uk" = "сполучені-штати"
"el" = "ηνωμένεσ-πολιτείεσ"
"zh-CN" = "美国"
"zh-TW" = "美國"
"ja" = "アメリカ合衆国"
"ko" = "미국"
"bg" = "съединени-щати"
"cs" = "spojené-státy"
"mt" = "l-istati-uniti"

[country.codes]
gisco_cntr_id = "US"
iso_3166_1_alpha2 = "US"
iso_3166_1_alpha3 = "USA"
