schema_version = 1

[[country]]
id = "VA"
kind = "country"
official_languages = ["it", "la"]

[country.names]
"ca" = "Ciutat del Vaticà"
"da" = "Vatikanstaten"
"de" = "Vatikanstadt"
"et" = "Vatikan"
"en" = "Vatican City"
"es" = "Ciudad del Vaticano"
"fr" = "État de la Cité du Vatican"
"oc" = "Ciutat del Vatican"
"lb" = "Vatikanstad"
"ga" = "Cathair na Vatacáine"
"hr" = "Vatikan"
"it" = "Città del Vaticano"
"lt" = "Vatikano Miesto Valstybė"
"lv" = "Vatikāns"
"nl" = "Vaticaanstad"
"hu" = "Vatikán"
"no" = "Vatikanstaten"
"pl" = "Watykan"
"pt-PT" = "Cidade do Vaticano"
"ro" = "Statul Cetății Vaticanului"
"sk" = "Vatikán"
"sl" = "Vatikan"
"sr" = "Ватикан"
"fi" = "Vatikaani"
"sv" = "Vatikanstaten"
"ru" = "Ватикан"
"uk" = "Ватикан"
"el" = "Βατικανό"
"zh-CN" = "梵蒂冈"
"zh-TW" = "梵蒂岡"
"ja" = "バチカン市国"
"ko" = "바티칸 시국"
"bg" = "Ватикан"
"cs" = "Vatikán"
"mt" = "l-Istat tal-Belt tal-Vatikan"
"la" = "Civitas Vaticana"

[country.slugs]
"ca" = "ciutat-del-vaticà"
"da" = "vatikanstaten"
"de" = "vatikanstadt"
"et" = "vatikan"
"en" = "vatican-city"
"es" = "ciudad-del-vaticano"
"fr" = "état-de-la-cité-du-vatican"
"oc" = "ciutat-del-vatican"
"lb" = "vatikanstad"
"ga" = "cathair-na-vatacáine"
"hr" = "vatikan"
"it" = "città-del-vaticano"
"lt" = "vatikano-miesto-valstybė"
"lv" = "vatikāns"
"nl" = "vaticaanstad"
"hu" = "vatikán"
"no" = "vatikanstaten"
"pl" = "watykan"
"pt-PT" = "cidade-do-vaticano"
"ro" = "statul-cetății-vaticanului"
"sk" = "vatikán"
"sl" = "vatikan"
"sr" = "ватикан"
"fi" = "vatikaani"
"sv" = "vatikanstaten"
"ru" = "ватикан"
"uk" = "ватикан"
"el" = "βατικανό"
"zh-CN" = "梵蒂冈"
"zh-TW" = "梵蒂岡"
"ja" = "バチカン市国"
"ko" = "바티칸-시국"
"bg" = "ватикан"
"cs" = "vatikán"
"mt" = "l-istat-tal-belt-tal-vatikan"

[country.codes]
gisco_cntr_id = "VA"
iso_3166_1_alpha2 = "VA"
iso_3166_1_alpha3 = "VAT"
