schema_version = 1

[[country]]
id = "VE"
kind = "country"
official_languages = ["es"]

[country.names]
"ca" = "Veneçuela"
"da" = "Venezuela"
"de" = "Venezuela"
"et" = "Venezuela"
"en" = "Venezuela"
"es" = "Venezuela"
"fr" = "Venezuela"
"oc" = "Veneçuèla"
"lb" = "Venezuela"
"ga" = "Veiniséala"
"hr" = "Venezuela"
"it" = "Venezuela"
"lt" = "Venesuela"
"lv" = "Venecuēla"
"nl" = "Venezuela"
"hu" = "Venezuela"
"no" = "Venezuela"
"pl" = "Wenezuela"
"pt-PT" = "Venezuela"
"ro" = "Venezuela"
"sk" = "Venezuela"
"sl" = "Venezuela"
"sr" = "Венецуела"
"fi" = "Venezuela"
"sv" = "Venezuela"
"ru" = "Венесуэла"
"uk" = "Венесуела"
"el" = "Βενεζουέλα"
"zh-CN" = "委内瑞拉"
"zh-TW" = "委內瑞拉"
"ja" = "ベネズエラ"
"ko" = "베네수엘라"
"bg" = "Венецуела"
"cs" = "Venezuela"
"mt" = "il-Venezwela"

[country.slugs]
"ca" = "veneçuela"
"da" = "venezuela"
"de" = "venezuela"
"et" = "venezuela"
"en" = "venezuela"
"es" = "venezuela"
"fr" = "venezuela"
"oc" = "veneçuèla"
"lb" = "venezuela"
"ga" = "veiniséala"
"hr" = "venezuela"
"it" = "venezuela"
"lt" = "venesuela"
"lv" = "venecuēla"
"nl" = "venezuela"
"hu" = "venezuela"
"no" = "venezuela"
"pl" = "wenezuela"
"pt-PT" = "venezuela"
"ro" = "venezuela"
"sk" = "venezuela"
"sl" = "venezuela"
"sr" = "венецуела"
"fi" = "venezuela"
"sv" = "venezuela"
"ru" = "венесуэла"
"uk" = "венесуела"
"el" = "βενεζουέλα"
"zh-CN" = "委内瑞拉"
"zh-TW" = "委內瑞拉"
"ja" = "ベネズエラ"
"ko" = "베네수엘라"
"bg" = "венецуела"
"cs" = "venezuela"
"mt" = "il-venezwela"

[country.codes]
gisco_cntr_id = "VE"
iso_3166_1_alpha2 = "VE"
iso_3166_1_alpha3 = "VEN"
