schema_version = 1

[[country]]
id = "VI"
kind = "country"
official_languages = ["en"]

[country.names]
"ca" = "Illes Verges dels Estats Units"
"da" = "De Amerikanske Jomfruøer"
"de" = "Amerikanische Jungferninseln"
"et" = "USA Neitsisaared"
"en" = "U.S. Virgin Islands"
"es" = "Islas Vírgenes de EE. UU."
"fr" = "Îles Vierges des États-Unis"
"oc" = "Illas Verges estatsunidencas"
"lb" = "Amerikanesch Joffereninselen"
"ga" = "Oileáin Mheiriceánacha na Maighdean"
"hr" = "Američki Djevičanski Otoci"
"it" = "Isole Vergini Americane"
"lt" = "Jungtinių Valstijų Mergelių Salos"
"lv" = "ASV Virdžīnas"
"nl" = "Amerikaanse Maagdeneilanden"
"hu" = "Amerikai Virgin-szigetek"
"no" = "De amerikanske jomfruøyene"
"pl" = "Wyspy Dziewicze Stanów Zjednoczonych"
"pt-PT" = "Ilhas Virgens dos EUA"
"ro" = "Insulele Virgine Americane"
"sk" = "Americké Panenské ostrovy"
"sl" = "Ameriški Deviški otoki"
"sr" = "Америчка Девичанска Острва"
"fi" = "Yhdysvaltain Neitsytsaaret"
"sv" = "Amerikanska Jungfruöarna"
"ru" = "Виргинские о-ва (США)"
"uk" = "Віргінські Острови (США)"
"el" = "Αμερικανικές Παρθένες Νήσοι"
"zh-CN" = "美属维尔京群岛"
"zh-TW" = "美屬維京群島"
"ja" = "米領ヴァージン諸島"
"ko" = "미국령 버진아일랜드"
"bg" = "Американски Вирджински острови"
"cs" = "Americké Panenské ostrovy"
"mt" = "il-Gżejjer Verġni tal-Istati Uniti"

[country.slugs]
"ca" = "illes-verges-dels-estats-units"
"da" = "de-amerikanske-jomfruøer"
"de" = "amerikanische-jungferninseln"
"et" = "usa-neitsisaared"
"en" = "u-s-virgin-islands"
"es" = "islas-vírgenes-de-ee-uu"
"fr" = "îles-vierges-des-états-unis"
"oc" = "illas-verges-estatsunidencas"
"lb" = "amerikanesch-joffereninselen"
"ga" = "oileáin-mheiriceánacha-na-maighdean"
"hr" = "američki-djevičanski-otoci"
"it" = "isole-vergini-americane"
"lt" = "jungtinių-valstijų-mergelių-salos"
"lv" = "asv-virdžīnas"
"nl" = "amerikaanse-maagdeneilanden"
"hu" = "amerikai-virgin-szigetek"
"no" = "de-amerikanske-jomfruøyene"
"pl" = "wyspy-dziewicze-stanów-zjednoczonych"
"pt-PT" = "ilhas-virgens-dos-eua"
"ro" = "insulele-virgine-americane"
"sk" = "americké-panenské-ostrovy"
"sl" = "ameriški-deviški-otoki"
"sr" = "америчка-девичанска-острва"
"fi" = "yhdysvaltain-neitsytsaaret"
"sv" = "amerikanska-jungfruöarna"
"ru" = "виргинские-о-ва-сша"
"uk" = "віргінські-острови-сша"
"el" = "αμερικανικέσ-παρθένεσ-νήσοι"
"zh-CN" = "美属维尔京群岛"
"zh-TW" = "美屬維京群島"
"ja" = "米領ヴァージン諸島"
"ko" = "미국령-버진아일랜드"
"bg" = "американски-вирджински-острови"
"cs" = "americké-panenské-ostrovy"
"mt" = "il-gżejjer-verġni-tal-istati-uniti"

[country.codes]
gisco_cntr_id = "VI"
iso_3166_1_alpha2 = "VI"
iso_3166_1_alpha3 = "VIR"
