name: Release
on:
  push:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Compile Maple
      uses: redhat-actions/buildah-build@v2
      with:
        image: maple
        tags: ${{ github.sha }}
        containerfiles: | 
          ./containers/maple/Dockerfile

    - name: Push Maple To ghcr.io
      id: push-to-ghcr-maple
      uses: redhat-actions/push-to-registry@v2
      with:
        image: maple
        tags: ${{ github.sha }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
